// ════════════════════════════════════════════════════════════════════════════
// Fun Facts — absurd distance comparisons shown once per session
// ════════════════════════════════════════════════════════════════════════════

var FUN_FACTS = [

  // ── 0.1 – 1.0 km (The "Did I Even Start?" Range) ──────────────────────

  { km: 0.1, text: "100m done! That's one Usain Bolt world record. He'd have finished, showered, and done a press conference by now." },
  { km: 0.16, text: "160m! The exact length of the Great Pyramid of Giza's base. You've run around one side of a pyramid." },
  { km: 0.2, text: "200m — the length of the International Space Station. You've run from one end to the other. In space. Sort of." },
  { km: 0.3, text: "300m! That's the height of the Eiffel Tower laid on its side. You just outran a toppled French landmark." },
  { km: 0.4, text: "400m — one lap of an Olympic track. You're officially an athlete. The Olympic committee will be in touch." },
  { km: 0.42, text: "420m — the length of 4.2 blue whales nose to tail. You've just out-swum 4 whales. On land. On a treadmill." },
  { km: 0.5, text: "500m! That's approximately 2,000 slices of pizza laid end to end. You've earned at least one." },
  { km: 0.55, text: "550m — the length of the world's longest swimming pool (San Alfonso del Mar, Chile). You just ran across it without getting wet." },
  { km: 0.6, text: "600m! The length of 100 London double-decker buses. Please do not attempt to run on top of them." },
  { km: 0.7, text: "700m — roughly the distance the average person walks to find where they parked at IKEA." },
  { km: 0.8, text: "800m done! In the time it took you, a peregrine falcon could have dived 3.2km. But falcons can't use treadmills, so who's winning?" },
  { km: 0.83, text: "830m — the height of the Burj Khalifa. You've just run the world's tallest building. Sideways, but still." },
  { km: 0.9, text: "900m! You've covered the length of 9 football pitches. The crowd goes mild!" },
  { km: 1.0, text: "1km! The average person walks 1km in their house per day just looking for their phone." },

  // ── 1.0 – 2.0 km (The "Technically Exercise" Range) ───────────────────

  { km: 1.05, text: "1.05km — the exact length of the Golden Gate Bridge. You just ran across San Francisco Bay. Virtually." },
  { km: 1.1, text: "1.1km! That's approximately the distance light travels in 3.7 microseconds. You were slightly slower." },
  { km: 1.15, text: "1.15km — the length of the world's longest bar (Barras, New Madrid). You could have done a pub crawl without leaving the building." },
  { km: 1.2, text: "1.2km! Fun fact: this is the average distance a squirrel runs per day. You're keeping pace with a squirrel. Be proud." },
  { km: 1.25, text: "1.25km — that's 1,250 adult humans lying head to toe. Please don't try to verify this." },
  { km: 1.3, text: "1.3km! The distance an average sneeze travels before the droplets settle. Gesundheit." },
  { km: 1.4, text: "1.4km — approximately the distance from the Earth's surface to the cruising altitude of a very confused bird." },
  { km: 1.5, text: "1.5km! You've run the length of 15 Titanics. None of them sank this time." },
  { km: 1.6, text: "1.6km — one mile! Known in America as 'a short drive' and in the UK as 'a nice walk to the pub'." },
  { km: 1.61, text: "Exactly one mile! The distance Roger Bannister ran in under 4 minutes in 1954. No pressure." },
  { km: 1.7, text: "1.7km — the length of the Channel Tunnel's undersea section divided by 30. You're 3.3% of the way to France!" },
  { km: 1.8, text: "1.8km! That's 7,200 bananas laid end to end. We measured. (We didn't measure.)" },
  { km: 1.85, text: "1.85km — the average distance a dog drags you on 'just a quick walk around the block'." },
  { km: 1.9, text: "1.9km! The exact distance your food delivery driver's GPS says they are from your house, perpetually, for 20 minutes." },

  // ── 2.0 – 5.0 km (The "I'm Walking There" Range) ─────────────────────

  { km: 2.0, text: "2km! Also known as 'The String Method' — tie a 2km string to your gatepost; when it tightens, it's time to turn back." },
  { km: 2.04, text: "2.04km! The distance between the two closest parkruns in the world — Broadbeach Waters to Surfers Paradise." },
  { km: 2.1, text: "2.1km — the distance you walk in a supermarket when you 'only needed milk'." },
  { km: 2.2, text: "2.2km! That's the distance from home plate to the centre field fence in 14 baseball stadiums laid end to end." },
  { km: 2.3, text: "2.3km — approximately how far you walk at an airport between 'Gate B2' and the actual Gate B2." },
  { km: 2.4, text: "2.4km! The width of the English Channel at its narrowest. You could have swum to France. But this is nicer." },
  { km: 2.5, text: "2.5km — the average distance a chicken can fly before landing. You've just outrun a flying chicken." },
  { km: 2.6, text: "2.6km! That's how far the Mars rover Opportunity drove in its first 90 days. It took it 90 days. You're faster than a Mars rover." },
  { km: 2.7, text: "2.7km — the length of the Las Vegas Strip. You've just power-walked past every casino without losing a penny." },
  { km: 2.8, text: "2.8km! The distance a sloth covers in an entire day. You've done a sloth's daily commute." },
  { km: 2.9, text: "2.9km — fun fact: a garden snail would take about 33 hours to cover this distance. You're marginally faster." },
  { km: 3.0, text: "3km! The exact distance where your pet decides they are too tired to walk, forcing you to carry them." },
  { km: 3.1, text: "3.1km — in the US this is a '5K' because they round generously. The American way." },
  { km: 3.2, text: "3.2km! Two miles! The distance where 'going for a quick jog' stops being quick." },
  { km: 3.3, text: "3.3km — the approximate depth of the deepest mine on Earth (Mponeng, South Africa). You've run to the Earth's bowels." },
  { km: 3.4, text: "3.4km! The length of the world's longest train (BHP, Australia). You just outran a train. Admittedly a very slow one." },
  { km: 3.5, text: "3.5km — the average distance between Starbucks locations in a major city. You could have had a latte by now." },
  { km: 3.6, text: "3.6km! The average distance a golden retriever runs in circles before lying in the exact spot you wanted to sit." },
  { km: 3.7, text: "3.7km — roughly the height of the tallest waterfall (Angel Falls). You've run off a cliff. Metaphorically." },
  { km: 3.8, text: "3.8km! The diameter of the Moon is 3,474km, so you've covered 0.1% of the Moon. Moon runner!" },
  { km: 3.9, text: "3.9km — the distance from Westminster to Tower Bridge. You've just jogged the Thames. Without the pigeons." },
  { km: 4.0, text: "4km done! That's approximately 10,000 steps, or one 'target' on your fitness tracker's constant nagging." },
  { km: 4.1, text: "4.1km! The length of the world's longest bridge over water (Lake Pontchartrain, Louisiana). Don't look down." },
  { km: 4.2, text: "4.2km — the exact distance light travels in 14 microseconds. You took slightly longer." },
  { km: 4.3, text: "4.3km! That's 21,500 toilet rolls unrolled end to end. We're not sure why we calculated this." },
  { km: 4.4, text: "4.4km — the average distance a lost tourist walks in London before admitting they need Google Maps." },
  { km: 4.5, text: "4.5km! The width of the Strait of Gibraltar. You've just run from Europe to Africa. Dry." },
  { km: 4.6, text: "4.6km — you've run the entire length of the world's longest IKEA (Kungens Kurva, Sweden). Exit through the marketplace." },
  { km: 4.7, text: "4.7km! A flea jumping 150 times its body length would need 15,700 jumps to match this. You win." },
  { km: 4.8, text: "4.8km — three miles! The distance where 'a bit of exercise' becomes 'what have I done'." },
  { km: 4.9, text: "4.9km! Nearly 5K. The distance where you start rounding up and telling people 'I did 5K today'." },

  // ── 5.0 – 10.0 km (The "Getting Serious" Range) ──────────────────────

  { km: 5.0, text: "5K! A 'short' run that doesn't kill you, but makes you feel authorized to eat an entire pizza afterward." },
  { km: 5.1, text: "5.1km! You've run further than the depth of the Mariana Trench (if it were horizontal, which it isn't)." },
  { km: 5.2, text: "5.2km — roughly the distance a hamster runs on its wheel per night. You're living the hamster life." },
  { km: 5.3, text: "5.3km! That's 5,300 king-size Mars bars laid end to end. You've earned approximately 0.3 of them calorie-wise." },
  { km: 5.4, text: "5.4km — the length of the runway at Kennedy Space Center. Clear for launch!" },
  { km: 5.5, text: "5.5km! Equivalent to the longest runway in the world (Qamdo Bamda Airport, Tibet). Clear for landing!" },
  { km: 5.6, text: "5.6km — the average distance a bee flies per day. You are now officially as busy as a bee." },
  { km: 5.7, text: "5.7km! The distance from Buckingham Palace to the O2 Arena. Royal run complete." },
  { km: 5.8, text: "5.8km — fun fact: this is approximately the altitude where commercial aircraft reach cruising speed. Seatbelts on." },
  { km: 5.9, text: "5.9km! That's 23,600 Cadbury Creme Eggs in a line. Easter sorted." },
  { km: 6.0, text: "6km! The perfect distance to walk to feel healthy, only to ruin it by buying a coffee and cake at the turnaround point." },
  { km: 6.1, text: "6.1km — the diameter of Mars's largest moon, Phobos. You've run across a moon!" },
  { km: 6.2, text: "6.2km! Nearly 4 miles. At this point you can legitimately call yourself 'a runner' at dinner parties." },
  { km: 6.3, text: "6.3km — the length of the Channel Tunnel's French section. Bonjour!" },
  { km: 6.4, text: "6.4km! Four miles! The distance that separates 'jogger' from 'actually quite fit person'." },
  { km: 6.5, text: "6.5km — the average distance between two pubs in rural England. You've done a proper pub-to-pub." },
  { km: 6.6, text: "6.6km! That's the height you'd reach if you stacked 8,400 people on each other's shoulders. Health & safety would object." },
  { km: 6.7, text: "6.7km — approximately the distance the Great Wall of China's most popular tourist section covers." },
  { km: 6.8, text: "6.8km! A cheetah could cover this in about 3 minutes. But cheetahs don't get participation medals." },
  { km: 6.9, text: "6.9km — you've run the entire length of the Palm Jumeirah in Dubai. No sand in your shoes." },
  { km: 7.0, text: "7km! Seven thousand metres. In the 1800s this would have been considered a full day's journey. With a horse." },
  { km: 7.1, text: "7.1km — the depth of the Puerto Rico Trench. If you fell in, at least you'd have run enough to justify the rescue helicopter." },
  { km: 7.2, text: "7.2km! That's 28,800 sausages laid end to end. Linked, obviously." },
  { km: 7.3, text: "7.3km — the height of Mount Vinson, Antarctica's highest peak. You've summited Antarctica. From your living room." },
  { km: 7.4, text: "7.4km! 4.6 miles. The distance where you start composing your Strava caption in your head." },
  { km: 7.5, text: "7.5km! A distance that is 'too long to be a fun run, but too short to be a real, meaningful long run'." },
  { km: 7.6, text: "7.6km — you've run the entire length of Loch Ness. Nessie was too slow to keep up." },
  { km: 7.7, text: "7.7km! The width of the Dead Sea. You could have floated it instead, but where's the glory in that?" },
  { km: 7.8, text: "7.8km — approximately how far you walk on a family trip to the zoo when your kids want to see EVERYTHING." },
  { km: 7.9, text: "7.9km! That's the distance from the Louvre to the Eiffel Tower and back. Cultural AND fit." },
  { km: 8.0, text: "8km! Five miles! The distance where runners stop saying 'it's just a short run' and start saying 'I went for a run'." },
  { km: 8.05, text: "5 miles exactly! In running terms, this is the 'no man's land' between 'quick jog' and 'proper training run'." },
  { km: 8.1, text: "8.1km — the circumference of the Large Hadron Collider at CERN. You've run around the world's biggest science experiment." },
  { km: 8.23, text: "8.23km! The specific, annoying, non-round distance you end up running because you took a wrong turn." },
  { km: 8.3, text: "8.3km — the altitude of Mount Everest's summit (8,849m, close enough). You've Everested on flat ground!" },
  { km: 8.5, text: "8.5km! The approximate length of the Channel Tunnel's English section. You've tunnelled to Folkestone." },
  { km: 8.6, text: "8.6km — you've run further than the world's longest aircraft carrier (USS Gerald Ford, 337m) 25 times over." },
  { km: 8.7, text: "8.7km! That's 34,800 regulation Subway footlong sandwiches. Eat fresh." },
  { km: 8.8, text: "8.8km — the exact height of Mount Everest in metres. Horizontal Everest: conquered." },
  { km: 8.85, text: "8,849m — the height of Everest, to the metre. You just ran to the top of the world. The flat way." },
  { km: 9.0, text: "9km! A 3-Munro Scottish hiking adventure that takes 4 hours, mostly because you keep stopping to take photos." },
  { km: 9.1, text: "9.1km — the average distance a dog sled team covers per hour. You're keeping up with huskies!" },
  { km: 9.2, text: "9.2km! You've run the entire Circuit de Monaco F1 track 2.7 times. Without the Armco barriers." },
  { km: 9.3, text: "9.3km — that's the length of the Gotthard Base Tunnel divided by 6. One sixth of Switzerland's finest hole." },
  { km: 9.4, text: "9.4km! Fun fact: a woodpecker pecks at 20 times per second. It would take one 47,000 pecks to cover this distance. Probably." },
  { km: 9.5, text: "9.5km — the width of Manhattan at its widest. You've crossed New York. Without the traffic." },
  { km: 9.6, text: "9.6km! Six miles. The distance where your body says 'I'm alive!' and your brain says 'Why are we doing this?'" },
  { km: 9.7, text: "9.7km — you've run the distance from 10 Downing Street to the London Eye. Three times." },
  { km: 9.8, text: "9.8km! Nearly 10K. You can almost taste the finisher's banana." },
  { km: 9.9, text: "9.9km — the most frustrating distance, because your GPS will round it to '10K' but your brain knows the truth." },

  // ── 10.0 – 15.0 km (The "Why Did I Agree To This" Range) ─────────────

  { km: 10.0, text: "10K! The 'happy medium' distance where you can still feel your legs but are technically a long-distance runner." },
  { km: 10.1, text: "10.1km — you've just outrun a world-class racewalker's best hour. And they looked ridiculous doing it." },
  { km: 10.5, text: "10.5km! The approximate width of the English Channel at Dover. You've swum it. Without getting wet." },
  { km: 11.0, text: "11km! The total length of corridors in the Pentagon. You could navigate the world's largest office building." },
  { km: 11.2, text: "11.2km — that's escape velocity from Earth... in km per SECOND. You're a bit slower, but gravity-bound running counts." },
  { km: 11.5, text: "11.5km! You've run the length of Hadrian's Wall divided by 10. One tenth Roman." },
  { km: 12.0, text: "12km! The distance where you realize you are 12km from home, it's raining, and your phone is dead." },
  { km: 12.5, text: "12.5km — that's 50,000 regulation baguettes. Vive la France!" },
  { km: 12.7, text: "12.7km! The length of the world's longest beach (Praia do Cassino, Brazil). Sand not included." },
  { km: 13.0, text: "13km! You've run further than most people drive to get a pint of milk." },
  { km: 13.1, text: "13.1km — you've run a 'fun half' of a half marathon. The 'un-fun half' is the second bit." },
  { km: 13.5, text: "13.5km! The height of the atmosphere's troposphere. You've run to where weather happens." },
  { km: 14.0, text: "14km — approximately the distance you walk on a day out at a theme park, except here there's no queuing." },
  { km: 14.5, text: "14.5km! The diameter of the asteroid that killed the dinosaurs. You've just outrun extinction." },
  { km: 15.0, text: "15km! The distance where your running app tells you 'Great Job!' while you are mentally planning how to re-route to the nearest pub." },
  { km: 15.0, text: "15km! Also known as the '3 Loops of 5km' walk, where you seriously contemplate quitting after loop 2." },

  // ── 15.0 – 21.0 km (The "This Is a Lifestyle Choice" Range) ──────────

  { km: 15.5, text: "15.5km — the 'Leadville Heavy Half,' because in trail running, 13.1 miles is apparently just a warm-up." },
  { km: 16.0, text: "16km! Ten miles! You've reached double digits in miles. This is not a drill." },
  { km: 16.1, text: "Exactly 10 miles! In many countries this earns you a free cup of tea and a concerned look from your family." },
  { km: 16.5, text: "16.5km — the approximate distance the ancient Greeks ran from Marathon to Athens. Then the messenger died. Stay hydrated." },
  { km: 17.0, text: "17km! You've run further than most Uber rides. And without the awkward small talk." },
  { km: 17.5, text: "17.5km — the circumference of Disney World's Magic Kingdom. You've lapped Mickey Mouse." },
  { km: 18.0, text: "18km! The distance from central London to Heathrow Airport. You've just run to your holiday." },
  { km: 18.5, text: "18.5km — you've run the length of Manhattan from tip to tip. Twice." },
  { km: 19.0, text: "19km! At this point, your legs have their own opinions about continuing." },
  { km: 19.3, text: "19.3km! Twelve miles! The exact distance where every runner discovers what their knees really think of them." },
  { km: 20.0, text: "20km! At this distance, you've burned enough calories to justify any meal. Literally anything. A full English at 11pm? Earned." },
  { km: 20.5, text: "20.5km — the altitude of the Concorde's cruising height (18,300m is close). You're supersonic. Ish." },

  // ── 21.0 – 30.0 km (The "Half Marathon and Beyond" Range) ─────────────

  { km: 21.0, text: "21km! Almost a half marathon! Your 'quick jog' has turned into a commitment longer than most Netflix series." },
  { km: 21.1, text: "HALF MARATHON! 13.1 miles! Known as 'half the pain of a full marathon but double the fun'." },
  { km: 21.5, text: "21.5km — you've now run further than the total length of every IKEA aisle. Without buying a single Billy bookcase." },
  { km: 22.0, text: "22km! The average height of weather balloons (about 20km). You've run to the edge of space. Horizontally." },
  { km: 23.0, text: "23km! The depth of the deepest ocean trench (about 11km). You've run there and halfway back." },
  { km: 24.0, text: "24km! Fifteen miles! At this point, other runners nod at you. You're in the club." },
  { km: 25.0, text: "25km! The length of the Channel Tunnel. You've tunnelled from England to France on your legs." },
  { km: 26.0, text: "26km — the altitude at which you'd need a spacesuit (about 19km). You've run past the need for oxygen." },
  { km: 27.0, text: "27km! The total length of Amsterdam's canal ring. You've run it without a single tulip." },
  { km: 28.0, text: "28km — you've run the entire length of the Suez Canal divided by 7. Very efficient shipping." },
  { km: 29.0, text: "29km! Eighteen miles! The distance where your watch battery starts to worry." },
  { km: 30.0, text: "30km! This is 'the wall' distance for marathon runners. If you're still reading this, you've broken through." },

  // ── 30.0 – 42.0 km (The "What Am I Doing With My Life" Range) ────────

  { km: 31.0, text: "31km! You've run the height of the tallest thunderstorm cloud (about 20km) 1.5 times. Vertical insanity." },
  { km: 32.0, text: "32km! Twenty miles! In ultra-running circles, this is called 'the warm-up is over'." },
  { km: 33.0, text: "33km — you've now run the entire Circuit de la Sarthe (Le Mans 24h track) 2.4 times. Without a car." },
  { km: 34.0, text: "34km! The diameter of Phobos, Mars's larger moon. You've run across a Martian moon." },
  { km: 35.0, text: "35km — the length of Hong Kong Island from east to west. Island conquered!" },
  { km: 36.0, text: "36km! The altitude of geostationary satellites. Your legs are now technically in orbit." },
  { km: 37.0, text: "37km! Twenty-three miles! Your legs have filed a formal complaint with HR." },
  { km: 38.0, text: "38km — the length of the world's longest lava tube (Kazumura Cave, Hawaii). You've spelunked without a torch." },
  { km: 39.0, text: "39km! At this distance, you've forgotten what stationary feels like." },
  { km: 40.0, text: "40km! Twenty-five miles. The original Marathon distance before the British royal family made it longer." },
  { km: 41.0, text: "41km — one kilometre from marathon distance. Your body is screaming. Your brain is composing the Instagram caption." },

  // ── 42.0+ km (The "Why" Range) ────────────────────────────────────────

  { km: 42.195, text: "MARATHON! 26.2 miles! You've run from Marathon to Athens. The original messenger died afterwards. You're doing better." },
  { km: 43.0, text: "43km! You've gone BEYOND marathon distance. Ultra territory. The snacks here are better." },
  { km: 45.0, text: "45km! You've run the total length of the London Underground's Central Line. Mind the gap." },
  { km: 50.0, text: "50K ULTRA! You've run further than most people drive to work. You absolute legend." },

  // ── More absurd comparisons across all ranges ─────────────────────────

  { km: 0.15, text: "150m! The distance a T-Rex could sprint before getting tired. You're fitter than a dinosaur." },
  { km: 0.22, text: "220m — the length of two Olympic swimming pools. You didn't even need goggles." },
  { km: 0.35, text: "350m! The approximate distance your toast flies when the toaster is set too high." },
  { km: 0.45, text: "450m — the height of the Empire State Building. You've run up it. Lying down." },
  { km: 0.65, text: "650m! That's approximately 1,300 adult cats lying nose to tail. They wouldn't cooperate, obviously." },
  { km: 0.75, text: "750m — the length of the world's longest wedding veil. You've outrun a bride." },
  { km: 0.95, text: "950m! Nearly a kilometre. Your GPS has been fighting internally about whether to round up." },
  { km: 1.35, text: "1.35km — the distance a kangaroo covers in 45 bounces. You needed considerably more steps." },
  { km: 1.45, text: "1.45km! That's 5,800 regulation Lego bricks in a line. Don't step on them barefoot." },
  { km: 1.55, text: "1.55km — the length of the world's longest sausage ever made (62.75km...wait, this is only 1.55km). Progress!" },
  { km: 1.65, text: "1.65km! The average distance between 'I'll be there in 5 minutes' and actually arriving." },
  { km: 1.75, text: "1.75km — the distance from Hogwarts to Hogsmeade. Butterbeer earned." },
  { km: 1.95, text: "1.95km! Nearly 2K. The distance where power walkers start overtaking people who said they were going for a 'run'." },
  { km: 2.15, text: "2.15km — the total distance walked by the average person while on hold with their broadband provider." },
  { km: 2.25, text: "2.25km! The diameter of the asteroid Bennu. You've outrun a space rock." },
  { km: 2.35, text: "2.35km — the distance from the nearest car park to the actual beach, according to your satnav." },
  { km: 2.45, text: "2.45km! That's 9,800 hot dogs end to end. National Hot Dog Day salutes you." },
  { km: 2.55, text: "2.55km — the distance an otter can swim in 15 minutes. You and the otter are now rivals." },
  { km: 2.65, text: "2.65km! You've run the length of Vatican City 6 times. Pope-level fitness." },
  { km: 2.75, text: "2.75km — the approximate distance from your front door to 'I should have driven'." },
  { km: 2.85, text: "2.85km! The distance of the Monaco Grand Prix circuit. You've completed a Formula 1 lap. Without the million-pound car." },
  { km: 2.95, text: "2.95km — nearly 3K! The distance where 'going for a walk' becomes 'going for a Walk' (capital W)." },
  { km: 3.15, text: "3.15km! Approximately Pi kilometres. You are now mathematically significant." },
  { km: 3.25, text: "3.25km — the distance from Platform 9¾ to the Great Hall at Hogwarts. (We estimated. The Sorting Hat was unhelpful.)" },
  { km: 3.35, text: "3.35km! That's 13,400 pencils laid end to end. Your legs are about as sharp as one right now." },
  { km: 3.45, text: "3.45km — the exact distance a carrier pigeon flies before realizing it left its message at home." },
  { km: 3.55, text: "3.55km! The distance from the top of the Shard to the ground. 88 times." },
  { km: 3.65, text: "3.65km — the average distance a teenager walks to find WiFi signal when on a family camping trip." },
  { km: 3.75, text: "3.75km! The distance from 'I'm nearly there' to actually being there, when you're on the phone to your mum." },
  { km: 3.85, text: "3.85km — approximately the distance from your desk to the office kitchen, if you work in a large corporate building and take the scenic route." },
  { km: 3.95, text: "3.95km! Nearly 4K. The distance where your watch vibrates excitedly like it's Christmas morning." },
  { km: 4.15, text: "4.15km — the diameter of Pluto's moon Charon. You've traversed an entire celestial body. A cold, dark one, but still." },
  { km: 4.25, text: "4.25km! That's 17,000 packets of digestive biscuits laid end to end. Dunking optional." },
  { km: 4.35, text: "4.35km — the total distance covered in the average game of Snakes & Ladders, if the board were life-sized." },
  { km: 4.45, text: "4.45km! The length of runway needed for a fully loaded A380. Clear for takeoff!" },
  { km: 4.55, text: "4.55km — the exact distance at which your enthusiasm graph crosses your tiredness graph." },
  { km: 4.65, text: "4.65km! You've run the length of the world's longest bridge (Danyang-Kunshan) divided by 35. Baby steps." },
  { km: 4.75, text: "4.75km — nearly 3 miles. The 'I could stop now and still feel good about myself' distance." },
  { km: 4.85, text: "4.85km! The average distance between coffee shops in central London. You've earned your flat white." },
  { km: 4.95, text: "4.95km — SO close to 5K. Your legs are negotiating with your brain for those last 50 metres." },
  { km: 5.15, text: "5.15km — you've passed 5K! Everything from here is bonus running. Tell everyone." },
  { km: 5.25, text: "5.25km! The distance a ball travels in a typical Premier League football match. You're match fit." },
  { km: 5.35, text: "5.35km — the length of the original Disneyland Railroad track times 4. Choo choo." },
  { km: 5.45, text: "5.45km! That's approximately 21,800 rolls of Sellotape unrolled. Sticky situation avoided." },
  { km: 5.55, text: "5.55km — triple nickels! A satisfyingly pointless numerical achievement." },
  { km: 5.65, text: "5.65km! The distance between the Sydney Opera House and Bondi Beach. G'day, runner!" },
  { km: 5.75, text: "5.75km — the average distance from 'the nearest parking space' to your actual destination in any major city." },
  { km: 5.85, text: "5.85km! That's 23,400 rubber ducks in a row. The world's most adorable distance measurement." },
  { km: 5.95, text: "5.95km — the exact distance where your running playlist runs out and you hear your own breathing for the first time." },
  { km: 6.15, text: "6.15km! The distance light travels in 20.5 microseconds. You were slightly behind schedule." },
  { km: 6.25, text: "6.25km — the total distance walked at a wedding between the ceremony, photos, reception, and dance floor." },
  { km: 6.35, text: "6.35km! That's 25,400 standard pork pies. A magnificent measurement for a magnificent snack." },
  { km: 6.45, text: "6.45km — four miles! The distance where you start wondering if your route home is actually shorter going the other way." },
  { km: 6.55, text: "6.55km! The average distance a dog runs at the beach before returning with someone else's ball." },
  { km: 6.65, text: "6.65km — the length of the world's longest sofa would need to be to seat 4,433 people. Hypothetically." },
  { km: 6.75, text: "6.75km! You've run from one end of Gibraltar to the other. Three times. On a rock." },
  { km: 6.85, text: "6.85km — the exact distance between 'I'm getting fit' and 'I need new trainers to cope with how fit I'm getting'." },
  { km: 6.95, text: "6.95km! Nearly 7K. Your body is producing endorphins. Your brain is producing excuses to stop." },
  { km: 7.15, text: "7.15km — the depth you'd need to drill to reach the Earth's outer core. You've drilled. Horizontally." },
  { km: 7.25, text: "7.25km! 4.5 miles! The distance where non-runners start looking at you with genuine concern." },
  { km: 7.35, text: "7.35km — the length of the world's longest swimming pool (if one existed). You'd need a LOT of chlorine." },
  { km: 7.45, text: "7.45km! That's approximately 29,800 cheese strings. Peelable performance." },
  { km: 7.55, text: "7.55km — the distance from Frodo's house to the Prancing Pony in Bree. One does not simply walk into Bree." },
  { km: 7.65, text: "7.65km! You've run the equivalent of climbing the Eiffel Tower 25 times. Without the lift." },
  { km: 7.75, text: "7.75km — the distance between confidence and collapse. You're on the right side. Probably." },
  { km: 7.85, text: "7.85km! The total distance covered by the average toddler in a soft play centre in 30 minutes. They were faster." },
  { km: 7.95, text: "7.95km — nearly 8K! At this point your treadmill is just a very expensive clothes hanger that you're actually using." },
  { km: 8.15, text: "8.15km! The circumference of CERN's Large Hadron Collider. You've run around the biggest science experiment ever built." },
  { km: 8.35, text: "8.35km — the distance you'd walk following the dotted line on a pirate's treasure map. X marks the spot." },
  { km: 8.45, text: "8.45km! That's 33,800 teaspoons laid end to end. We don't know why we measured this either." },
  { km: 8.55, text: "8.55km — the distance from your sofa to your fridge, if you live in a very, very long house." },
  { km: 8.65, text: "8.65km! The distance a penguin walks to its breeding ground. You're basically a penguin now. Waddle on." },
  { km: 8.75, text: "8.75km — the width of Lake Windermere times 8. That's a lot of lake." },
  { km: 8.95, text: "8.95km! Nearly 9K. Your legs have entered the negotiation phase." },
  { km: 9.15, text: "9.15km — you've run the length of the Champs-Elysees 5 times. Tres magnifique!" },
  { km: 9.25, text: "9.25km! The distance light travels inside a fibre optic cable in 46 microseconds. Tech runner!" },
  { km: 9.35, text: "9.35km — the exact distance at which 'I run for fun' becomes 'I run because I've forgotten how to stop'." },
  { km: 9.45, text: "9.45km! That's 37,800 slices of toast. You've run a full English breakfast in toast units." },
  { km: 9.55, text: "9.55km — the distance from the car park to the stadium at every major sporting event, apparently." },
  { km: 9.65, text: "9.65km! Six miles! At this point you're legally allowed to complain about it for the rest of the day." },
  { km: 9.75, text: "9.75km — the distance from 'I should really exercise more' to 'I will never exercise again'." },
  { km: 9.85, text: "9.85km! Nearly 10K. Your watch is counting down. Your legs are counting their regrets." },
  { km: 9.95, text: "9.95km — 50 metres from 10K. THE most frustrating distance. Run those last metres, you legend." },

  // ── Bonus weird measurements ──────────────────────────────────────────

  { km: 0.12, text: "120m — the length of Noah's Ark (allegedly). You've outrun biblical transport." },
  { km: 0.27, text: "270m! The range of a T-shirt cannon at a sports game. You're out of free merch territory." },
  { km: 0.33, text: "330m — the length of an aircraft carrier. You've jogged the USS Nimitz from stern to bow." },
  { km: 0.48, text: "480m! The distance of the longest hole-in-one in golf history. You ran it; they hit a tiny ball." },
  { km: 0.52, text: "520m — the depth of London's deepest tube station (Hampstead). You've tube-dived." },
  { km: 0.58, text: "580m! The length of 2,320 standard pencils. None of them had erasers." },
  { km: 0.72, text: "720m — the distance between Ronaldo's house and the nearest gym. He probably runs it daily." },
  { km: 0.78, text: "780m! The length of the QE2. You've cruised without the seasickness." },
  { km: 0.88, text: "880m — half a mile! Also known as '2 laps of a track' or '1 lap if you're bad at counting'." },
  { km: 1.08, text: "1.08km — the exact distance between saying 'I'll start running' and 'actually, I have started running'. Well done." },
  { km: 1.12, text: "1.12km! You've run the length of 4,480 hamsters. The hamsters did not volunteer for this measurement." },
  { km: 1.22, text: "1.22km — the distance from your office to that sandwich shop you always say is 'just around the corner'." },
  { km: 1.32, text: "1.32km! That's approximately 5,280 regulation Jaffa Cakes in a line. Moon or cake? Both." },
  { km: 1.42, text: "1.42km — the square root of 2, in kilometres. You are now irrational. Mathematically." },
  { km: 1.52, text: "1.52km! The distance between the two closest McDonald's in the world (on the Champs-Elysees, of course)." },
  { km: 1.62, text: "1.62km — the Golden Ratio in kilometres (1.618...). You are now aesthetically perfect." },
  { km: 1.72, text: "1.72km! The distance a cat wanders from home on average per night. Outdoor cat energy." },
  { km: 1.82, text: "1.82km — the average height of a giraffe times 333. A tower of giraffes would be impressed." },
  { km: 1.92, text: "1.92km! The width of the narrowest point of Panama. You've crossed between oceans." },
  { km: 2.02, text: "2.02km! A palindrome in distance. Same distance forwards as backwards. Deep." },
  { km: 2.12, text: "2.12km — the distance most people's 'shortcut' adds to their journey." },
  { km: 2.22, text: "2.22km! Triple twos! The distance that looks mildly satisfying on your tracking app." },
  { km: 2.32, text: "2.32km — the length of the runway at Heathrow's Terminal 5. Cleared for takeoff, but on foot." },
  { km: 2.42, text: "2.42km! 1.5 miles! The distance where your post-run stretch becomes more of a 'lean against a wall and groan'." },
  { km: 2.52, text: "2.52km — the height of Mount Olympus on Mars divided by 10,000. Baby steps toward Mars." },
  { km: 2.62, text: "2.62km! That's 10,480 credit cards laid end to end. Don't max them out." },
  { km: 2.72, text: "2.72km — approximately Euler's number (e=2.718...) in kilometres. Naturally exponential." },
  { km: 2.82, text: "2.82km! The distance from the Colosseum to the Vatican. Ancient to holy in one run." },
  { km: 2.92, text: "2.92km — the distance at which your Apple Watch gives you a standing ovation. Even though you're running." },
  { km: 3.05, text: "3.05km — the height of a basketball hoop in kilometres! Wait, that's only 3.05 metres. Never mind. You've still done well." },
  { km: 3.42, text: "3.42km! The answer to Life, the Universe and Everything... divided by 12.28. Close enough." },
  { km: 3.52, text: "3.52km — the distance from the bar to the bathroom at the world's longest pub crawl. Approximately." },
  { km: 3.62, text: "3.62km! That's 14,480 regulation golf tees. Fore!" },
  { km: 3.72, text: "3.72km — the diameter of Pluto divided by 640. You're 0.16% of the way across a dwarf planet!" },
  { km: 3.82, text: "3.82km! The average distance a tennis player runs in a 3-set match. Love-all." },
  { km: 3.92, text: "3.92km — the distance between 'warming up' and 'I might actually enjoy this'." },
  { km: 4.05, text: "4.05km! You've run 4,050 metres. That's 4,050,000 millimetres. Numbers! Impressive ones!" },
  { km: 4.42, text: "4.42km — the total length of the world's longest Scalextric track. Vroooom but on foot." },
  { km: 4.52, text: "4.52km! That's 18,080 regulation dominos. Don't knock the first one." },
  { km: 4.62, text: "4.62km — the average distance a pizza delivery driver travels. Except you arrive fitter and without garlic bread." },
  { km: 4.72, text: "4.72km! The distance from Central Park's south end to its north end. You've traversed Manhattan's lung." },
  { km: 4.82, text: "4.82km — three miles! The distance where joggers and runners are briefly the same thing." },
  { km: 4.92, text: "4.92km! That's approximately 19,680 fish fingers laid end to end. Captain Birdseye salutes you." },
  { km: 5.05, text: "5.05km! Just past 5K. You've entered the 'elite 5K runners' territory. (Territory: anyone who runs past 5K.)" },
  { km: 5.42, text: "5.42km — the total distance a Roomba covers cleaning an average living room. Over 4 hours. You're faster." },
  { km: 5.52, text: "5.52km! That's the distance between you and any meaningful regret about starting this run." },
  { km: 5.62, text: "5.62km — the exact distance where endorphins kick in, according to science. Do you feel them? No? Keep going." },
  { km: 5.72, text: "5.72km! The distance from your house to that gym membership you're not using. This is better anyway." },
  { km: 5.82, text: "5.82km — the distance a paper aeroplane would travel if it had unlimited fuel and ambition." },
  { km: 5.92, text: "5.92km! Nearly 6K. You've burned enough calories to justify telling everyone at work about it tomorrow." },
  { km: 6.42, text: "6.42km! Four miles exactly! In old money, that's 'a proper walk' — in new money, it's 'content for Instagram'." },
  { km: 6.52, text: "6.52km — the distance from your desk to the meeting room, if your office was designed by a marathon enthusiast." },
  { km: 6.62, text: "6.62km! Planck's constant starts with 6.626. You've achieved quantum fitness." },
  { km: 6.72, text: "6.72km — the distance a message in a bottle travels on a moderately breezy day. You're faster than glass." },
  { km: 6.82, text: "6.82km! That's 27,280 wine corks in a row. No judgement on how we collected that many." },
  { km: 6.92, text: "6.92km — the distance from 'casually fit' to 'annoyingly fit' on the social acceptability scale." },
  { km: 7.42, text: "7.42km! That's the boiling point of liquid nitrogen (-195.8 C) converted to... actually, that maths doesn't work. Good run though!" },
  { km: 7.52, text: "7.52km — the distance you walk in an average day at a music festival, not including the walk to find your tent at 3am." },
  { km: 7.62, text: "7.62km! That's also the calibre of a NATO standard rifle round in millimetres. Unrelated, but fun." },
  { km: 7.72, text: "7.72km — the distance a startled cat can run at full speed before crashing into a door. Multiplied by 10." },
  { km: 7.82, text: "7.82km! That's 31,280 Maltesers in a line. The lighter way to measure distance." },
  { km: 7.92, text: "7.92km — the exact distance where you transition from 'warm-up complete' to 'core workout established'." },
  { km: 8.42, text: "8.42km! The answer to Life, the Universe, and Everything divided by 5. Deeply meaningful." },
  { km: 8.52, text: "8.52km — the distance from your bed to the motivation you needed to do this run. You found it." },
  { km: 8.62, text: "8.62km! That's 34,480 standard AA batteries in a row. You're more energised than all of them." },
  { km: 8.72, text: "8.72km — the distance a hedgehog covers on its nightly patrol. You've been promoted to Head Hedgehog." },
  { km: 8.82, text: "8.82km! That's exactly how far your Uber driver was when the app said 'arriving now'." },
  { km: 8.92, text: "8.92km — the distance where 'just a run' becomes 'I should write a blog post about this'." },
  { km: 9.42, text: "9.42km! 3 times Pi kilometres! You are now a mathematical marvel on a treadmill." },
  { km: 9.52, text: "9.52km — the total distance walked by the average person during a game of Monopoly. Including trips to the fridge." },
  { km: 9.62, text: "9.62km! That's 38,480 paperclips. The world's most boring and specific measurement." },
  { km: 9.72, text: "9.72km — the distance from 'I run sometimes' to 'I am a runner' on your dating profile." },
  { km: 9.82, text: "9.82km! Nearly 10K. At this point, your body is 60% water and 40% determination." },
  { km: 10.2, text: "10.2km — that's 40,800 Wotsits in a row. Cheesy distance achieved." },
  { km: 10.8, text: "10.8km! The approximate distance a shopping trolley travels before developing a wonky wheel." },
  { km: 11.1, text: "11.1km! Triple ones. In bowling, you'd have a turkey. In running, you have sore legs." },
  { km: 11.5, text: "11.5km — the total distance walked during the average house move. But with fewer broken plates." },
  { km: 12.5, text: "12.5km! The distance from London Bridge to Big Ben and back. Twice. Touristy fitness." },
  { km: 13.5, text: "13.5km — you've now run further than a cricket ball has ever been hit (maximum about 170m times 79)." },
  { km: 14.5, text: "14.5km! Nine miles! The distance where you stop thinking in kilometres and start thinking in tea breaks." },
  { km: 15.5, text: "15.5km — the total distance covered in the average 90-minute football match. You're match fit AND extra time fit." },
  { km: 16.5, text: "16.5km! You've run from Trafalgar Square to Hampton Court Palace. Henry VIII approves." },
  { km: 17.5, text: "17.5km — the average distance an albatross glides without flapping. You did more flapping, but well done." },
  { km: 18.5, text: "18.5km! You've run further than the average London commute (11km). And you didn't have to deal with the Northern Line." },
  { km: 19.5, text: "19.5km — twelve miles! At this distance, you have permission to call any meal 'recovery nutrition'." },
  { km: 20.5, text: "20.5km! You've run from Paris's Arc de Triomphe to Versailles. Let them eat cake!" },
  { km: 22.5, text: "22.5km — you've run the length of the Panama Canal divided by 3.5. Intercontinental fitness." },
  { km: 23.5, text: "23.5km! The total distance a bee flies to make one tablespoon of honey. You've earned that tablespoon." },
  { km: 25.5, text: "25.5km — you've run from JFK Airport to Times Square. Without the taxi fare." },
  { km: 27.5, text: "27.5km! Seventeen miles. At this point, even your shadow looks tired." },
  { km: 30.5, text: "30.5km — nineteen miles! Your legs are sending you a strongly-worded letter." },
  { km: 32.5, text: "32.5km! You've run from central London to Gatwick Airport. Board your flight in running gear. Assert dominance." },
  { km: 35.5, text: "35.5km — twenty-two miles! The distance where runners have philosophical conversations with lamp posts." },
  { km: 37.5, text: "37.5km! You've run from Edinburgh Castle to Falkirk. William Wallace would be proud." },
  { km: 40.5, text: "40.5km — twenty-five miles! One mile from marathon distance. Your legs are just numbers now." },

  // ── Animals and nature themed ─────────────────────────────────────────

  { km: 0.18, text: "180m! The distance an average chicken can run before forgetting why. You're already more focused." },
  { km: 0.38, text: "380m — the distance a startled hedgehog curls up from danger, multiplied by... a lot. Hedgehog math." },
  { km: 0.62, text: "620m! The distance a determined tortoise covers in one hour. You've Aesop-ed that fable." },
  { km: 1.02, text: "1.02km — the distance a duck walks from the pond to steal your sandwich. Duck fitness unlocked." },
  { km: 1.38, text: "1.38km! The distance a salmon swims upstream to spawn, give or take. Less romantic on a treadmill." },
  { km: 2.08, text: "2.08km — the distance between you and any spider, at maximum. (We hope.)" },
  { km: 3.08, text: "3.08km! The distance a pigeon flies to deliver a message. Your message: 'I went running today'." },
  { km: 4.08, text: "4.08km — the distance a raccoon travels nightly to raid bins. You're trash panda fit!" },
  { km: 5.08, text: "5.08km! The distance an eagle's screech carries on a quiet day. You've outrun a sound wave. Sort of." },
  { km: 6.08, text: "6.08km — the distance between you and the nearest cat that is judging you right now." },
  { km: 7.08, text: "7.08km! The average distance a fox runs per night in urban London. You're as fit as a fox." },
  { km: 8.08, text: "8.08km — the average daily patrol distance of a wolf. You are the pack leader now." },
  { km: 9.08, text: "9.08km! The distance a homing pigeon covers in about 10 minutes. Show-off pigeons." },

  // ── Food themed ───────────────────────────────────────────────────────

  { km: 0.25, text: "250m! That's 1,000 Jelly Babies standing shoulder to shoulder. A gelatinous guard of honour." },
  { km: 1.15, text: "1.15km — the length of 4,600 Pringles laid flat. Once you pop, you can't stop. Same with running, apparently." },
  { km: 2.18, text: "2.18km! That's 8,720 Oreos in a row. Twist, lick, run." },
  { km: 3.18, text: "3.18km — the distance of 12,720 gummy bears marching single file. The gummy bear army salutes you." },
  { km: 4.18, text: "4.18km! That's 16,720 Skittles. Taste the rainbow; run the rainbow." },
  { km: 5.18, text: "5.18km — the length of 20,720 M&Ms. They melt in your hand, not on the treadmill." },
  { km: 6.18, text: "6.18km! That's 24,720 grains of rice in a very precise line. Asian grandmothers would be impressed." },
  { km: 7.18, text: "7.18km — 28,720 cocktail sausages. The world's most delicious unit of measurement." },
  { km: 8.18, text: "8.18km! 32,720 After Eight mints. It's always after eight somewhere." },
  { km: 9.18, text: "9.18km — 36,720 chunks of fudge. This run IS fudging amazing." },

  // ── Pop culture themed ────────────────────────────────────────────────

  { km: 1.21, text: "1.21km! 1.21 gigawatts! Great Scott! The DeLorean needs 1.21 of everything, apparently." },
  { km: 3.14, text: "3.14km! Pi kilometres! You've run a mathematically irrational distance. How fitting." },
  { km: 4.2, text: "4.2km — close to 42, the Answer to the Ultimate Question of Life, the Universe, and Everything. Divided by 10." },
  { km: 6.66, text: "6.66km! The Number of the Beast in kilometres. Highway to the fitness zone." },
  { km: 7.07, text: "7.07km! Bond distance. Shaken, not stirred, and slightly out of breath." },
  { km: 10.66, text: "10.66km — the Battle of Hastings was in 1066. You've run that year in metres. Historical fitness!" },

  // ── British humour themed ─────────────────────────────────────────────

  { km: 0.32, text: "320m! The exact distance from the front door to the bin on bin day, and back. In slippers. In the rain." },
  { km: 0.68, text: "680m — the distance from your seat to the bar at a cricket ground. The longest walk in sport." },
  { km: 1.28, text: "1.28km! The average distance between complaints about the weather in Britain." },
  { km: 2.28, text: "2.28km — the distance from 'I'll just have one biscuit' to eating the entire pack while walking to the kitchen." },
  { km: 3.28, text: "3.28km! The distance the average British person walks on Christmas Day between the sofa and the turkey." },
  { km: 4.28, text: "4.28km — the distance between 'slightly warm' and 'absolutely roasting' on the British temperature scale." },
  { km: 5.28, text: "5.28km! The total distance walked during a Sunday car boot sale, mostly looking at junk you'll never buy." },
  { km: 6.28, text: "6.28km — 2 times Pi! Also known as Tau. The mathematically superior circle constant, in kilometres." },
  { km: 7.28, text: "7.28km! The distance from 'I fancy a nice walk' to 'we should have brought waterproofs' in the Lake District." },
  { km: 8.28, text: "8.28km — the average distance between a British person and their nearest cup of tea." },
  { km: 9.28, text: "9.28km! The distance from thinking about the gym to actually going. You skipped the middleman. Legend." },
];
