// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: activitylog/ActivityLogMetadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityLogMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId             string                 `protobuf:"bytes,1,opt,name=workoutId,proto3" json:"workoutId,omitempty"`
	ShouldUploadLog       bool                   `protobuf:"varint,2,opt,name=shouldUploadLog,proto3" json:"shouldUploadLog,omitempty"`
	ContentId             string                 `protobuf:"bytes,3,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	HeroImageUrl          string                 `protobuf:"bytes,5,opt,name=heroImageUrl,proto3" json:"heroImageUrl,omitempty"`
	SocialImageUrl        string                 `protobuf:"bytes,6,opt,name=socialImageUrl,proto3" json:"socialImageUrl,omitempty"`
	ProgramId             string                 `protobuf:"bytes,7,opt,name=programId,proto3" json:"programId,omitempty"`
	VideoId               string                 `protobuf:"bytes,8,opt,name=videoId,proto3" json:"videoId,omitempty"`
	ListWorkoutId         string                 `protobuf:"bytes,9,opt,name=listWorkoutId,proto3" json:"listWorkoutId,omitempty"`
	LiveWorkoutId         string                 `protobuf:"bytes,10,opt,name=liveWorkoutId,proto3" json:"liveWorkoutId,omitempty"`
	LiveWorkoutScheduleId string                 `protobuf:"bytes,11,opt,name=liveWorkoutScheduleId,proto3" json:"liveWorkoutScheduleId,omitempty"`
	Origin                ActivityLogOrigin      `protobuf:"varint,12,opt,name=origin,proto3,enum=com.ifit.glassos.ActivityLogOrigin" json:"origin,omitempty"`
	Context               ActivityLogContext     `protobuf:"varint,13,opt,name=context,proto3,enum=com.ifit.glassos.ActivityLogContext" json:"context,omitempty"`
	Type                  ActivityLogType        `protobuf:"varint,14,opt,name=type,proto3,enum=com.ifit.glassos.ActivityLogType" json:"type,omitempty"`
	TypeDetail            string                 `protobuf:"bytes,15,opt,name=typeDetail,proto3" json:"typeDetail,omitempty"`
	ExternalType          string                 `protobuf:"bytes,16,opt,name=externalType,proto3" json:"externalType,omitempty"`
	CompletedMovements    []string               `protobuf:"bytes,17,rep,name=completedMovements,proto3" json:"completedMovements,omitempty"`
	Redundant             bool                   `protobuf:"varint,18,opt,name=redundant,proto3" json:"redundant,omitempty"`
	SleepScore            int32                  `protobuf:"varint,19,opt,name=sleepScore,proto3" json:"sleepScore,omitempty"`
	SeriesId              string                 `protobuf:"bytes,20,opt,name=seriesId,proto3" json:"seriesId,omitempty"`
	ChallengeId           string                 `protobuf:"bytes,21,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	WorkoutDriverFQN      string                 `protobuf:"bytes,22,opt,name=workoutDriverFQN,proto3" json:"workoutDriverFQN,omitempty"`
	ThirdPartyContentId   string                 `protobuf:"bytes,23,opt,name=thirdPartyContentId,proto3" json:"thirdPartyContentId,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActivityLogMetadata) Reset() {
	*x = ActivityLogMetadata{}
	mi := &file_activitylog_ActivityLogMetadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityLogMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityLogMetadata) ProtoMessage() {}

func (x *ActivityLogMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_activitylog_ActivityLogMetadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityLogMetadata.ProtoReflect.Descriptor instead.
func (*ActivityLogMetadata) Descriptor() ([]byte, []int) {
	return file_activitylog_ActivityLogMetadata_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityLogMetadata) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *ActivityLogMetadata) GetShouldUploadLog() bool {
	if x != nil {
		return x.ShouldUploadLog
	}
	return false
}

func (x *ActivityLogMetadata) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ActivityLogMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityLogMetadata) GetHeroImageUrl() string {
	if x != nil {
		return x.HeroImageUrl
	}
	return ""
}

func (x *ActivityLogMetadata) GetSocialImageUrl() string {
	if x != nil {
		return x.SocialImageUrl
	}
	return ""
}

func (x *ActivityLogMetadata) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *ActivityLogMetadata) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ActivityLogMetadata) GetListWorkoutId() string {
	if x != nil {
		return x.ListWorkoutId
	}
	return ""
}

func (x *ActivityLogMetadata) GetLiveWorkoutId() string {
	if x != nil {
		return x.LiveWorkoutId
	}
	return ""
}

func (x *ActivityLogMetadata) GetLiveWorkoutScheduleId() string {
	if x != nil {
		return x.LiveWorkoutScheduleId
	}
	return ""
}

func (x *ActivityLogMetadata) GetOrigin() ActivityLogOrigin {
	if x != nil {
		return x.Origin
	}
	return ActivityLogOrigin_ACT_LOG_ORIGIN_BIKE
}

func (x *ActivityLogMetadata) GetContext() ActivityLogContext {
	if x != nil {
		return x.Context
	}
	return ActivityLogContext_ACT_LOG_CONTEXT_ON_DEMAND
}

func (x *ActivityLogMetadata) GetType() ActivityLogType {
	if x != nil {
		return x.Type
	}
	return ActivityLogType_ACT_LOG_TYPE_CARDIO
}

func (x *ActivityLogMetadata) GetTypeDetail() string {
	if x != nil {
		return x.TypeDetail
	}
	return ""
}

func (x *ActivityLogMetadata) GetExternalType() string {
	if x != nil {
		return x.ExternalType
	}
	return ""
}

func (x *ActivityLogMetadata) GetCompletedMovements() []string {
	if x != nil {
		return x.CompletedMovements
	}
	return nil
}

func (x *ActivityLogMetadata) GetRedundant() bool {
	if x != nil {
		return x.Redundant
	}
	return false
}

func (x *ActivityLogMetadata) GetSleepScore() int32 {
	if x != nil {
		return x.SleepScore
	}
	return 0
}

func (x *ActivityLogMetadata) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *ActivityLogMetadata) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ActivityLogMetadata) GetWorkoutDriverFQN() string {
	if x != nil {
		return x.WorkoutDriverFQN
	}
	return ""
}

func (x *ActivityLogMetadata) GetThirdPartyContentId() string {
	if x != nil {
		return x.ThirdPartyContentId
	}
	return ""
}

var File_activitylog_ActivityLogMetadata_proto protoreflect.FileDescriptor

const file_activitylog_ActivityLogMetadata_proto_rawDesc = "" +
	"\n" +
	"%activitylog/ActivityLogMetadata.proto\x12\x10com.ifit.glassos\x1a\"activitylog/ActivityLogUtils.proto\"\x99\a\n" +
	"\x13ActivityLogMetadata\x12\x1c\n" +
	"\tworkoutId\x18\x01 \x01(\tR\tworkoutId\x12(\n" +
	"\x0fshouldUploadLog\x18\x02 \x01(\bR\x0fshouldUploadLog\x12\x1c\n" +
	"\tcontentId\x18\x03 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\"\n" +
	"\fheroImageUrl\x18\x05 \x01(\tR\fheroImageUrl\x12&\n" +
	"\x0esocialImageUrl\x18\x06 \x01(\tR\x0esocialImageUrl\x12\x1c\n" +
	"\tprogramId\x18\a \x01(\tR\tprogramId\x12\x18\n" +
	"\avideoId\x18\b \x01(\tR\avideoId\x12$\n" +
	"\rlistWorkoutId\x18\t \x01(\tR\rlistWorkoutId\x12$\n" +
	"\rliveWorkoutId\x18\n" +
	" \x01(\tR\rliveWorkoutId\x124\n" +
	"\x15liveWorkoutScheduleId\x18\v \x01(\tR\x15liveWorkoutScheduleId\x12;\n" +
	"\x06origin\x18\f \x01(\x0e2#.com.ifit.glassos.ActivityLogOriginR\x06origin\x12>\n" +
	"\acontext\x18\r \x01(\x0e2$.com.ifit.glassos.ActivityLogContextR\acontext\x125\n" +
	"\x04type\x18\x0e \x01(\x0e2!.com.ifit.glassos.ActivityLogTypeR\x04type\x12\x1e\n" +
	"\n" +
	"typeDetail\x18\x0f \x01(\tR\n" +
	"typeDetail\x12\"\n" +
	"\fexternalType\x18\x10 \x01(\tR\fexternalType\x12.\n" +
	"\x12completedMovements\x18\x11 \x03(\tR\x12completedMovements\x12\x1c\n" +
	"\tredundant\x18\x12 \x01(\bR\tredundant\x12\x1e\n" +
	"\n" +
	"sleepScore\x18\x13 \x01(\x05R\n" +
	"sleepScore\x12\x1a\n" +
	"\bseriesId\x18\x14 \x01(\tR\bseriesId\x12 \n" +
	"\vchallengeId\x18\x15 \x01(\tR\vchallengeId\x12*\n" +
	"\x10workoutDriverFQN\x18\x16 \x01(\tR\x10workoutDriverFQN\x120\n" +
	"\x13thirdPartyContentId\x18\x17 \x01(\tR\x13thirdPartyContentIdBA\n" +
	"\x1ccom.ifit.glassos.activitylogB\x18ActivityLogMetadataProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_activitylog_ActivityLogMetadata_proto_rawDescOnce sync.Once
	file_activitylog_ActivityLogMetadata_proto_rawDescData []byte
)

func file_activitylog_ActivityLogMetadata_proto_rawDescGZIP() []byte {
	file_activitylog_ActivityLogMetadata_proto_rawDescOnce.Do(func() {
		file_activitylog_ActivityLogMetadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activitylog_ActivityLogMetadata_proto_rawDesc), len(file_activitylog_ActivityLogMetadata_proto_rawDesc)))
	})
	return file_activitylog_ActivityLogMetadata_proto_rawDescData
}

var file_activitylog_ActivityLogMetadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_activitylog_ActivityLogMetadata_proto_goTypes = []any{
	(*ActivityLogMetadata)(nil), // 0: com.ifit.glassos.ActivityLogMetadata
	(ActivityLogOrigin)(0),      // 1: com.ifit.glassos.ActivityLogOrigin
	(ActivityLogContext)(0),     // 2: com.ifit.glassos.ActivityLogContext
	(ActivityLogType)(0),        // 3: com.ifit.glassos.ActivityLogType
}
var file_activitylog_ActivityLogMetadata_proto_depIdxs = []int32{
	1, // 0: com.ifit.glassos.ActivityLogMetadata.origin:type_name -> com.ifit.glassos.ActivityLogOrigin
	2, // 1: com.ifit.glassos.ActivityLogMetadata.context:type_name -> com.ifit.glassos.ActivityLogContext
	3, // 2: com.ifit.glassos.ActivityLogMetadata.type:type_name -> com.ifit.glassos.ActivityLogType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_activitylog_ActivityLogMetadata_proto_init() }
func file_activitylog_ActivityLogMetadata_proto_init() {
	if File_activitylog_ActivityLogMetadata_proto != nil {
		return
	}
	file_activitylog_ActivityLogUtils_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activitylog_ActivityLogMetadata_proto_rawDesc), len(file_activitylog_ActivityLogMetadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activitylog_ActivityLogMetadata_proto_goTypes,
		DependencyIndexes: file_activitylog_ActivityLogMetadata_proto_depIdxs,
		MessageInfos:      file_activitylog_ActivityLogMetadata_proto_msgTypes,
	}.Build()
	File_activitylog_ActivityLogMetadata_proto = out.File
	file_activitylog_ActivityLogMetadata_proto_goTypes = nil
	file_activitylog_ActivityLogMetadata_proto_depIdxs = nil
}
