// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: auth/AuthError.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthErrorCode int32

const (
	AuthErrorCode_AUTH_FAILURE        AuthErrorCode = 0
	AuthErrorCode_AUTH_LOGIN_REQUIRED AuthErrorCode = 1
	AuthErrorCode_AUTH_NETWORK_ERROR  AuthErrorCode = 2
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0: "AUTH_FAILURE",
		1: "AUTH_LOGIN_REQUIRED",
		2: "AUTH_NETWORK_ERROR",
	}
	AuthErrorCode_value = map[string]int32{
		"AUTH_FAILURE":        0,
		"AUTH_LOGIN_REQUIRED": 1,
		"AUTH_NETWORK_ERROR":  2,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_AuthError_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_auth_AuthError_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_auth_AuthError_proto_rawDescGZIP(), []int{0}
}

type AuthError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     AuthErrorCode          `protobuf:"varint,1,opt,name=errorCode,proto3,enum=com.ifit.glassos.AuthErrorCode" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	mi := &file_auth_AuthError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_auth_AuthError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_auth_AuthError_proto_rawDescGZIP(), []int{0}
}

func (x *AuthError) GetErrorCode() AuthErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return AuthErrorCode_AUTH_FAILURE
}

func (x *AuthError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth_AuthError_proto protoreflect.FileDescriptor

const file_auth_AuthError_proto_rawDesc = "" +
	"\n" +
	"\x14auth/AuthError.proto\x12\x10com.ifit.glassos\"d\n" +
	"\tAuthError\x12=\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x1f.com.ifit.glassos.AuthErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*R\n" +
	"\rAuthErrorCode\x12\x10\n" +
	"\fAUTH_FAILURE\x10\x00\x12\x17\n" +
	"\x13AUTH_LOGIN_REQUIRED\x10\x01\x12\x16\n" +
	"\x12AUTH_NETWORK_ERROR\x10\x02B4\n" +
	"\x15com.ifit.glassos.authB\x12AuthErrorCodeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_auth_AuthError_proto_rawDescOnce sync.Once
	file_auth_AuthError_proto_rawDescData []byte
)

func file_auth_AuthError_proto_rawDescGZIP() []byte {
	file_auth_AuthError_proto_rawDescOnce.Do(func() {
		file_auth_AuthError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_AuthError_proto_rawDesc), len(file_auth_AuthError_proto_rawDesc)))
	})
	return file_auth_AuthError_proto_rawDescData
}

var file_auth_AuthError_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_AuthError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_AuthError_proto_goTypes = []any{
	(AuthErrorCode)(0), // 0: com.ifit.glassos.AuthErrorCode
	(*AuthError)(nil),  // 1: com.ifit.glassos.AuthError
}
var file_auth_AuthError_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.AuthError.errorCode:type_name -> com.ifit.glassos.AuthErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_AuthError_proto_init() }
func file_auth_AuthError_proto_init() {
	if File_auth_AuthError_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_AuthError_proto_rawDesc), len(file_auth_AuthError_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_AuthError_proto_goTypes,
		DependencyIndexes: file_auth_AuthError_proto_depIdxs,
		EnumInfos:         file_auth_AuthError_proto_enumTypes,
		MessageInfos:      file_auth_AuthError_proto_msgTypes,
	}.Build()
	File_auth_AuthError_proto = out.File
	file_auth_AuthError_proto_goTypes = nil
	file_auth_AuthError_proto_depIdxs = nil
}
