// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/CaloriesBurnedService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaloriesBurnedService_CanRead_FullMethodName                    = "/com.ifit.glassos.CaloriesBurnedService/CanRead"
	CaloriesBurnedService_GetCaloriesBurned_FullMethodName          = "/com.ifit.glassos.CaloriesBurnedService/GetCaloriesBurned"
	CaloriesBurnedService_CaloriesBurnedSubscription_FullMethodName = "/com.ifit.glassos.CaloriesBurnedService/CaloriesBurnedSubscription"
	CaloriesBurnedService_GetCaloriesBurnedHistory_FullMethodName   = "/com.ifit.glassos.CaloriesBurnedService/GetCaloriesBurnedHistory"
)

// CaloriesBurnedServiceClient is the client API for CaloriesBurnedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaloriesBurnedServiceClient interface {
	// check whether CaloriesBurned is Readable
	CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// get the current CaloriesBurned relative to the current workout
	GetCaloriesBurned(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CaloriesBurnedMetric, error)
	// subscribe to CaloriesBurned updates relative to the current workout
	CaloriesBurnedSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CaloriesBurnedMetric], error)
	// gets a list of all of the CaloriesBurned changes for the given workout ID
	GetCaloriesBurnedHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*CaloriesBurnedMetricList, error)
}

type caloriesBurnedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaloriesBurnedServiceClient(cc grpc.ClientConnInterface) CaloriesBurnedServiceClient {
	return &caloriesBurnedServiceClient{cc}
}

func (c *caloriesBurnedServiceClient) CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, CaloriesBurnedService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caloriesBurnedServiceClient) GetCaloriesBurned(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CaloriesBurnedMetric, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaloriesBurnedMetric)
	err := c.cc.Invoke(ctx, CaloriesBurnedService_GetCaloriesBurned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *caloriesBurnedServiceClient) CaloriesBurnedSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CaloriesBurnedMetric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaloriesBurnedService_ServiceDesc.Streams[0], CaloriesBurnedService_CaloriesBurnedSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, CaloriesBurnedMetric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaloriesBurnedService_CaloriesBurnedSubscriptionClient = grpc.ServerStreamingClient[CaloriesBurnedMetric]

func (c *caloriesBurnedServiceClient) GetCaloriesBurnedHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*CaloriesBurnedMetricList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaloriesBurnedMetricList)
	err := c.cc.Invoke(ctx, CaloriesBurnedService_GetCaloriesBurnedHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaloriesBurnedServiceServer is the server API for CaloriesBurnedService service.
// All implementations must embed UnimplementedCaloriesBurnedServiceServer
// for forward compatibility.
type CaloriesBurnedServiceServer interface {
	// check whether CaloriesBurned is Readable
	CanRead(context.Context, *Empty) (*AvailabilityResponse, error)
	// get the current CaloriesBurned relative to the current workout
	GetCaloriesBurned(context.Context, *Empty) (*CaloriesBurnedMetric, error)
	// subscribe to CaloriesBurned updates relative to the current workout
	CaloriesBurnedSubscription(*Empty, grpc.ServerStreamingServer[CaloriesBurnedMetric]) error
	// gets a list of all of the CaloriesBurned changes for the given workout ID
	GetCaloriesBurnedHistory(context.Context, *WorkoutID) (*CaloriesBurnedMetricList, error)
	mustEmbedUnimplementedCaloriesBurnedServiceServer()
}

// UnimplementedCaloriesBurnedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaloriesBurnedServiceServer struct{}

func (UnimplementedCaloriesBurnedServiceServer) CanRead(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedCaloriesBurnedServiceServer) GetCaloriesBurned(context.Context, *Empty) (*CaloriesBurnedMetric, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCaloriesBurned not implemented")
}
func (UnimplementedCaloriesBurnedServiceServer) CaloriesBurnedSubscription(*Empty, grpc.ServerStreamingServer[CaloriesBurnedMetric]) error {
	return status.Error(codes.Unimplemented, "method CaloriesBurnedSubscription not implemented")
}
func (UnimplementedCaloriesBurnedServiceServer) GetCaloriesBurnedHistory(context.Context, *WorkoutID) (*CaloriesBurnedMetricList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCaloriesBurnedHistory not implemented")
}
func (UnimplementedCaloriesBurnedServiceServer) mustEmbedUnimplementedCaloriesBurnedServiceServer() {}
func (UnimplementedCaloriesBurnedServiceServer) testEmbeddedByValue()                               {}

// UnsafeCaloriesBurnedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaloriesBurnedServiceServer will
// result in compilation errors.
type UnsafeCaloriesBurnedServiceServer interface {
	mustEmbedUnimplementedCaloriesBurnedServiceServer()
}

func RegisterCaloriesBurnedServiceServer(s grpc.ServiceRegistrar, srv CaloriesBurnedServiceServer) {
	// If the following call panics, it indicates UnimplementedCaloriesBurnedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaloriesBurnedService_ServiceDesc, srv)
}

func _CaloriesBurnedService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaloriesBurnedServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaloriesBurnedService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaloriesBurnedServiceServer).CanRead(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaloriesBurnedService_GetCaloriesBurned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaloriesBurnedServiceServer).GetCaloriesBurned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaloriesBurnedService_GetCaloriesBurned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaloriesBurnedServiceServer).GetCaloriesBurned(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaloriesBurnedService_CaloriesBurnedSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaloriesBurnedServiceServer).CaloriesBurnedSubscription(m, &grpc.GenericServerStream[Empty, CaloriesBurnedMetric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaloriesBurnedService_CaloriesBurnedSubscriptionServer = grpc.ServerStreamingServer[CaloriesBurnedMetric]

func _CaloriesBurnedService_GetCaloriesBurnedHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaloriesBurnedServiceServer).GetCaloriesBurnedHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaloriesBurnedService_GetCaloriesBurnedHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaloriesBurnedServiceServer).GetCaloriesBurnedHistory(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

// CaloriesBurnedService_ServiceDesc is the grpc.ServiceDesc for CaloriesBurnedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaloriesBurnedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.CaloriesBurnedService",
	HandlerType: (*CaloriesBurnedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanRead",
			Handler:    _CaloriesBurnedService_CanRead_Handler,
		},
		{
			MethodName: "GetCaloriesBurned",
			Handler:    _CaloriesBurnedService_GetCaloriesBurned_Handler,
		},
		{
			MethodName: "GetCaloriesBurnedHistory",
			Handler:    _CaloriesBurnedService_GetCaloriesBurnedHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CaloriesBurnedSubscription",
			Handler:       _CaloriesBurnedService_CaloriesBurnedSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/CaloriesBurnedService.proto",
}
