// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/CaloriesBurnedService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaloriesBurnedMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutID     string                 `protobuf:"bytes,1,opt,name=workoutID,proto3" json:"workoutID,omitempty"`
	TimeSeconds   int32                  `protobuf:"varint,2,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	LastCalories  float64                `protobuf:"fixed64,3,opt,name=lastCalories,proto3" json:"lastCalories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaloriesBurnedMetric) Reset() {
	*x = CaloriesBurnedMetric{}
	mi := &file_workout_CaloriesBurnedService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaloriesBurnedMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaloriesBurnedMetric) ProtoMessage() {}

func (x *CaloriesBurnedMetric) ProtoReflect() protoreflect.Message {
	mi := &file_workout_CaloriesBurnedService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaloriesBurnedMetric.ProtoReflect.Descriptor instead.
func (*CaloriesBurnedMetric) Descriptor() ([]byte, []int) {
	return file_workout_CaloriesBurnedService_proto_rawDescGZIP(), []int{0}
}

func (x *CaloriesBurnedMetric) GetWorkoutID() string {
	if x != nil {
		return x.WorkoutID
	}
	return ""
}

func (x *CaloriesBurnedMetric) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *CaloriesBurnedMetric) GetLastCalories() float64 {
	if x != nil {
		return x.LastCalories
	}
	return 0
}

type CaloriesBurnedMetricList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metrics       []*CaloriesBurnedMetric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaloriesBurnedMetricList) Reset() {
	*x = CaloriesBurnedMetricList{}
	mi := &file_workout_CaloriesBurnedService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaloriesBurnedMetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaloriesBurnedMetricList) ProtoMessage() {}

func (x *CaloriesBurnedMetricList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_CaloriesBurnedService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaloriesBurnedMetricList.ProtoReflect.Descriptor instead.
func (*CaloriesBurnedMetricList) Descriptor() ([]byte, []int) {
	return file_workout_CaloriesBurnedService_proto_rawDescGZIP(), []int{1}
}

func (x *CaloriesBurnedMetricList) GetMetrics() []*CaloriesBurnedMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_workout_CaloriesBurnedService_proto protoreflect.FileDescriptor

const file_workout_CaloriesBurnedService_proto_rawDesc = "" +
	"\n" +
	"#workout/CaloriesBurnedService.proto\x12\x10com.ifit.glassos\x1a\x0futil/Util.proto\"z\n" +
	"\x14CaloriesBurnedMetric\x12\x1c\n" +
	"\tworkoutID\x18\x01 \x01(\tR\tworkoutID\x12 \n" +
	"\vtimeSeconds\x18\x02 \x01(\x05R\vtimeSeconds\x12\"\n" +
	"\flastCalories\x18\x03 \x01(\x01R\flastCalories\"\\\n" +
	"\x18CaloriesBurnedMetricList\x12@\n" +
	"\ametrics\x18\x01 \x03(\v2&.com.ifit.glassos.CaloriesBurnedMetricR\ametrics2\x87\x03\n" +
	"\x15CaloriesBurnedService\x12L\n" +
	"\aCanRead\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12V\n" +
	"\x11GetCaloriesBurned\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.CaloriesBurnedMetric\"\x00\x12a\n" +
	"\x1aCaloriesBurnedSubscription\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.CaloriesBurnedMetric\"\x000\x01\x12e\n" +
	"\x18GetCaloriesBurnedHistory\x12\x1b.com.ifit.glassos.WorkoutID\x1a*.com.ifit.glassos.CaloriesBurnedMetricList\"\x00B?\n" +
	"\x18com.ifit.glassos.workoutB\x1aCaloriesBurnedServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_CaloriesBurnedService_proto_rawDescOnce sync.Once
	file_workout_CaloriesBurnedService_proto_rawDescData []byte
)

func file_workout_CaloriesBurnedService_proto_rawDescGZIP() []byte {
	file_workout_CaloriesBurnedService_proto_rawDescOnce.Do(func() {
		file_workout_CaloriesBurnedService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_CaloriesBurnedService_proto_rawDesc), len(file_workout_CaloriesBurnedService_proto_rawDesc)))
	})
	return file_workout_CaloriesBurnedService_proto_rawDescData
}

var file_workout_CaloriesBurnedService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workout_CaloriesBurnedService_proto_goTypes = []any{
	(*CaloriesBurnedMetric)(nil),     // 0: com.ifit.glassos.CaloriesBurnedMetric
	(*CaloriesBurnedMetricList)(nil), // 1: com.ifit.glassos.CaloriesBurnedMetricList
	(*Empty)(nil),                    // 2: com.ifit.glassos.Empty
	(*WorkoutID)(nil),                // 3: com.ifit.glassos.WorkoutID
	(*AvailabilityResponse)(nil),     // 4: com.ifit.glassos.AvailabilityResponse
}
var file_workout_CaloriesBurnedService_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.CaloriesBurnedMetricList.metrics:type_name -> com.ifit.glassos.CaloriesBurnedMetric
	2, // 1: com.ifit.glassos.CaloriesBurnedService.CanRead:input_type -> com.ifit.glassos.Empty
	2, // 2: com.ifit.glassos.CaloriesBurnedService.GetCaloriesBurned:input_type -> com.ifit.glassos.Empty
	2, // 3: com.ifit.glassos.CaloriesBurnedService.CaloriesBurnedSubscription:input_type -> com.ifit.glassos.Empty
	3, // 4: com.ifit.glassos.CaloriesBurnedService.GetCaloriesBurnedHistory:input_type -> com.ifit.glassos.WorkoutID
	4, // 5: com.ifit.glassos.CaloriesBurnedService.CanRead:output_type -> com.ifit.glassos.AvailabilityResponse
	0, // 6: com.ifit.glassos.CaloriesBurnedService.GetCaloriesBurned:output_type -> com.ifit.glassos.CaloriesBurnedMetric
	0, // 7: com.ifit.glassos.CaloriesBurnedService.CaloriesBurnedSubscription:output_type -> com.ifit.glassos.CaloriesBurnedMetric
	1, // 8: com.ifit.glassos.CaloriesBurnedService.GetCaloriesBurnedHistory:output_type -> com.ifit.glassos.CaloriesBurnedMetricList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workout_CaloriesBurnedService_proto_init() }
func file_workout_CaloriesBurnedService_proto_init() {
	if File_workout_CaloriesBurnedService_proto != nil {
		return
	}
	file_util_Util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_CaloriesBurnedService_proto_rawDesc), len(file_workout_CaloriesBurnedService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_CaloriesBurnedService_proto_goTypes,
		DependencyIndexes: file_workout_CaloriesBurnedService_proto_depIdxs,
		MessageInfos:      file_workout_CaloriesBurnedService_proto_msgTypes,
	}.Build()
	File_workout_CaloriesBurnedService_proto = out.File
	file_workout_CaloriesBurnedService_proto_goTypes = nil
	file_workout_CaloriesBurnedService_proto_depIdxs = nil
}
