// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: util/ConnectionError.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionErrorCode int32

const (
	ConnectionErrorCode_CONNECTION_FAILURE ConnectionErrorCode = 0
)

// Enum value maps for ConnectionErrorCode.
var (
	ConnectionErrorCode_name = map[int32]string{
		0: "CONNECTION_FAILURE",
	}
	ConnectionErrorCode_value = map[string]int32{
		"CONNECTION_FAILURE": 0,
	}
)

func (x ConnectionErrorCode) Enum() *ConnectionErrorCode {
	p := new(ConnectionErrorCode)
	*p = x
	return p
}

func (x ConnectionErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_util_ConnectionError_proto_enumTypes[0].Descriptor()
}

func (ConnectionErrorCode) Type() protoreflect.EnumType {
	return &file_util_ConnectionError_proto_enumTypes[0]
}

func (x ConnectionErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionErrorCode.Descriptor instead.
func (ConnectionErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_util_ConnectionError_proto_rawDescGZIP(), []int{0}
}

type ConnectionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ConnectionErrorCode    `protobuf:"varint,1,opt,name=errorCode,proto3,enum=com.ifit.glassos.ConnectionErrorCode" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionError) Reset() {
	*x = ConnectionError{}
	mi := &file_util_ConnectionError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionError) ProtoMessage() {}

func (x *ConnectionError) ProtoReflect() protoreflect.Message {
	mi := &file_util_ConnectionError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionError.ProtoReflect.Descriptor instead.
func (*ConnectionError) Descriptor() ([]byte, []int) {
	return file_util_ConnectionError_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionError) GetErrorCode() ConnectionErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ConnectionErrorCode_CONNECTION_FAILURE
}

func (x *ConnectionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_util_ConnectionError_proto protoreflect.FileDescriptor

const file_util_ConnectionError_proto_rawDesc = "" +
	"\n" +
	"\x1autil/ConnectionError.proto\x12\x10com.ifit.glassos\"p\n" +
	"\x0fConnectionError\x12C\n" +
	"\terrorCode\x18\x01 \x01(\x0e2%.com.ifit.glassos.ConnectionErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*-\n" +
	"\x13ConnectionErrorCode\x12\x16\n" +
	"\x12CONNECTION_FAILURE\x10\x00B:\n" +
	"\x15com.ifit.glassos.utilB\x18ConnectionErrorCodeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_util_ConnectionError_proto_rawDescOnce sync.Once
	file_util_ConnectionError_proto_rawDescData []byte
)

func file_util_ConnectionError_proto_rawDescGZIP() []byte {
	file_util_ConnectionError_proto_rawDescOnce.Do(func() {
		file_util_ConnectionError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_ConnectionError_proto_rawDesc), len(file_util_ConnectionError_proto_rawDesc)))
	})
	return file_util_ConnectionError_proto_rawDescData
}

var file_util_ConnectionError_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_util_ConnectionError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_ConnectionError_proto_goTypes = []any{
	(ConnectionErrorCode)(0), // 0: com.ifit.glassos.ConnectionErrorCode
	(*ConnectionError)(nil),  // 1: com.ifit.glassos.ConnectionError
}
var file_util_ConnectionError_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.ConnectionError.errorCode:type_name -> com.ifit.glassos.ConnectionErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_util_ConnectionError_proto_init() }
func file_util_ConnectionError_proto_init() {
	if File_util_ConnectionError_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_ConnectionError_proto_rawDesc), len(file_util_ConnectionError_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_ConnectionError_proto_goTypes,
		DependencyIndexes: file_util_ConnectionError_proto_depIdxs,
		EnumInfos:         file_util_ConnectionError_proto_enumTypes,
		MessageInfos:      file_util_ConnectionError_proto_msgTypes,
	}.Build()
	File_util_ConnectionError_proto = out.File
	file_util_ConnectionError_proto_goTypes = nil
	file_util_ConnectionError_proto_depIdxs = nil
}
