// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: console/ConsoleService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleService_Connect_FullMethodName                 = "/com.ifit.glassos.ConsoleService/Connect"
	ConsoleService_Disconnect_FullMethodName              = "/com.ifit.glassos.ConsoleService/Disconnect"
	ConsoleService_GetConsole_FullMethodName              = "/com.ifit.glassos.ConsoleService/GetConsole"
	ConsoleService_ConsoleChanged_FullMethodName          = "/com.ifit.glassos.ConsoleService/ConsoleChanged"
	ConsoleService_GetConsoleState_FullMethodName         = "/com.ifit.glassos.ConsoleService/GetConsoleState"
	ConsoleService_ConsoleStateChanged_FullMethodName     = "/com.ifit.glassos.ConsoleService/ConsoleStateChanged"
	ConsoleService_GetKnownConsoleInfo_FullMethodName     = "/com.ifit.glassos.ConsoleService/GetKnownConsoleInfo"
	ConsoleService_RefreshKnownConsoleInfo_FullMethodName = "/com.ifit.glassos.ConsoleService/RefreshKnownConsoleInfo"
)

// ConsoleServiceClient is the client API for ConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsoleServiceClient interface {
	Connect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConnectionResult, error)
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetConsole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleInfo, error)
	ConsoleChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleInfo], error)
	GetConsoleState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleStateMessage, error)
	ConsoleStateChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleStateMessage], error)
	GetKnownConsoleInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleInfo, error)
	RefreshKnownConsoleInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleInfo, error)
}

type consoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleServiceClient(cc grpc.ClientConnInterface) ConsoleServiceClient {
	return &consoleServiceClient{cc}
}

func (c *consoleServiceClient) Connect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConnectionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionResult)
	err := c.cc.Invoke(ctx, ConsoleService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ConsoleService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) GetConsole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleInfo)
	err := c.cc.Invoke(ctx, ConsoleService_GetConsole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) ConsoleChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsoleService_ServiceDesc.Streams[0], ConsoleService_ConsoleChanged_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ConsoleInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_ConsoleChangedClient = grpc.ServerStreamingClient[ConsoleInfo]

func (c *consoleServiceClient) GetConsoleState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleStateMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleStateMessage)
	err := c.cc.Invoke(ctx, ConsoleService_GetConsoleState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) ConsoleStateChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleStateMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsoleService_ServiceDesc.Streams[1], ConsoleService_ConsoleStateChanged_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ConsoleStateMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_ConsoleStateChangedClient = grpc.ServerStreamingClient[ConsoleStateMessage]

func (c *consoleServiceClient) GetKnownConsoleInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleInfo)
	err := c.cc.Invoke(ctx, ConsoleService_GetKnownConsoleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleServiceClient) RefreshKnownConsoleInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConsoleInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleInfo)
	err := c.cc.Invoke(ctx, ConsoleService_RefreshKnownConsoleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleServiceServer is the server API for ConsoleService service.
// All implementations must embed UnimplementedConsoleServiceServer
// for forward compatibility.
type ConsoleServiceServer interface {
	Connect(context.Context, *Empty) (*ConnectionResult, error)
	Disconnect(context.Context, *Empty) (*Empty, error)
	GetConsole(context.Context, *Empty) (*ConsoleInfo, error)
	ConsoleChanged(*Empty, grpc.ServerStreamingServer[ConsoleInfo]) error
	GetConsoleState(context.Context, *Empty) (*ConsoleStateMessage, error)
	ConsoleStateChanged(*Empty, grpc.ServerStreamingServer[ConsoleStateMessage]) error
	GetKnownConsoleInfo(context.Context, *Empty) (*ConsoleInfo, error)
	RefreshKnownConsoleInfo(context.Context, *Empty) (*ConsoleInfo, error)
	mustEmbedUnimplementedConsoleServiceServer()
}

// UnimplementedConsoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleServiceServer struct{}

func (UnimplementedConsoleServiceServer) Connect(context.Context, *Empty) (*ConnectionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConsoleServiceServer) Disconnect(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedConsoleServiceServer) GetConsole(context.Context, *Empty) (*ConsoleInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsole not implemented")
}
func (UnimplementedConsoleServiceServer) ConsoleChanged(*Empty, grpc.ServerStreamingServer[ConsoleInfo]) error {
	return status.Error(codes.Unimplemented, "method ConsoleChanged not implemented")
}
func (UnimplementedConsoleServiceServer) GetConsoleState(context.Context, *Empty) (*ConsoleStateMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsoleState not implemented")
}
func (UnimplementedConsoleServiceServer) ConsoleStateChanged(*Empty, grpc.ServerStreamingServer[ConsoleStateMessage]) error {
	return status.Error(codes.Unimplemented, "method ConsoleStateChanged not implemented")
}
func (UnimplementedConsoleServiceServer) GetKnownConsoleInfo(context.Context, *Empty) (*ConsoleInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnownConsoleInfo not implemented")
}
func (UnimplementedConsoleServiceServer) RefreshKnownConsoleInfo(context.Context, *Empty) (*ConsoleInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshKnownConsoleInfo not implemented")
}
func (UnimplementedConsoleServiceServer) mustEmbedUnimplementedConsoleServiceServer() {}
func (UnimplementedConsoleServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServiceServer will
// result in compilation errors.
type UnsafeConsoleServiceServer interface {
	mustEmbedUnimplementedConsoleServiceServer()
}

func RegisterConsoleServiceServer(s grpc.ServiceRegistrar, srv ConsoleServiceServer) {
	// If the following call panics, it indicates UnimplementedConsoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleService_ServiceDesc, srv)
}

func _ConsoleService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Connect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_GetConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetConsole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetConsole(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_ConsoleChanged_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsoleServiceServer).ConsoleChanged(m, &grpc.GenericServerStream[Empty, ConsoleInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_ConsoleChangedServer = grpc.ServerStreamingServer[ConsoleInfo]

func _ConsoleService_GetConsoleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetConsoleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetConsoleState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetConsoleState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_ConsoleStateChanged_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsoleServiceServer).ConsoleStateChanged(m, &grpc.GenericServerStream[Empty, ConsoleStateMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsoleService_ConsoleStateChangedServer = grpc.ServerStreamingServer[ConsoleStateMessage]

func _ConsoleService_GetKnownConsoleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).GetKnownConsoleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_GetKnownConsoleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).GetKnownConsoleInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleService_RefreshKnownConsoleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServiceServer).RefreshKnownConsoleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleService_RefreshKnownConsoleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServiceServer).RefreshKnownConsoleInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleService_ServiceDesc is the grpc.ServiceDesc for ConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.ConsoleService",
	HandlerType: (*ConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _ConsoleService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _ConsoleService_Disconnect_Handler,
		},
		{
			MethodName: "GetConsole",
			Handler:    _ConsoleService_GetConsole_Handler,
		},
		{
			MethodName: "GetConsoleState",
			Handler:    _ConsoleService_GetConsoleState_Handler,
		},
		{
			MethodName: "GetKnownConsoleInfo",
			Handler:    _ConsoleService_GetKnownConsoleInfo_Handler,
		},
		{
			MethodName: "RefreshKnownConsoleInfo",
			Handler:    _ConsoleService_RefreshKnownConsoleInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConsoleChanged",
			Handler:       _ConsoleService_ConsoleChanged_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConsoleStateChanged",
			Handler:       _ConsoleService_ConsoleStateChanged_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "console/ConsoleService.proto",
}
