// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: console/ConsoleState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleState int32

const (
	ConsoleState_DISCONNECTED          ConsoleState = 0
	ConsoleState_CONSOLE_STATE_UNKNOWN ConsoleState = 1
	ConsoleState_IDLE                  ConsoleState = 2
	ConsoleState_WORKOUT               ConsoleState = 3
	ConsoleState_PAUSED                ConsoleState = 4
	ConsoleState_WORKOUT_RESULTS       ConsoleState = 5
	ConsoleState_SAFETY_KEY_REMOVED    ConsoleState = 6
	ConsoleState_WARM_UP               ConsoleState = 7
	ConsoleState_COOL_DOWN             ConsoleState = 8
	ConsoleState_RESUME                ConsoleState = 9
	ConsoleState_LOCKED                ConsoleState = 10
	ConsoleState_DEMO                  ConsoleState = 11
	ConsoleState_SLEEP                 ConsoleState = 12
	ConsoleState_ERROR                 ConsoleState = 13
)

// Enum value maps for ConsoleState.
var (
	ConsoleState_name = map[int32]string{
		0:  "DISCONNECTED",
		1:  "CONSOLE_STATE_UNKNOWN",
		2:  "IDLE",
		3:  "WORKOUT",
		4:  "PAUSED",
		5:  "WORKOUT_RESULTS",
		6:  "SAFETY_KEY_REMOVED",
		7:  "WARM_UP",
		8:  "COOL_DOWN",
		9:  "RESUME",
		10: "LOCKED",
		11: "DEMO",
		12: "SLEEP",
		13: "ERROR",
	}
	ConsoleState_value = map[string]int32{
		"DISCONNECTED":          0,
		"CONSOLE_STATE_UNKNOWN": 1,
		"IDLE":                  2,
		"WORKOUT":               3,
		"PAUSED":                4,
		"WORKOUT_RESULTS":       5,
		"SAFETY_KEY_REMOVED":    6,
		"WARM_UP":               7,
		"COOL_DOWN":             8,
		"RESUME":                9,
		"LOCKED":                10,
		"DEMO":                  11,
		"SLEEP":                 12,
		"ERROR":                 13,
	}
)

func (x ConsoleState) Enum() *ConsoleState {
	p := new(ConsoleState)
	*p = x
	return p
}

func (x ConsoleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleState) Descriptor() protoreflect.EnumDescriptor {
	return file_console_ConsoleState_proto_enumTypes[0].Descriptor()
}

func (ConsoleState) Type() protoreflect.EnumType {
	return &file_console_ConsoleState_proto_enumTypes[0]
}

func (x ConsoleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleState.Descriptor instead.
func (ConsoleState) EnumDescriptor() ([]byte, []int) {
	return file_console_ConsoleState_proto_rawDescGZIP(), []int{0}
}

var File_console_ConsoleState_proto protoreflect.FileDescriptor

const file_console_ConsoleState_proto_rawDesc = "" +
	"\n" +
	"\x1aconsole/ConsoleState.proto\x12\x10com.ifit.glassos*\xdf\x01\n" +
	"\fConsoleState\x12\x10\n" +
	"\fDISCONNECTED\x10\x00\x12\x19\n" +
	"\x15CONSOLE_STATE_UNKNOWN\x10\x01\x12\b\n" +
	"\x04IDLE\x10\x02\x12\v\n" +
	"\aWORKOUT\x10\x03\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x04\x12\x13\n" +
	"\x0fWORKOUT_RESULTS\x10\x05\x12\x16\n" +
	"\x12SAFETY_KEY_REMOVED\x10\x06\x12\v\n" +
	"\aWARM_UP\x10\a\x12\r\n" +
	"\tCOOL_DOWN\x10\b\x12\n" +
	"\n" +
	"\x06RESUME\x10\t\x12\n" +
	"\n" +
	"\x06LOCKED\x10\n" +
	"\x12\b\n" +
	"\x04DEMO\x10\v\x12\t\n" +
	"\x05SLEEP\x10\f\x12\t\n" +
	"\x05ERROR\x10\rB6\n" +
	"\x18com.ifit.glassos.consoleB\x11ConsoleStateProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_console_ConsoleState_proto_rawDescOnce sync.Once
	file_console_ConsoleState_proto_rawDescData []byte
)

func file_console_ConsoleState_proto_rawDescGZIP() []byte {
	file_console_ConsoleState_proto_rawDescOnce.Do(func() {
		file_console_ConsoleState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_ConsoleState_proto_rawDesc), len(file_console_ConsoleState_proto_rawDesc)))
	})
	return file_console_ConsoleState_proto_rawDescData
}

var file_console_ConsoleState_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_ConsoleState_proto_goTypes = []any{
	(ConsoleState)(0), // 0: com.ifit.glassos.ConsoleState
}
var file_console_ConsoleState_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_console_ConsoleState_proto_init() }
func file_console_ConsoleState_proto_init() {
	if File_console_ConsoleState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_ConsoleState_proto_rawDesc), len(file_console_ConsoleState_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_console_ConsoleState_proto_goTypes,
		DependencyIndexes: file_console_ConsoleState_proto_depIdxs,
		EnumInfos:         file_console_ConsoleState_proto_enumTypes,
	}.Build()
	File_console_ConsoleState_proto = out.File
	file_console_ConsoleState_proto_goTypes = nil
	file_console_ConsoleState_proto_depIdxs = nil
}
