// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: console/ConsoleType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleType int32

const (
	ConsoleType_CONSOLE_TYPE_UNKNOWN ConsoleType = 0
	ConsoleType_TREADMILL            ConsoleType = 1
	ConsoleType_INCLINE_TRAINER      ConsoleType = 2
	ConsoleType_ELLIPTICAL           ConsoleType = 3
	ConsoleType_BIKE                 ConsoleType = 4
	ConsoleType_STRIDER              ConsoleType = 5
	ConsoleType_FREE_STRIDER         ConsoleType = 6
	ConsoleType_VERTICAL_ELLIPTICAL  ConsoleType = 7
	ConsoleType_SPIN_BIKE            ConsoleType = 8
	ConsoleType_ROWER                ConsoleType = 9
	ConsoleType_EQUIPMENTLESS        ConsoleType = 10
	ConsoleType_MIRROR               ConsoleType = 11
	ConsoleType_VIBRATION            ConsoleType = 12
)

// Enum value maps for ConsoleType.
var (
	ConsoleType_name = map[int32]string{
		0:  "CONSOLE_TYPE_UNKNOWN",
		1:  "TREADMILL",
		2:  "INCLINE_TRAINER",
		3:  "ELLIPTICAL",
		4:  "BIKE",
		5:  "STRIDER",
		6:  "FREE_STRIDER",
		7:  "VERTICAL_ELLIPTICAL",
		8:  "SPIN_BIKE",
		9:  "ROWER",
		10: "EQUIPMENTLESS",
		11: "MIRROR",
		12: "VIBRATION",
	}
	ConsoleType_value = map[string]int32{
		"CONSOLE_TYPE_UNKNOWN": 0,
		"TREADMILL":            1,
		"INCLINE_TRAINER":      2,
		"ELLIPTICAL":           3,
		"BIKE":                 4,
		"STRIDER":              5,
		"FREE_STRIDER":         6,
		"VERTICAL_ELLIPTICAL":  7,
		"SPIN_BIKE":            8,
		"ROWER":                9,
		"EQUIPMENTLESS":        10,
		"MIRROR":               11,
		"VIBRATION":            12,
	}
)

func (x ConsoleType) Enum() *ConsoleType {
	p := new(ConsoleType)
	*p = x
	return p
}

func (x ConsoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_console_ConsoleType_proto_enumTypes[0].Descriptor()
}

func (ConsoleType) Type() protoreflect.EnumType {
	return &file_console_ConsoleType_proto_enumTypes[0]
}

func (x ConsoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleType.Descriptor instead.
func (ConsoleType) EnumDescriptor() ([]byte, []int) {
	return file_console_ConsoleType_proto_rawDescGZIP(), []int{0}
}

var File_console_ConsoleType_proto protoreflect.FileDescriptor

const file_console_ConsoleType_proto_rawDesc = "" +
	"\n" +
	"\x19console/ConsoleType.proto\x12\x10com.ifit.glassos*\xe5\x01\n" +
	"\vConsoleType\x12\x18\n" +
	"\x14CONSOLE_TYPE_UNKNOWN\x10\x00\x12\r\n" +
	"\tTREADMILL\x10\x01\x12\x13\n" +
	"\x0fINCLINE_TRAINER\x10\x02\x12\x0e\n" +
	"\n" +
	"ELLIPTICAL\x10\x03\x12\b\n" +
	"\x04BIKE\x10\x04\x12\v\n" +
	"\aSTRIDER\x10\x05\x12\x10\n" +
	"\fFREE_STRIDER\x10\x06\x12\x17\n" +
	"\x13VERTICAL_ELLIPTICAL\x10\a\x12\r\n" +
	"\tSPIN_BIKE\x10\b\x12\t\n" +
	"\x05ROWER\x10\t\x12\x11\n" +
	"\rEQUIPMENTLESS\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06MIRROR\x10\v\x12\r\n" +
	"\tVIBRATION\x10\fB5\n" +
	"\x18com.ifit.glassos.consoleB\x10ConsoleTypeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_console_ConsoleType_proto_rawDescOnce sync.Once
	file_console_ConsoleType_proto_rawDescData []byte
)

func file_console_ConsoleType_proto_rawDescGZIP() []byte {
	file_console_ConsoleType_proto_rawDescOnce.Do(func() {
		file_console_ConsoleType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_ConsoleType_proto_rawDesc), len(file_console_ConsoleType_proto_rawDesc)))
	})
	return file_console_ConsoleType_proto_rawDescData
}

var file_console_ConsoleType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_ConsoleType_proto_goTypes = []any{
	(ConsoleType)(0), // 0: com.ifit.glassos.ConsoleType
}
var file_console_ConsoleType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_console_ConsoleType_proto_init() }
func file_console_ConsoleType_proto_init() {
	if File_console_ConsoleType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_ConsoleType_proto_rawDesc), len(file_console_ConsoleType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_console_ConsoleType_proto_goTypes,
		DependencyIndexes: file_console_ConsoleType_proto_depIdxs,
		EnumInfos:         file_console_ConsoleType_proto_enumTypes,
	}.Build()
	File_console_ConsoleType_proto = out.File
	file_console_ConsoleType_proto_goTypes = nil
	file_console_ConsoleType_proto_depIdxs = nil
}
