// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: console/ConsoleInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleInfo struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ModelNumber                    int32                  `protobuf:"varint,1,opt,name=modelNumber,proto3" json:"modelNumber,omitempty"`
	PartNumber                     int32                  `protobuf:"varint,2,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	SoftwareVersion                int32                  `protobuf:"varint,3,opt,name=softwareVersion,proto3" json:"softwareVersion,omitempty"`
	HardwareVersion                int32                  `protobuf:"varint,4,opt,name=hardwareVersion,proto3" json:"hardwareVersion,omitempty"`
	FirmwareVersion                string                 `protobuf:"bytes,5,opt,name=firmwareVersion,proto3" json:"firmwareVersion,omitempty"`
	SerialNumber                   int32                  `protobuf:"varint,6,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	MachineType                    ConsoleType            `protobuf:"varint,7,opt,name=machineType,proto3,enum=com.ifit.glassos.ConsoleType" json:"machineType,omitempty"`
	Name                           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	BrainboardSerialNumber         string                 `protobuf:"bytes,9,opt,name=brainboardSerialNumber,proto3" json:"brainboardSerialNumber,omitempty"`
	MasterLibraryVersion           int32                  `protobuf:"varint,10,opt,name=masterLibraryVersion,proto3" json:"masterLibraryVersion,omitempty"`
	MasterLibraryBuild             int32                  `protobuf:"varint,11,opt,name=masterLibraryBuild,proto3" json:"masterLibraryBuild,omitempty"`
	SystemUnits                    SystemUnits            `protobuf:"varint,12,opt,name=systemUnits,proto3,enum=com.ifit.glassos.SystemUnits" json:"systemUnits,omitempty"`
	MaxKph                         float64                `protobuf:"fixed64,13,opt,name=maxKph,proto3" json:"maxKph,omitempty"`
	MinKph                         float64                `protobuf:"fixed64,14,opt,name=minKph,proto3" json:"minKph,omitempty"`
	MaxInclinePercent              float64                `protobuf:"fixed64,15,opt,name=maxInclinePercent,proto3" json:"maxInclinePercent,omitempty"`
	MinInclinePercent              float64                `protobuf:"fixed64,16,opt,name=minInclinePercent,proto3" json:"minInclinePercent,omitempty"`
	MinResistance                  float64                `protobuf:"fixed64,17,opt,name=minResistance,proto3" json:"minResistance,omitempty"`
	MaxResistance                  float64                `protobuf:"fixed64,18,opt,name=maxResistance,proto3" json:"maxResistance,omitempty"`
	MinGear                        int32                  `protobuf:"varint,19,opt,name=minGear,proto3" json:"minGear,omitempty"`
	MaxGear                        int32                  `protobuf:"varint,20,opt,name=maxGear,proto3" json:"maxGear,omitempty"`
	MaxWeightKg                    float64                `protobuf:"fixed64,21,opt,name=maxWeightKg,proto3" json:"maxWeightKg,omitempty"`
	CanSetSpeed                    bool                   `protobuf:"varint,22,opt,name=canSetSpeed,proto3" json:"canSetSpeed,omitempty"`
	CanSetIncline                  bool                   `protobuf:"varint,23,opt,name=canSetIncline,proto3" json:"canSetIncline,omitempty"`
	CanSetResistance               bool                   `protobuf:"varint,24,opt,name=canSetResistance,proto3" json:"canSetResistance,omitempty"`
	CanSetGear                     bool                   `protobuf:"varint,25,opt,name=canSetGear,proto3" json:"canSetGear,omitempty"`
	CanSetActivationLock           bool                   `protobuf:"varint,26,opt,name=canSetActivationLock,proto3" json:"canSetActivationLock,omitempty"`
	SupportsVerticalGain           bool                   `protobuf:"varint,27,opt,name=supportsVerticalGain,proto3" json:"supportsVerticalGain,omitempty"`
	SupportsVerticalNet            bool                   `protobuf:"varint,28,opt,name=supportsVerticalNet,proto3" json:"supportsVerticalNet,omitempty"`
	SupportsStartRequested         bool                   `protobuf:"varint,29,opt,name=supportsStartRequested,proto3" json:"supportsStartRequested,omitempty"`
	SupportsRequireStartRequested  bool                   `protobuf:"varint,30,opt,name=supportsRequireStartRequested,proto3" json:"supportsRequireStartRequested,omitempty"`
	SupportsKeyPressObserved       bool                   `protobuf:"varint,31,opt,name=supportsKeyPressObserved,proto3" json:"supportsKeyPressObserved,omitempty"`
	SupportsPulse                  bool                   `protobuf:"varint,32,opt,name=supportsPulse,proto3" json:"supportsPulse,omitempty"`
	TotalTimeSeconds               float64                `protobuf:"fixed64,33,opt,name=totalTimeSeconds,proto3" json:"totalTimeSeconds,omitempty"`
	WarmUpTimeoutSeconds           float64                `protobuf:"fixed64,34,opt,name=warmUpTimeoutSeconds,proto3" json:"warmUpTimeoutSeconds,omitempty"`
	CoolDownTimeoutSeconds         float64                `protobuf:"fixed64,35,opt,name=coolDownTimeoutSeconds,proto3" json:"coolDownTimeoutSeconds,omitempty"`
	PauseTimeoutSeconds            float64                `protobuf:"fixed64,36,opt,name=pauseTimeoutSeconds,proto3" json:"pauseTimeoutSeconds,omitempty"`
	TotalDistanceKm                float64                `protobuf:"fixed64,37,opt,name=totalDistanceKm,proto3" json:"totalDistanceKm,omitempty"`
	IsClubUnit                     bool                   `protobuf:"varint,38,opt,name=isClubUnit,proto3" json:"isClubUnit,omitempty"`
	WeightKg                       float64                `protobuf:"fixed64,39,opt,name=weightKg,proto3" json:"weightKg,omitempty"`
	SupportsConstantWatts          bool                   `protobuf:"varint,40,opt,name=supportsConstantWatts,proto3" json:"supportsConstantWatts,omitempty"`
	AntPlusBootloaderVersion       string                 `protobuf:"bytes,41,opt,name=antPlusBootloaderVersion,proto3" json:"antPlusBootloaderVersion,omitempty"`
	AntPlusSerialNumber            string                 `protobuf:"bytes,42,opt,name=antPlusSerialNumber,proto3" json:"antPlusSerialNumber,omitempty"`
	AntPlusDeviceNumber            string                 `protobuf:"bytes,43,opt,name=antPlusDeviceNumber,proto3" json:"antPlusDeviceNumber,omitempty"`
	AntPlusRelaySoftwareVersion    string                 `protobuf:"bytes,44,opt,name=antPlusRelaySoftwareVersion,proto3" json:"antPlusRelaySoftwareVersion,omitempty"`
	ProductSerialNumber            string                 `protobuf:"bytes,45,opt,name=productSerialNumber,proto3" json:"productSerialNumber,omitempty"`
	Controller1SoftwareVersion     string                 `protobuf:"bytes,46,opt,name=controller1SoftwareVersion,proto3" json:"controller1SoftwareVersion,omitempty"`
	Controller1SoftwarePartNumber  string                 `protobuf:"bytes,47,opt,name=controller1SoftwarePartNumber,proto3" json:"controller1SoftwarePartNumber,omitempty"`
	Controller4SoftwareVersion     string                 `protobuf:"bytes,48,opt,name=controller4SoftwareVersion,proto3" json:"controller4SoftwareVersion,omitempty"`
	Controller4SoftwarePartNumber  string                 `protobuf:"bytes,49,opt,name=controller4SoftwarePartNumber,proto3" json:"controller4SoftwarePartNumber,omitempty"`
	Controller40SoftwareVersion    string                 `protobuf:"bytes,50,opt,name=controller40SoftwareVersion,proto3" json:"controller40SoftwareVersion,omitempty"`
	Controller40SoftwarePartNumber string                 `protobuf:"bytes,51,opt,name=controller40SoftwarePartNumber,proto3" json:"controller40SoftwarePartNumber,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ConsoleInfo) Reset() {
	*x = ConsoleInfo{}
	mi := &file_console_ConsoleInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInfo) ProtoMessage() {}

func (x *ConsoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_console_ConsoleInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInfo.ProtoReflect.Descriptor instead.
func (*ConsoleInfo) Descriptor() ([]byte, []int) {
	return file_console_ConsoleInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ConsoleInfo) GetModelNumber() int32 {
	if x != nil {
		return x.ModelNumber
	}
	return 0
}

func (x *ConsoleInfo) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *ConsoleInfo) GetSoftwareVersion() int32 {
	if x != nil {
		return x.SoftwareVersion
	}
	return 0
}

func (x *ConsoleInfo) GetHardwareVersion() int32 {
	if x != nil {
		return x.HardwareVersion
	}
	return 0
}

func (x *ConsoleInfo) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *ConsoleInfo) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *ConsoleInfo) GetMachineType() ConsoleType {
	if x != nil {
		return x.MachineType
	}
	return ConsoleType_CONSOLE_TYPE_UNKNOWN
}

func (x *ConsoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsoleInfo) GetBrainboardSerialNumber() string {
	if x != nil {
		return x.BrainboardSerialNumber
	}
	return ""
}

func (x *ConsoleInfo) GetMasterLibraryVersion() int32 {
	if x != nil {
		return x.MasterLibraryVersion
	}
	return 0
}

func (x *ConsoleInfo) GetMasterLibraryBuild() int32 {
	if x != nil {
		return x.MasterLibraryBuild
	}
	return 0
}

func (x *ConsoleInfo) GetSystemUnits() SystemUnits {
	if x != nil {
		return x.SystemUnits
	}
	return SystemUnits_SYSTEM_UNITS_UNKNOWN
}

func (x *ConsoleInfo) GetMaxKph() float64 {
	if x != nil {
		return x.MaxKph
	}
	return 0
}

func (x *ConsoleInfo) GetMinKph() float64 {
	if x != nil {
		return x.MinKph
	}
	return 0
}

func (x *ConsoleInfo) GetMaxInclinePercent() float64 {
	if x != nil {
		return x.MaxInclinePercent
	}
	return 0
}

func (x *ConsoleInfo) GetMinInclinePercent() float64 {
	if x != nil {
		return x.MinInclinePercent
	}
	return 0
}

func (x *ConsoleInfo) GetMinResistance() float64 {
	if x != nil {
		return x.MinResistance
	}
	return 0
}

func (x *ConsoleInfo) GetMaxResistance() float64 {
	if x != nil {
		return x.MaxResistance
	}
	return 0
}

func (x *ConsoleInfo) GetMinGear() int32 {
	if x != nil {
		return x.MinGear
	}
	return 0
}

func (x *ConsoleInfo) GetMaxGear() int32 {
	if x != nil {
		return x.MaxGear
	}
	return 0
}

func (x *ConsoleInfo) GetMaxWeightKg() float64 {
	if x != nil {
		return x.MaxWeightKg
	}
	return 0
}

func (x *ConsoleInfo) GetCanSetSpeed() bool {
	if x != nil {
		return x.CanSetSpeed
	}
	return false
}

func (x *ConsoleInfo) GetCanSetIncline() bool {
	if x != nil {
		return x.CanSetIncline
	}
	return false
}

func (x *ConsoleInfo) GetCanSetResistance() bool {
	if x != nil {
		return x.CanSetResistance
	}
	return false
}

func (x *ConsoleInfo) GetCanSetGear() bool {
	if x != nil {
		return x.CanSetGear
	}
	return false
}

func (x *ConsoleInfo) GetCanSetActivationLock() bool {
	if x != nil {
		return x.CanSetActivationLock
	}
	return false
}

func (x *ConsoleInfo) GetSupportsVerticalGain() bool {
	if x != nil {
		return x.SupportsVerticalGain
	}
	return false
}

func (x *ConsoleInfo) GetSupportsVerticalNet() bool {
	if x != nil {
		return x.SupportsVerticalNet
	}
	return false
}

func (x *ConsoleInfo) GetSupportsStartRequested() bool {
	if x != nil {
		return x.SupportsStartRequested
	}
	return false
}

func (x *ConsoleInfo) GetSupportsRequireStartRequested() bool {
	if x != nil {
		return x.SupportsRequireStartRequested
	}
	return false
}

func (x *ConsoleInfo) GetSupportsKeyPressObserved() bool {
	if x != nil {
		return x.SupportsKeyPressObserved
	}
	return false
}

func (x *ConsoleInfo) GetSupportsPulse() bool {
	if x != nil {
		return x.SupportsPulse
	}
	return false
}

func (x *ConsoleInfo) GetTotalTimeSeconds() float64 {
	if x != nil {
		return x.TotalTimeSeconds
	}
	return 0
}

func (x *ConsoleInfo) GetWarmUpTimeoutSeconds() float64 {
	if x != nil {
		return x.WarmUpTimeoutSeconds
	}
	return 0
}

func (x *ConsoleInfo) GetCoolDownTimeoutSeconds() float64 {
	if x != nil {
		return x.CoolDownTimeoutSeconds
	}
	return 0
}

func (x *ConsoleInfo) GetPauseTimeoutSeconds() float64 {
	if x != nil {
		return x.PauseTimeoutSeconds
	}
	return 0
}

func (x *ConsoleInfo) GetTotalDistanceKm() float64 {
	if x != nil {
		return x.TotalDistanceKm
	}
	return 0
}

func (x *ConsoleInfo) GetIsClubUnit() bool {
	if x != nil {
		return x.IsClubUnit
	}
	return false
}

func (x *ConsoleInfo) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *ConsoleInfo) GetSupportsConstantWatts() bool {
	if x != nil {
		return x.SupportsConstantWatts
	}
	return false
}

func (x *ConsoleInfo) GetAntPlusBootloaderVersion() string {
	if x != nil {
		return x.AntPlusBootloaderVersion
	}
	return ""
}

func (x *ConsoleInfo) GetAntPlusSerialNumber() string {
	if x != nil {
		return x.AntPlusSerialNumber
	}
	return ""
}

func (x *ConsoleInfo) GetAntPlusDeviceNumber() string {
	if x != nil {
		return x.AntPlusDeviceNumber
	}
	return ""
}

func (x *ConsoleInfo) GetAntPlusRelaySoftwareVersion() string {
	if x != nil {
		return x.AntPlusRelaySoftwareVersion
	}
	return ""
}

func (x *ConsoleInfo) GetProductSerialNumber() string {
	if x != nil {
		return x.ProductSerialNumber
	}
	return ""
}

func (x *ConsoleInfo) GetController1SoftwareVersion() string {
	if x != nil {
		return x.Controller1SoftwareVersion
	}
	return ""
}

func (x *ConsoleInfo) GetController1SoftwarePartNumber() string {
	if x != nil {
		return x.Controller1SoftwarePartNumber
	}
	return ""
}

func (x *ConsoleInfo) GetController4SoftwareVersion() string {
	if x != nil {
		return x.Controller4SoftwareVersion
	}
	return ""
}

func (x *ConsoleInfo) GetController4SoftwarePartNumber() string {
	if x != nil {
		return x.Controller4SoftwarePartNumber
	}
	return ""
}

func (x *ConsoleInfo) GetController40SoftwareVersion() string {
	if x != nil {
		return x.Controller40SoftwareVersion
	}
	return ""
}

func (x *ConsoleInfo) GetController40SoftwarePartNumber() string {
	if x != nil {
		return x.Controller40SoftwarePartNumber
	}
	return ""
}

var File_console_ConsoleInfo_proto protoreflect.FileDescriptor

const file_console_ConsoleInfo_proto_rawDesc = "" +
	"\n" +
	"\x19console/ConsoleInfo.proto\x12\x10com.ifit.glassos\x1a\x19console/ConsoleType.proto\x1a!settings/SystemUnitsService.proto\"\xef\x12\n" +
	"\vConsoleInfo\x12 \n" +
	"\vmodelNumber\x18\x01 \x01(\x05R\vmodelNumber\x12\x1e\n" +
	"\n" +
	"partNumber\x18\x02 \x01(\x05R\n" +
	"partNumber\x12(\n" +
	"\x0fsoftwareVersion\x18\x03 \x01(\x05R\x0fsoftwareVersion\x12(\n" +
	"\x0fhardwareVersion\x18\x04 \x01(\x05R\x0fhardwareVersion\x12(\n" +
	"\x0ffirmwareVersion\x18\x05 \x01(\tR\x0ffirmwareVersion\x12\"\n" +
	"\fserialNumber\x18\x06 \x01(\x05R\fserialNumber\x12?\n" +
	"\vmachineType\x18\a \x01(\x0e2\x1d.com.ifit.glassos.ConsoleTypeR\vmachineType\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x126\n" +
	"\x16brainboardSerialNumber\x18\t \x01(\tR\x16brainboardSerialNumber\x122\n" +
	"\x14masterLibraryVersion\x18\n" +
	" \x01(\x05R\x14masterLibraryVersion\x12.\n" +
	"\x12masterLibraryBuild\x18\v \x01(\x05R\x12masterLibraryBuild\x12?\n" +
	"\vsystemUnits\x18\f \x01(\x0e2\x1d.com.ifit.glassos.SystemUnitsR\vsystemUnits\x12\x16\n" +
	"\x06maxKph\x18\r \x01(\x01R\x06maxKph\x12\x16\n" +
	"\x06minKph\x18\x0e \x01(\x01R\x06minKph\x12,\n" +
	"\x11maxInclinePercent\x18\x0f \x01(\x01R\x11maxInclinePercent\x12,\n" +
	"\x11minInclinePercent\x18\x10 \x01(\x01R\x11minInclinePercent\x12$\n" +
	"\rminResistance\x18\x11 \x01(\x01R\rminResistance\x12$\n" +
	"\rmaxResistance\x18\x12 \x01(\x01R\rmaxResistance\x12\x18\n" +
	"\aminGear\x18\x13 \x01(\x05R\aminGear\x12\x18\n" +
	"\amaxGear\x18\x14 \x01(\x05R\amaxGear\x12 \n" +
	"\vmaxWeightKg\x18\x15 \x01(\x01R\vmaxWeightKg\x12 \n" +
	"\vcanSetSpeed\x18\x16 \x01(\bR\vcanSetSpeed\x12$\n" +
	"\rcanSetIncline\x18\x17 \x01(\bR\rcanSetIncline\x12*\n" +
	"\x10canSetResistance\x18\x18 \x01(\bR\x10canSetResistance\x12\x1e\n" +
	"\n" +
	"canSetGear\x18\x19 \x01(\bR\n" +
	"canSetGear\x122\n" +
	"\x14canSetActivationLock\x18\x1a \x01(\bR\x14canSetActivationLock\x122\n" +
	"\x14supportsVerticalGain\x18\x1b \x01(\bR\x14supportsVerticalGain\x120\n" +
	"\x13supportsVerticalNet\x18\x1c \x01(\bR\x13supportsVerticalNet\x126\n" +
	"\x16supportsStartRequested\x18\x1d \x01(\bR\x16supportsStartRequested\x12D\n" +
	"\x1dsupportsRequireStartRequested\x18\x1e \x01(\bR\x1dsupportsRequireStartRequested\x12:\n" +
	"\x18supportsKeyPressObserved\x18\x1f \x01(\bR\x18supportsKeyPressObserved\x12$\n" +
	"\rsupportsPulse\x18  \x01(\bR\rsupportsPulse\x12*\n" +
	"\x10totalTimeSeconds\x18! \x01(\x01R\x10totalTimeSeconds\x122\n" +
	"\x14warmUpTimeoutSeconds\x18\" \x01(\x01R\x14warmUpTimeoutSeconds\x126\n" +
	"\x16coolDownTimeoutSeconds\x18# \x01(\x01R\x16coolDownTimeoutSeconds\x120\n" +
	"\x13pauseTimeoutSeconds\x18$ \x01(\x01R\x13pauseTimeoutSeconds\x12(\n" +
	"\x0ftotalDistanceKm\x18% \x01(\x01R\x0ftotalDistanceKm\x12\x1e\n" +
	"\n" +
	"isClubUnit\x18& \x01(\bR\n" +
	"isClubUnit\x12\x1a\n" +
	"\bweightKg\x18' \x01(\x01R\bweightKg\x124\n" +
	"\x15supportsConstantWatts\x18( \x01(\bR\x15supportsConstantWatts\x12:\n" +
	"\x18antPlusBootloaderVersion\x18) \x01(\tR\x18antPlusBootloaderVersion\x120\n" +
	"\x13antPlusSerialNumber\x18* \x01(\tR\x13antPlusSerialNumber\x120\n" +
	"\x13antPlusDeviceNumber\x18+ \x01(\tR\x13antPlusDeviceNumber\x12@\n" +
	"\x1bantPlusRelaySoftwareVersion\x18, \x01(\tR\x1bantPlusRelaySoftwareVersion\x120\n" +
	"\x13productSerialNumber\x18- \x01(\tR\x13productSerialNumber\x12>\n" +
	"\x1acontroller1SoftwareVersion\x18. \x01(\tR\x1acontroller1SoftwareVersion\x12D\n" +
	"\x1dcontroller1SoftwarePartNumber\x18/ \x01(\tR\x1dcontroller1SoftwarePartNumber\x12>\n" +
	"\x1acontroller4SoftwareVersion\x180 \x01(\tR\x1acontroller4SoftwareVersion\x12D\n" +
	"\x1dcontroller4SoftwarePartNumber\x181 \x01(\tR\x1dcontroller4SoftwarePartNumber\x12@\n" +
	"\x1bcontroller40SoftwareVersion\x182 \x01(\tR\x1bcontroller40SoftwareVersion\x12F\n" +
	"\x1econtroller40SoftwarePartNumber\x183 \x01(\tR\x1econtroller40SoftwarePartNumberB5\n" +
	"\x18com.ifit.glassos.consoleB\x10ConsoleInfoProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_console_ConsoleInfo_proto_rawDescOnce sync.Once
	file_console_ConsoleInfo_proto_rawDescData []byte
)

func file_console_ConsoleInfo_proto_rawDescGZIP() []byte {
	file_console_ConsoleInfo_proto_rawDescOnce.Do(func() {
		file_console_ConsoleInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_ConsoleInfo_proto_rawDesc), len(file_console_ConsoleInfo_proto_rawDesc)))
	})
	return file_console_ConsoleInfo_proto_rawDescData
}

var file_console_ConsoleInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_console_ConsoleInfo_proto_goTypes = []any{
	(*ConsoleInfo)(nil), // 0: com.ifit.glassos.ConsoleInfo
	(ConsoleType)(0),    // 1: com.ifit.glassos.ConsoleType
	(SystemUnits)(0),    // 2: com.ifit.glassos.SystemUnits
}
var file_console_ConsoleInfo_proto_depIdxs = []int32{
	1, // 0: com.ifit.glassos.ConsoleInfo.machineType:type_name -> com.ifit.glassos.ConsoleType
	2, // 1: com.ifit.glassos.ConsoleInfo.systemUnits:type_name -> com.ifit.glassos.SystemUnits
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_console_ConsoleInfo_proto_init() }
func file_console_ConsoleInfo_proto_init() {
	if File_console_ConsoleInfo_proto != nil {
		return
	}
	file_console_ConsoleType_proto_init()
	file_settings_SystemUnitsService_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_ConsoleInfo_proto_rawDesc), len(file_console_ConsoleInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_console_ConsoleInfo_proto_goTypes,
		DependencyIndexes: file_console_ConsoleInfo_proto_depIdxs,
		MessageInfos:      file_console_ConsoleInfo_proto_msgTypes,
	}.Build()
	File_console_ConsoleInfo_proto = out.File
	file_console_ConsoleInfo_proto_goTypes = nil
	file_console_ConsoleInfo_proto_depIdxs = nil
}
