// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: console/ConsoleError.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleErrorCode int32

const (
	ConsoleErrorCode_FITNESS_VALUE_UNSUPPORTED ConsoleErrorCode = 0
	ConsoleErrorCode_VIRTUAL_CONSOLE_REQUIRED  ConsoleErrorCode = 1
	ConsoleErrorCode_NO_VALUE_SET              ConsoleErrorCode = 2
)

// Enum value maps for ConsoleErrorCode.
var (
	ConsoleErrorCode_name = map[int32]string{
		0: "FITNESS_VALUE_UNSUPPORTED",
		1: "VIRTUAL_CONSOLE_REQUIRED",
		2: "NO_VALUE_SET",
	}
	ConsoleErrorCode_value = map[string]int32{
		"FITNESS_VALUE_UNSUPPORTED": 0,
		"VIRTUAL_CONSOLE_REQUIRED":  1,
		"NO_VALUE_SET":              2,
	}
)

func (x ConsoleErrorCode) Enum() *ConsoleErrorCode {
	p := new(ConsoleErrorCode)
	*p = x
	return p
}

func (x ConsoleErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_console_ConsoleError_proto_enumTypes[0].Descriptor()
}

func (ConsoleErrorCode) Type() protoreflect.EnumType {
	return &file_console_ConsoleError_proto_enumTypes[0]
}

func (x ConsoleErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleErrorCode.Descriptor instead.
func (ConsoleErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_console_ConsoleError_proto_rawDescGZIP(), []int{0}
}

type ConsoleError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ConsoleErrorCode       `protobuf:"varint,1,opt,name=errorCode,proto3,enum=com.ifit.glassos.ConsoleErrorCode" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleError) Reset() {
	*x = ConsoleError{}
	mi := &file_console_ConsoleError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleError) ProtoMessage() {}

func (x *ConsoleError) ProtoReflect() protoreflect.Message {
	mi := &file_console_ConsoleError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleError.ProtoReflect.Descriptor instead.
func (*ConsoleError) Descriptor() ([]byte, []int) {
	return file_console_ConsoleError_proto_rawDescGZIP(), []int{0}
}

func (x *ConsoleError) GetErrorCode() ConsoleErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ConsoleErrorCode_FITNESS_VALUE_UNSUPPORTED
}

func (x *ConsoleError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_console_ConsoleError_proto protoreflect.FileDescriptor

const file_console_ConsoleError_proto_rawDesc = "" +
	"\n" +
	"\x1aconsole/ConsoleError.proto\x12\x10com.ifit.glassos\"j\n" +
	"\fConsoleError\x12@\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\".com.ifit.glassos.ConsoleErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*a\n" +
	"\x10ConsoleErrorCode\x12\x1d\n" +
	"\x19FITNESS_VALUE_UNSUPPORTED\x10\x00\x12\x1c\n" +
	"\x18VIRTUAL_CONSOLE_REQUIRED\x10\x01\x12\x10\n" +
	"\fNO_VALUE_SET\x10\x02B:\n" +
	"\x18com.ifit.glassos.consoleB\x15ConsoleErrorCodeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_console_ConsoleError_proto_rawDescOnce sync.Once
	file_console_ConsoleError_proto_rawDescData []byte
)

func file_console_ConsoleError_proto_rawDescGZIP() []byte {
	file_console_ConsoleError_proto_rawDescOnce.Do(func() {
		file_console_ConsoleError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_ConsoleError_proto_rawDesc), len(file_console_ConsoleError_proto_rawDesc)))
	})
	return file_console_ConsoleError_proto_rawDescData
}

var file_console_ConsoleError_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_ConsoleError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_console_ConsoleError_proto_goTypes = []any{
	(ConsoleErrorCode)(0), // 0: com.ifit.glassos.ConsoleErrorCode
	(*ConsoleError)(nil),  // 1: com.ifit.glassos.ConsoleError
}
var file_console_ConsoleError_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.ConsoleError.errorCode:type_name -> com.ifit.glassos.ConsoleErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_console_ConsoleError_proto_init() }
func file_console_ConsoleError_proto_init() {
	if File_console_ConsoleError_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_ConsoleError_proto_rawDesc), len(file_console_ConsoleError_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_console_ConsoleError_proto_goTypes,
		DependencyIndexes: file_console_ConsoleError_proto_depIdxs,
		EnumInfos:         file_console_ConsoleError_proto_enumTypes,
		MessageInfos:      file_console_ConsoleError_proto_msgTypes,
	}.Build()
	File_console_ConsoleError_proto = out.File
	file_console_ConsoleError_proto_goTypes = nil
	file_console_ConsoleError_proto_depIdxs = nil
}
