// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/ControlType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlType int32

const (
	ControlType_CONTROL_TYPE_UNKNOWN            ControlType = 0
	ControlType_CONTROL_TYPE_INCLINE            ControlType = 1
	ControlType_CONTROL_TYPE_MPS                ControlType = 2
	ControlType_CONTROL_TYPE_RESISTANCE         ControlType = 3
	ControlType_CONTROL_TYPE_GEAR               ControlType = 4
	ControlType_CONTROL_TYPE_AMPLITUDE          ControlType = 5
	ControlType_CONTROL_TYPE_CALORIES           ControlType = 6
	ControlType_CONTROL_TYPE_FREQUENCY          ControlType = 7
	ControlType_CONTROL_TYPE_RELATIVERESISTANCE ControlType = 8
	ControlType_CONTROL_TYPE_RPM                ControlType = 9
	ControlType_CONTROL_TYPE_SPM                ControlType = 10
	ControlType_CONTROL_TYPE_WATTS              ControlType = 11
	ControlType_CONTROL_TYPE_ZONE               ControlType = 12
)

// Enum value maps for ControlType.
var (
	ControlType_name = map[int32]string{
		0:  "CONTROL_TYPE_UNKNOWN",
		1:  "CONTROL_TYPE_INCLINE",
		2:  "CONTROL_TYPE_MPS",
		3:  "CONTROL_TYPE_RESISTANCE",
		4:  "CONTROL_TYPE_GEAR",
		5:  "CONTROL_TYPE_AMPLITUDE",
		6:  "CONTROL_TYPE_CALORIES",
		7:  "CONTROL_TYPE_FREQUENCY",
		8:  "CONTROL_TYPE_RELATIVERESISTANCE",
		9:  "CONTROL_TYPE_RPM",
		10: "CONTROL_TYPE_SPM",
		11: "CONTROL_TYPE_WATTS",
		12: "CONTROL_TYPE_ZONE",
	}
	ControlType_value = map[string]int32{
		"CONTROL_TYPE_UNKNOWN":            0,
		"CONTROL_TYPE_INCLINE":            1,
		"CONTROL_TYPE_MPS":                2,
		"CONTROL_TYPE_RESISTANCE":         3,
		"CONTROL_TYPE_GEAR":               4,
		"CONTROL_TYPE_AMPLITUDE":          5,
		"CONTROL_TYPE_CALORIES":           6,
		"CONTROL_TYPE_FREQUENCY":          7,
		"CONTROL_TYPE_RELATIVERESISTANCE": 8,
		"CONTROL_TYPE_RPM":                9,
		"CONTROL_TYPE_SPM":                10,
		"CONTROL_TYPE_WATTS":              11,
		"CONTROL_TYPE_ZONE":               12,
	}
)

func (x ControlType) Enum() *ControlType {
	p := new(ControlType)
	*p = x
	return p
}

func (x ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_data_ControlType_proto_enumTypes[0].Descriptor()
}

func (ControlType) Type() protoreflect.EnumType {
	return &file_workout_data_ControlType_proto_enumTypes[0]
}

func (x ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlType.Descriptor instead.
func (ControlType) EnumDescriptor() ([]byte, []int) {
	return file_workout_data_ControlType_proto_rawDescGZIP(), []int{0}
}

var File_workout_data_ControlType_proto protoreflect.FileDescriptor

const file_workout_data_ControlType_proto_rawDesc = "" +
	"\n" +
	"\x1eworkout/data/ControlType.proto\x12\x10com.ifit.glassos*\xde\x02\n" +
	"\vControlType\x12\x18\n" +
	"\x14CONTROL_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CONTROL_TYPE_INCLINE\x10\x01\x12\x14\n" +
	"\x10CONTROL_TYPE_MPS\x10\x02\x12\x1b\n" +
	"\x17CONTROL_TYPE_RESISTANCE\x10\x03\x12\x15\n" +
	"\x11CONTROL_TYPE_GEAR\x10\x04\x12\x1a\n" +
	"\x16CONTROL_TYPE_AMPLITUDE\x10\x05\x12\x19\n" +
	"\x15CONTROL_TYPE_CALORIES\x10\x06\x12\x1a\n" +
	"\x16CONTROL_TYPE_FREQUENCY\x10\a\x12#\n" +
	"\x1fCONTROL_TYPE_RELATIVERESISTANCE\x10\b\x12\x14\n" +
	"\x10CONTROL_TYPE_RPM\x10\t\x12\x14\n" +
	"\x10CONTROL_TYPE_SPM\x10\n" +
	"\x12\x16\n" +
	"\x12CONTROL_TYPE_WATTS\x10\v\x12\x15\n" +
	"\x11CONTROL_TYPE_ZONE\x10\fB:\n" +
	"\x1dcom.ifit.glassos.workout.dataB\x10ControlTypeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_ControlType_proto_rawDescOnce sync.Once
	file_workout_data_ControlType_proto_rawDescData []byte
)

func file_workout_data_ControlType_proto_rawDescGZIP() []byte {
	file_workout_data_ControlType_proto_rawDescOnce.Do(func() {
		file_workout_data_ControlType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_ControlType_proto_rawDesc), len(file_workout_data_ControlType_proto_rawDesc)))
	})
	return file_workout_data_ControlType_proto_rawDescData
}

var file_workout_data_ControlType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_data_ControlType_proto_goTypes = []any{
	(ControlType)(0), // 0: com.ifit.glassos.ControlType
}
var file_workout_data_ControlType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_ControlType_proto_init() }
func file_workout_data_ControlType_proto_init() {
	if File_workout_data_ControlType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_ControlType_proto_rawDesc), len(file_workout_data_ControlType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_ControlType_proto_goTypes,
		DependencyIndexes: file_workout_data_ControlType_proto_depIdxs,
		EnumInfos:         file_workout_data_ControlType_proto_enumTypes,
	}.Build()
	File_workout_data_ControlType_proto = out.File
	file_workout_data_ControlType_proto_goTypes = nil
	file_workout_data_ControlType_proto_depIdxs = nil
}
