// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/Control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlType            `protobuf:"varint,1,opt,name=type,proto3,enum=com.ifit.glassos.ControlType" json:"type,omitempty"`
	At            float64                `protobuf:"fixed64,2,opt,name=at,proto3" json:"at,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_workout_data_Control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_workout_data_Control_proto_rawDescGZIP(), []int{0}
}

func (x *Control) GetType() ControlType {
	if x != nil {
		return x.Type
	}
	return ControlType_CONTROL_TYPE_UNKNOWN
}

func (x *Control) GetAt() float64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Control) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ControlList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controls      []*Control             `protobuf:"bytes,1,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlList) Reset() {
	*x = ControlList{}
	mi := &file_workout_data_Control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlList) ProtoMessage() {}

func (x *ControlList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlList.ProtoReflect.Descriptor instead.
func (*ControlList) Descriptor() ([]byte, []int) {
	return file_workout_data_Control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlList) GetControls() []*Control {
	if x != nil {
		return x.Controls
	}
	return nil
}

var File_workout_data_Control_proto protoreflect.FileDescriptor

const file_workout_data_Control_proto_rawDesc = "" +
	"\n" +
	"\x1aworkout/data/Control.proto\x12\x10com.ifit.glassos\x1a\x1eworkout/data/ControlType.proto\"b\n" +
	"\aControl\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.com.ifit.glassos.ControlTypeR\x04type\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x01R\x02at\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"D\n" +
	"\vControlList\x125\n" +
	"\bcontrols\x18\x01 \x03(\v2\x19.com.ifit.glassos.ControlR\bcontrolsB6\n" +
	"\x1dcom.ifit.glassos.workout.dataB\fControlProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_Control_proto_rawDescOnce sync.Once
	file_workout_data_Control_proto_rawDescData []byte
)

func file_workout_data_Control_proto_rawDescGZIP() []byte {
	file_workout_data_Control_proto_rawDescOnce.Do(func() {
		file_workout_data_Control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_Control_proto_rawDesc), len(file_workout_data_Control_proto_rawDesc)))
	})
	return file_workout_data_Control_proto_rawDescData
}

var file_workout_data_Control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workout_data_Control_proto_goTypes = []any{
	(*Control)(nil),     // 0: com.ifit.glassos.Control
	(*ControlList)(nil), // 1: com.ifit.glassos.ControlList
	(ControlType)(0),    // 2: com.ifit.glassos.ControlType
}
var file_workout_data_Control_proto_depIdxs = []int32{
	2, // 0: com.ifit.glassos.Control.type:type_name -> com.ifit.glassos.ControlType
	0, // 1: com.ifit.glassos.ControlList.controls:type_name -> com.ifit.glassos.Control
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workout_data_Control_proto_init() }
func file_workout_data_Control_proto_init() {
	if File_workout_data_Control_proto != nil {
		return
	}
	file_workout_data_ControlType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_Control_proto_rawDesc), len(file_workout_data_Control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_Control_proto_goTypes,
		DependencyIndexes: file_workout_data_Control_proto_depIdxs,
		MessageInfos:      file_workout_data_Control_proto_msgTypes,
	}.Build()
	File_workout_data_Control_proto = out.File
	file_workout_data_Control_proto_goTypes = nil
	file_workout_data_Control_proto_depIdxs = nil
}
