// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/DistanceService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistanceMetric struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkoutID           string                 `protobuf:"bytes,1,opt,name=workoutID,proto3" json:"workoutID,omitempty"`
	TimeSeconds         int32                  `protobuf:"varint,2,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	LastDistanceKm      float64                `protobuf:"fixed64,3,opt,name=lastDistanceKm,proto3" json:"lastDistanceKm,omitempty"`
	RemainingDistanceKm float64                `protobuf:"fixed64,4,opt,name=remainingDistanceKm,proto3" json:"remainingDistanceKm,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DistanceMetric) Reset() {
	*x = DistanceMetric{}
	mi := &file_workout_DistanceService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMetric) ProtoMessage() {}

func (x *DistanceMetric) ProtoReflect() protoreflect.Message {
	mi := &file_workout_DistanceService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMetric.ProtoReflect.Descriptor instead.
func (*DistanceMetric) Descriptor() ([]byte, []int) {
	return file_workout_DistanceService_proto_rawDescGZIP(), []int{0}
}

func (x *DistanceMetric) GetWorkoutID() string {
	if x != nil {
		return x.WorkoutID
	}
	return ""
}

func (x *DistanceMetric) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *DistanceMetric) GetLastDistanceKm() float64 {
	if x != nil {
		return x.LastDistanceKm
	}
	return 0
}

func (x *DistanceMetric) GetRemainingDistanceKm() float64 {
	if x != nil {
		return x.RemainingDistanceKm
	}
	return 0
}

type DistanceMetricList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*DistanceMetric      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMetricList) Reset() {
	*x = DistanceMetricList{}
	mi := &file_workout_DistanceService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMetricList) ProtoMessage() {}

func (x *DistanceMetricList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_DistanceService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMetricList.ProtoReflect.Descriptor instead.
func (*DistanceMetricList) Descriptor() ([]byte, []int) {
	return file_workout_DistanceService_proto_rawDescGZIP(), []int{1}
}

func (x *DistanceMetricList) GetMetrics() []*DistanceMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_workout_DistanceService_proto protoreflect.FileDescriptor

const file_workout_DistanceService_proto_rawDesc = "" +
	"\n" +
	"\x1dworkout/DistanceService.proto\x12\x10com.ifit.glassos\x1a\x0futil/Util.proto\"\xaa\x01\n" +
	"\x0eDistanceMetric\x12\x1c\n" +
	"\tworkoutID\x18\x01 \x01(\tR\tworkoutID\x12 \n" +
	"\vtimeSeconds\x18\x02 \x01(\x05R\vtimeSeconds\x12&\n" +
	"\x0elastDistanceKm\x18\x03 \x01(\x01R\x0elastDistanceKm\x120\n" +
	"\x13remainingDistanceKm\x18\x04 \x01(\x01R\x13remainingDistanceKm\"P\n" +
	"\x12DistanceMetricList\x12:\n" +
	"\ametrics\x18\x01 \x03(\v2 .com.ifit.glassos.DistanceMetricR\ametrics2\xdd\x02\n" +
	"\x0fDistanceService\x12L\n" +
	"\aCanRead\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12J\n" +
	"\vGetDistance\x12\x17.com.ifit.glassos.Empty\x1a .com.ifit.glassos.DistanceMetric\"\x00\x12U\n" +
	"\x14DistanceSubscription\x12\x17.com.ifit.glassos.Empty\x1a .com.ifit.glassos.DistanceMetric\"\x000\x01\x12Y\n" +
	"\x12GetDistanceHistory\x12\x1b.com.ifit.glassos.WorkoutID\x1a$.com.ifit.glassos.DistanceMetricList\"\x00B9\n" +
	"\x18com.ifit.glassos.workoutB\x14DistanceServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_DistanceService_proto_rawDescOnce sync.Once
	file_workout_DistanceService_proto_rawDescData []byte
)

func file_workout_DistanceService_proto_rawDescGZIP() []byte {
	file_workout_DistanceService_proto_rawDescOnce.Do(func() {
		file_workout_DistanceService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_DistanceService_proto_rawDesc), len(file_workout_DistanceService_proto_rawDesc)))
	})
	return file_workout_DistanceService_proto_rawDescData
}

var file_workout_DistanceService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workout_DistanceService_proto_goTypes = []any{
	(*DistanceMetric)(nil),       // 0: com.ifit.glassos.DistanceMetric
	(*DistanceMetricList)(nil),   // 1: com.ifit.glassos.DistanceMetricList
	(*Empty)(nil),                // 2: com.ifit.glassos.Empty
	(*WorkoutID)(nil),            // 3: com.ifit.glassos.WorkoutID
	(*AvailabilityResponse)(nil), // 4: com.ifit.glassos.AvailabilityResponse
}
var file_workout_DistanceService_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.DistanceMetricList.metrics:type_name -> com.ifit.glassos.DistanceMetric
	2, // 1: com.ifit.glassos.DistanceService.CanRead:input_type -> com.ifit.glassos.Empty
	2, // 2: com.ifit.glassos.DistanceService.GetDistance:input_type -> com.ifit.glassos.Empty
	2, // 3: com.ifit.glassos.DistanceService.DistanceSubscription:input_type -> com.ifit.glassos.Empty
	3, // 4: com.ifit.glassos.DistanceService.GetDistanceHistory:input_type -> com.ifit.glassos.WorkoutID
	4, // 5: com.ifit.glassos.DistanceService.CanRead:output_type -> com.ifit.glassos.AvailabilityResponse
	0, // 6: com.ifit.glassos.DistanceService.GetDistance:output_type -> com.ifit.glassos.DistanceMetric
	0, // 7: com.ifit.glassos.DistanceService.DistanceSubscription:output_type -> com.ifit.glassos.DistanceMetric
	1, // 8: com.ifit.glassos.DistanceService.GetDistanceHistory:output_type -> com.ifit.glassos.DistanceMetricList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workout_DistanceService_proto_init() }
func file_workout_DistanceService_proto_init() {
	if File_workout_DistanceService_proto != nil {
		return
	}
	file_util_Util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_DistanceService_proto_rawDesc), len(file_workout_DistanceService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_DistanceService_proto_goTypes,
		DependencyIndexes: file_workout_DistanceService_proto_depIdxs,
		MessageInfos:      file_workout_DistanceService_proto_msgTypes,
	}.Build()
	File_workout_DistanceService_proto = out.File
	file_workout_DistanceService_proto_goTypes = nil
	file_workout_DistanceService_proto_depIdxs = nil
}
