// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/ElapsedTimeService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ElapsedTimeService_CanRead_FullMethodName                 = "/com.ifit.glassos.ElapsedTimeService/CanRead"
	ElapsedTimeService_GetElapsedTime_FullMethodName          = "/com.ifit.glassos.ElapsedTimeService/GetElapsedTime"
	ElapsedTimeService_ElapsedTimeSubscription_FullMethodName = "/com.ifit.glassos.ElapsedTimeService/ElapsedTimeSubscription"
	ElapsedTimeService_GetElapsedTimeHistory_FullMethodName   = "/com.ifit.glassos.ElapsedTimeService/GetElapsedTimeHistory"
)

// ElapsedTimeServiceClient is the client API for ElapsedTimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElapsedTimeServiceClient interface {
	// check whether ElapsedTime is Readable
	CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// get the current Elapsed Time relative to the current workout
	GetElapsedTime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ElapsedTimeMetric, error)
	// subscribe to ElapsedTime updates relative to the current workout
	ElapsedTimeSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ElapsedTimeMetric], error)
	// gets a list of all of the ElapsedTime changes for the given workout ID
	GetElapsedTimeHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*ElapsedTimeMetricList, error)
}

type elapsedTimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewElapsedTimeServiceClient(cc grpc.ClientConnInterface) ElapsedTimeServiceClient {
	return &elapsedTimeServiceClient{cc}
}

func (c *elapsedTimeServiceClient) CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, ElapsedTimeService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elapsedTimeServiceClient) GetElapsedTime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ElapsedTimeMetric, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElapsedTimeMetric)
	err := c.cc.Invoke(ctx, ElapsedTimeService_GetElapsedTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elapsedTimeServiceClient) ElapsedTimeSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ElapsedTimeMetric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ElapsedTimeService_ServiceDesc.Streams[0], ElapsedTimeService_ElapsedTimeSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ElapsedTimeMetric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ElapsedTimeService_ElapsedTimeSubscriptionClient = grpc.ServerStreamingClient[ElapsedTimeMetric]

func (c *elapsedTimeServiceClient) GetElapsedTimeHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*ElapsedTimeMetricList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElapsedTimeMetricList)
	err := c.cc.Invoke(ctx, ElapsedTimeService_GetElapsedTimeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElapsedTimeServiceServer is the server API for ElapsedTimeService service.
// All implementations must embed UnimplementedElapsedTimeServiceServer
// for forward compatibility.
type ElapsedTimeServiceServer interface {
	// check whether ElapsedTime is Readable
	CanRead(context.Context, *Empty) (*AvailabilityResponse, error)
	// get the current Elapsed Time relative to the current workout
	GetElapsedTime(context.Context, *Empty) (*ElapsedTimeMetric, error)
	// subscribe to ElapsedTime updates relative to the current workout
	ElapsedTimeSubscription(*Empty, grpc.ServerStreamingServer[ElapsedTimeMetric]) error
	// gets a list of all of the ElapsedTime changes for the given workout ID
	GetElapsedTimeHistory(context.Context, *WorkoutID) (*ElapsedTimeMetricList, error)
	mustEmbedUnimplementedElapsedTimeServiceServer()
}

// UnimplementedElapsedTimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedElapsedTimeServiceServer struct{}

func (UnimplementedElapsedTimeServiceServer) CanRead(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedElapsedTimeServiceServer) GetElapsedTime(context.Context, *Empty) (*ElapsedTimeMetric, error) {
	return nil, status.Error(codes.Unimplemented, "method GetElapsedTime not implemented")
}
func (UnimplementedElapsedTimeServiceServer) ElapsedTimeSubscription(*Empty, grpc.ServerStreamingServer[ElapsedTimeMetric]) error {
	return status.Error(codes.Unimplemented, "method ElapsedTimeSubscription not implemented")
}
func (UnimplementedElapsedTimeServiceServer) GetElapsedTimeHistory(context.Context, *WorkoutID) (*ElapsedTimeMetricList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetElapsedTimeHistory not implemented")
}
func (UnimplementedElapsedTimeServiceServer) mustEmbedUnimplementedElapsedTimeServiceServer() {}
func (UnimplementedElapsedTimeServiceServer) testEmbeddedByValue()                            {}

// UnsafeElapsedTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElapsedTimeServiceServer will
// result in compilation errors.
type UnsafeElapsedTimeServiceServer interface {
	mustEmbedUnimplementedElapsedTimeServiceServer()
}

func RegisterElapsedTimeServiceServer(s grpc.ServiceRegistrar, srv ElapsedTimeServiceServer) {
	// If the following call panics, it indicates UnimplementedElapsedTimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ElapsedTimeService_ServiceDesc, srv)
}

func _ElapsedTimeService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElapsedTimeServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElapsedTimeService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElapsedTimeServiceServer).CanRead(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ElapsedTimeService_GetElapsedTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElapsedTimeServiceServer).GetElapsedTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElapsedTimeService_GetElapsedTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElapsedTimeServiceServer).GetElapsedTime(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ElapsedTimeService_ElapsedTimeSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ElapsedTimeServiceServer).ElapsedTimeSubscription(m, &grpc.GenericServerStream[Empty, ElapsedTimeMetric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ElapsedTimeService_ElapsedTimeSubscriptionServer = grpc.ServerStreamingServer[ElapsedTimeMetric]

func _ElapsedTimeService_GetElapsedTimeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElapsedTimeServiceServer).GetElapsedTimeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElapsedTimeService_GetElapsedTimeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElapsedTimeServiceServer).GetElapsedTimeHistory(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

// ElapsedTimeService_ServiceDesc is the grpc.ServiceDesc for ElapsedTimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ElapsedTimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.ElapsedTimeService",
	HandlerType: (*ElapsedTimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanRead",
			Handler:    _ElapsedTimeService_CanRead_Handler,
		},
		{
			MethodName: "GetElapsedTime",
			Handler:    _ElapsedTimeService_GetElapsedTime_Handler,
		},
		{
			MethodName: "GetElapsedTimeHistory",
			Handler:    _ElapsedTimeService_GetElapsedTimeHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ElapsedTimeSubscription",
			Handler:       _ElapsedTimeService_ElapsedTimeSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/ElapsedTimeService.proto",
}
