// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/ElevationService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElevationMetric struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkoutID           string                 `protobuf:"bytes,1,opt,name=workoutID,proto3" json:"workoutID,omitempty"`
	TimeSeconds         int32                  `protobuf:"varint,2,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	ElevationGainMeters float64                `protobuf:"fixed64,3,opt,name=elevationGainMeters,proto3" json:"elevationGainMeters,omitempty"`
	ElevationLossMeters float64                `protobuf:"fixed64,4,opt,name=elevationLossMeters,proto3" json:"elevationLossMeters,omitempty"`
	ElevationNetMeters  float64                `protobuf:"fixed64,5,opt,name=elevationNetMeters,proto3" json:"elevationNetMeters,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ElevationMetric) Reset() {
	*x = ElevationMetric{}
	mi := &file_workout_ElevationService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElevationMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElevationMetric) ProtoMessage() {}

func (x *ElevationMetric) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ElevationService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElevationMetric.ProtoReflect.Descriptor instead.
func (*ElevationMetric) Descriptor() ([]byte, []int) {
	return file_workout_ElevationService_proto_rawDescGZIP(), []int{0}
}

func (x *ElevationMetric) GetWorkoutID() string {
	if x != nil {
		return x.WorkoutID
	}
	return ""
}

func (x *ElevationMetric) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *ElevationMetric) GetElevationGainMeters() float64 {
	if x != nil {
		return x.ElevationGainMeters
	}
	return 0
}

func (x *ElevationMetric) GetElevationLossMeters() float64 {
	if x != nil {
		return x.ElevationLossMeters
	}
	return 0
}

func (x *ElevationMetric) GetElevationNetMeters() float64 {
	if x != nil {
		return x.ElevationNetMeters
	}
	return 0
}

type ElevationMetricList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*ElevationMetric     `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElevationMetricList) Reset() {
	*x = ElevationMetricList{}
	mi := &file_workout_ElevationService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElevationMetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElevationMetricList) ProtoMessage() {}

func (x *ElevationMetricList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ElevationService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElevationMetricList.ProtoReflect.Descriptor instead.
func (*ElevationMetricList) Descriptor() ([]byte, []int) {
	return file_workout_ElevationService_proto_rawDescGZIP(), []int{1}
}

func (x *ElevationMetricList) GetMetrics() []*ElevationMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_workout_ElevationService_proto protoreflect.FileDescriptor

const file_workout_ElevationService_proto_rawDesc = "" +
	"\n" +
	"\x1eworkout/ElevationService.proto\x12\x10com.ifit.glassos\x1a\x0futil/Util.proto\"\xe5\x01\n" +
	"\x0fElevationMetric\x12\x1c\n" +
	"\tworkoutID\x18\x01 \x01(\tR\tworkoutID\x12 \n" +
	"\vtimeSeconds\x18\x02 \x01(\x05R\vtimeSeconds\x120\n" +
	"\x13elevationGainMeters\x18\x03 \x01(\x01R\x13elevationGainMeters\x120\n" +
	"\x13elevationLossMeters\x18\x04 \x01(\x01R\x13elevationLossMeters\x12.\n" +
	"\x12elevationNetMeters\x18\x05 \x01(\x01R\x12elevationNetMeters\"R\n" +
	"\x13ElevationMetricList\x12;\n" +
	"\ametrics\x18\x01 \x03(\v2!.com.ifit.glassos.ElevationMetricR\ametrics2\xe4\x02\n" +
	"\x10ElevationService\x12L\n" +
	"\aCanRead\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12L\n" +
	"\fGetElevation\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.ElevationMetric\"\x00\x12W\n" +
	"\x15ElevationSubscription\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.ElevationMetric\"\x000\x01\x12[\n" +
	"\x13GetElevationHistory\x12\x1b.com.ifit.glassos.WorkoutID\x1a%.com.ifit.glassos.ElevationMetricList\"\x00B:\n" +
	"\x18com.ifit.glassos.workoutB\x15ElevationServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_ElevationService_proto_rawDescOnce sync.Once
	file_workout_ElevationService_proto_rawDescData []byte
)

func file_workout_ElevationService_proto_rawDescGZIP() []byte {
	file_workout_ElevationService_proto_rawDescOnce.Do(func() {
		file_workout_ElevationService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_ElevationService_proto_rawDesc), len(file_workout_ElevationService_proto_rawDesc)))
	})
	return file_workout_ElevationService_proto_rawDescData
}

var file_workout_ElevationService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workout_ElevationService_proto_goTypes = []any{
	(*ElevationMetric)(nil),      // 0: com.ifit.glassos.ElevationMetric
	(*ElevationMetricList)(nil),  // 1: com.ifit.glassos.ElevationMetricList
	(*Empty)(nil),                // 2: com.ifit.glassos.Empty
	(*WorkoutID)(nil),            // 3: com.ifit.glassos.WorkoutID
	(*AvailabilityResponse)(nil), // 4: com.ifit.glassos.AvailabilityResponse
}
var file_workout_ElevationService_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.ElevationMetricList.metrics:type_name -> com.ifit.glassos.ElevationMetric
	2, // 1: com.ifit.glassos.ElevationService.CanRead:input_type -> com.ifit.glassos.Empty
	2, // 2: com.ifit.glassos.ElevationService.GetElevation:input_type -> com.ifit.glassos.Empty
	2, // 3: com.ifit.glassos.ElevationService.ElevationSubscription:input_type -> com.ifit.glassos.Empty
	3, // 4: com.ifit.glassos.ElevationService.GetElevationHistory:input_type -> com.ifit.glassos.WorkoutID
	4, // 5: com.ifit.glassos.ElevationService.CanRead:output_type -> com.ifit.glassos.AvailabilityResponse
	0, // 6: com.ifit.glassos.ElevationService.GetElevation:output_type -> com.ifit.glassos.ElevationMetric
	0, // 7: com.ifit.glassos.ElevationService.ElevationSubscription:output_type -> com.ifit.glassos.ElevationMetric
	1, // 8: com.ifit.glassos.ElevationService.GetElevationHistory:output_type -> com.ifit.glassos.ElevationMetricList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workout_ElevationService_proto_init() }
func file_workout_ElevationService_proto_init() {
	if File_workout_ElevationService_proto != nil {
		return
	}
	file_util_Util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_ElevationService_proto_rawDesc), len(file_workout_ElevationService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_ElevationService_proto_goTypes,
		DependencyIndexes: file_workout_ElevationService_proto_depIdxs,
		MessageInfos:      file_workout_ElevationService_proto_msgTypes,
	}.Build()
	File_workout_ElevationService_proto = out.File
	file_workout_ElevationService_proto_goTypes = nil
	file_workout_ElevationService_proto_depIdxs = nil
}
