// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/ElevationService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ElevationService_CanRead_FullMethodName               = "/com.ifit.glassos.ElevationService/CanRead"
	ElevationService_GetElevation_FullMethodName          = "/com.ifit.glassos.ElevationService/GetElevation"
	ElevationService_ElevationSubscription_FullMethodName = "/com.ifit.glassos.ElevationService/ElevationSubscription"
	ElevationService_GetElevationHistory_FullMethodName   = "/com.ifit.glassos.ElevationService/GetElevationHistory"
)

// ElevationServiceClient is the client API for ElevationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElevationServiceClient interface {
	// check whether Elevation is Readable
	CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// get the current Elevation relative to the current workout
	GetElevation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ElevationMetric, error)
	// subscribe to Elevation updates relative to the current workout
	ElevationSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ElevationMetric], error)
	// gets a list of all of the Elevation changes for the given workout ID
	GetElevationHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*ElevationMetricList, error)
}

type elevationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewElevationServiceClient(cc grpc.ClientConnInterface) ElevationServiceClient {
	return &elevationServiceClient{cc}
}

func (c *elevationServiceClient) CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, ElevationService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elevationServiceClient) GetElevation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ElevationMetric, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElevationMetric)
	err := c.cc.Invoke(ctx, ElevationService_GetElevation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elevationServiceClient) ElevationSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ElevationMetric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ElevationService_ServiceDesc.Streams[0], ElevationService_ElevationSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ElevationMetric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ElevationService_ElevationSubscriptionClient = grpc.ServerStreamingClient[ElevationMetric]

func (c *elevationServiceClient) GetElevationHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*ElevationMetricList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElevationMetricList)
	err := c.cc.Invoke(ctx, ElevationService_GetElevationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElevationServiceServer is the server API for ElevationService service.
// All implementations must embed UnimplementedElevationServiceServer
// for forward compatibility.
type ElevationServiceServer interface {
	// check whether Elevation is Readable
	CanRead(context.Context, *Empty) (*AvailabilityResponse, error)
	// get the current Elevation relative to the current workout
	GetElevation(context.Context, *Empty) (*ElevationMetric, error)
	// subscribe to Elevation updates relative to the current workout
	ElevationSubscription(*Empty, grpc.ServerStreamingServer[ElevationMetric]) error
	// gets a list of all of the Elevation changes for the given workout ID
	GetElevationHistory(context.Context, *WorkoutID) (*ElevationMetricList, error)
	mustEmbedUnimplementedElevationServiceServer()
}

// UnimplementedElevationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedElevationServiceServer struct{}

func (UnimplementedElevationServiceServer) CanRead(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedElevationServiceServer) GetElevation(context.Context, *Empty) (*ElevationMetric, error) {
	return nil, status.Error(codes.Unimplemented, "method GetElevation not implemented")
}
func (UnimplementedElevationServiceServer) ElevationSubscription(*Empty, grpc.ServerStreamingServer[ElevationMetric]) error {
	return status.Error(codes.Unimplemented, "method ElevationSubscription not implemented")
}
func (UnimplementedElevationServiceServer) GetElevationHistory(context.Context, *WorkoutID) (*ElevationMetricList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetElevationHistory not implemented")
}
func (UnimplementedElevationServiceServer) mustEmbedUnimplementedElevationServiceServer() {}
func (UnimplementedElevationServiceServer) testEmbeddedByValue()                          {}

// UnsafeElevationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElevationServiceServer will
// result in compilation errors.
type UnsafeElevationServiceServer interface {
	mustEmbedUnimplementedElevationServiceServer()
}

func RegisterElevationServiceServer(s grpc.ServiceRegistrar, srv ElevationServiceServer) {
	// If the following call panics, it indicates UnimplementedElevationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ElevationService_ServiceDesc, srv)
}

func _ElevationService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElevationServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElevationService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElevationServiceServer).CanRead(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ElevationService_GetElevation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElevationServiceServer).GetElevation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElevationService_GetElevation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElevationServiceServer).GetElevation(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ElevationService_ElevationSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ElevationServiceServer).ElevationSubscription(m, &grpc.GenericServerStream[Empty, ElevationMetric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ElevationService_ElevationSubscriptionServer = grpc.ServerStreamingServer[ElevationMetric]

func _ElevationService_GetElevationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElevationServiceServer).GetElevationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElevationService_GetElevationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElevationServiceServer).GetElevationHistory(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

// ElevationService_ServiceDesc is the grpc.ServiceDesc for ElevationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ElevationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.ElevationService",
	HandlerType: (*ElevationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanRead",
			Handler:    _ElevationService_CanRead_Handler,
		},
		{
			MethodName: "GetElevation",
			Handler:    _ElevationService_GetElevation_Handler,
		},
		{
			MethodName: "GetElevationHistory",
			Handler:    _ElevationService_GetElevationHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ElevationSubscription",
			Handler:       _ElevationService_ElevationSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/ElevationService.proto",
}
