// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/HeartRateService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartRateMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutID     string                 `protobuf:"bytes,1,opt,name=workoutID,proto3" json:"workoutID,omitempty"`
	TimeSeconds   int32                  `protobuf:"varint,2,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	LastBpm       float64                `protobuf:"fixed64,3,opt,name=lastBpm,proto3" json:"lastBpm,omitempty"`
	MaxBpm        float64                `protobuf:"fixed64,4,opt,name=maxBpm,proto3" json:"maxBpm,omitempty"`
	AvgBpm        float64                `protobuf:"fixed64,5,opt,name=avgBpm,proto3" json:"avgBpm,omitempty"`
	MinBpm        float64                `protobuf:"fixed64,6,opt,name=minBpm,proto3" json:"minBpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartRateMetric) Reset() {
	*x = HeartRateMetric{}
	mi := &file_workout_HeartRateService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartRateMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRateMetric) ProtoMessage() {}

func (x *HeartRateMetric) ProtoReflect() protoreflect.Message {
	mi := &file_workout_HeartRateService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRateMetric.ProtoReflect.Descriptor instead.
func (*HeartRateMetric) Descriptor() ([]byte, []int) {
	return file_workout_HeartRateService_proto_rawDescGZIP(), []int{0}
}

func (x *HeartRateMetric) GetWorkoutID() string {
	if x != nil {
		return x.WorkoutID
	}
	return ""
}

func (x *HeartRateMetric) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *HeartRateMetric) GetLastBpm() float64 {
	if x != nil {
		return x.LastBpm
	}
	return 0
}

func (x *HeartRateMetric) GetMaxBpm() float64 {
	if x != nil {
		return x.MaxBpm
	}
	return 0
}

func (x *HeartRateMetric) GetAvgBpm() float64 {
	if x != nil {
		return x.AvgBpm
	}
	return 0
}

func (x *HeartRateMetric) GetMinBpm() float64 {
	if x != nil {
		return x.MinBpm
	}
	return 0
}

type HeartRateMetricList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*HeartRateMetric     `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartRateMetricList) Reset() {
	*x = HeartRateMetricList{}
	mi := &file_workout_HeartRateService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartRateMetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRateMetricList) ProtoMessage() {}

func (x *HeartRateMetricList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_HeartRateService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRateMetricList.ProtoReflect.Descriptor instead.
func (*HeartRateMetricList) Descriptor() ([]byte, []int) {
	return file_workout_HeartRateService_proto_rawDescGZIP(), []int{1}
}

func (x *HeartRateMetricList) GetMetrics() []*HeartRateMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bpm           float64                `protobuf:"fixed64,1,opt,name=bpm,proto3" json:"bpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartRateRequest) Reset() {
	*x = HeartRateRequest{}
	mi := &file_workout_HeartRateService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRateRequest) ProtoMessage() {}

func (x *HeartRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_HeartRateService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRateRequest.ProtoReflect.Descriptor instead.
func (*HeartRateRequest) Descriptor() ([]byte, []int) {
	return file_workout_HeartRateService_proto_rawDescGZIP(), []int{2}
}

func (x *HeartRateRequest) GetBpm() float64 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

var File_workout_HeartRateService_proto protoreflect.FileDescriptor

const file_workout_HeartRateService_proto_rawDesc = "" +
	"\n" +
	"\x1eworkout/HeartRateService.proto\x12\x10com.ifit.glassos\x1a\x0futil/Util.proto\x1a\x1bworkout/WorkoutResult.proto\"\xb3\x01\n" +
	"\x0fHeartRateMetric\x12\x1c\n" +
	"\tworkoutID\x18\x01 \x01(\tR\tworkoutID\x12 \n" +
	"\vtimeSeconds\x18\x02 \x01(\x05R\vtimeSeconds\x12\x18\n" +
	"\alastBpm\x18\x03 \x01(\x01R\alastBpm\x12\x16\n" +
	"\x06maxBpm\x18\x04 \x01(\x01R\x06maxBpm\x12\x16\n" +
	"\x06avgBpm\x18\x05 \x01(\x01R\x06avgBpm\x12\x16\n" +
	"\x06minBpm\x18\x06 \x01(\x01R\x06minBpm\"R\n" +
	"\x13HeartRateMetricList\x12;\n" +
	"\ametrics\x18\x01 \x03(\v2!.com.ifit.glassos.HeartRateMetricR\ametrics\"$\n" +
	"\x10HeartRateRequest\x12\x10\n" +
	"\x03bpm\x18\x01 \x01(\x01R\x03bpm2\x8a\x04\n" +
	"\x10HeartRateService\x12L\n" +
	"\aCanRead\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12M\n" +
	"\bCanWrite\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12L\n" +
	"\fGetHeartRate\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.HeartRateMetric\"\x00\x12U\n" +
	"\fSetHeartRate\x12\".com.ifit.glassos.HeartRateRequest\x1a\x1f.com.ifit.glassos.WorkoutResult\"\x00\x12W\n" +
	"\x15HeartRateSubscription\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.HeartRateMetric\"\x000\x01\x12[\n" +
	"\x13GetHeartRateHistory\x12\x1b.com.ifit.glassos.WorkoutID\x1a%.com.ifit.glassos.HeartRateMetricList\"\x00B:\n" +
	"\x18com.ifit.glassos.workoutB\x15HeartRateServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_HeartRateService_proto_rawDescOnce sync.Once
	file_workout_HeartRateService_proto_rawDescData []byte
)

func file_workout_HeartRateService_proto_rawDescGZIP() []byte {
	file_workout_HeartRateService_proto_rawDescOnce.Do(func() {
		file_workout_HeartRateService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_HeartRateService_proto_rawDesc), len(file_workout_HeartRateService_proto_rawDesc)))
	})
	return file_workout_HeartRateService_proto_rawDescData
}

var file_workout_HeartRateService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workout_HeartRateService_proto_goTypes = []any{
	(*HeartRateMetric)(nil),      // 0: com.ifit.glassos.HeartRateMetric
	(*HeartRateMetricList)(nil),  // 1: com.ifit.glassos.HeartRateMetricList
	(*HeartRateRequest)(nil),     // 2: com.ifit.glassos.HeartRateRequest
	(*Empty)(nil),                // 3: com.ifit.glassos.Empty
	(*WorkoutID)(nil),            // 4: com.ifit.glassos.WorkoutID
	(*AvailabilityResponse)(nil), // 5: com.ifit.glassos.AvailabilityResponse
	(*WorkoutResult)(nil),        // 6: com.ifit.glassos.WorkoutResult
}
var file_workout_HeartRateService_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.HeartRateMetricList.metrics:type_name -> com.ifit.glassos.HeartRateMetric
	3, // 1: com.ifit.glassos.HeartRateService.CanRead:input_type -> com.ifit.glassos.Empty
	3, // 2: com.ifit.glassos.HeartRateService.CanWrite:input_type -> com.ifit.glassos.Empty
	3, // 3: com.ifit.glassos.HeartRateService.GetHeartRate:input_type -> com.ifit.glassos.Empty
	2, // 4: com.ifit.glassos.HeartRateService.SetHeartRate:input_type -> com.ifit.glassos.HeartRateRequest
	3, // 5: com.ifit.glassos.HeartRateService.HeartRateSubscription:input_type -> com.ifit.glassos.Empty
	4, // 6: com.ifit.glassos.HeartRateService.GetHeartRateHistory:input_type -> com.ifit.glassos.WorkoutID
	5, // 7: com.ifit.glassos.HeartRateService.CanRead:output_type -> com.ifit.glassos.AvailabilityResponse
	5, // 8: com.ifit.glassos.HeartRateService.CanWrite:output_type -> com.ifit.glassos.AvailabilityResponse
	0, // 9: com.ifit.glassos.HeartRateService.GetHeartRate:output_type -> com.ifit.glassos.HeartRateMetric
	6, // 10: com.ifit.glassos.HeartRateService.SetHeartRate:output_type -> com.ifit.glassos.WorkoutResult
	0, // 11: com.ifit.glassos.HeartRateService.HeartRateSubscription:output_type -> com.ifit.glassos.HeartRateMetric
	1, // 12: com.ifit.glassos.HeartRateService.GetHeartRateHistory:output_type -> com.ifit.glassos.HeartRateMetricList
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workout_HeartRateService_proto_init() }
func file_workout_HeartRateService_proto_init() {
	if File_workout_HeartRateService_proto != nil {
		return
	}
	file_util_Util_proto_init()
	file_workout_WorkoutResult_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_HeartRateService_proto_rawDesc), len(file_workout_HeartRateService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_HeartRateService_proto_goTypes,
		DependencyIndexes: file_workout_HeartRateService_proto_depIdxs,
		MessageInfos:      file_workout_HeartRateService_proto_msgTypes,
	}.Build()
	File_workout_HeartRateService_proto = out.File
	file_workout_HeartRateService_proto_goTypes = nil
	file_workout_HeartRateService_proto_depIdxs = nil
}
