// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/HeartRateService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeartRateService_CanRead_FullMethodName               = "/com.ifit.glassos.HeartRateService/CanRead"
	HeartRateService_CanWrite_FullMethodName              = "/com.ifit.glassos.HeartRateService/CanWrite"
	HeartRateService_GetHeartRate_FullMethodName          = "/com.ifit.glassos.HeartRateService/GetHeartRate"
	HeartRateService_SetHeartRate_FullMethodName          = "/com.ifit.glassos.HeartRateService/SetHeartRate"
	HeartRateService_HeartRateSubscription_FullMethodName = "/com.ifit.glassos.HeartRateService/HeartRateSubscription"
	HeartRateService_GetHeartRateHistory_FullMethodName   = "/com.ifit.glassos.HeartRateService/GetHeartRateHistory"
)

// HeartRateServiceClient is the client API for HeartRateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartRateServiceClient interface {
	// check whether HeartRate is Readable
	CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// check whether HeartRate is Writable, like for Virtual Console or from outside apps like Apple Watch
	CanWrite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// get the current Heart Rate Metric relative to the current workout
	GetHeartRate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartRateMetric, error)
	SetHeartRate(ctx context.Context, in *HeartRateRequest, opts ...grpc.CallOption) (*WorkoutResult, error)
	// subscribe to HeartRate updates relative to the current workout
	HeartRateSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeartRateMetric], error)
	// gets a list of all of the HeartRate changes for the given workout ID
	GetHeartRateHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*HeartRateMetricList, error)
}

type heartRateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartRateServiceClient(cc grpc.ClientConnInterface) HeartRateServiceClient {
	return &heartRateServiceClient{cc}
}

func (c *heartRateServiceClient) CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, HeartRateService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heartRateServiceClient) CanWrite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, HeartRateService_CanWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heartRateServiceClient) GetHeartRate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartRateMetric, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartRateMetric)
	err := c.cc.Invoke(ctx, HeartRateService_GetHeartRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heartRateServiceClient) SetHeartRate(ctx context.Context, in *HeartRateRequest, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, HeartRateService_SetHeartRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heartRateServiceClient) HeartRateSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HeartRateMetric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HeartRateService_ServiceDesc.Streams[0], HeartRateService_HeartRateSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, HeartRateMetric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HeartRateService_HeartRateSubscriptionClient = grpc.ServerStreamingClient[HeartRateMetric]

func (c *heartRateServiceClient) GetHeartRateHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*HeartRateMetricList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartRateMetricList)
	err := c.cc.Invoke(ctx, HeartRateService_GetHeartRateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartRateServiceServer is the server API for HeartRateService service.
// All implementations must embed UnimplementedHeartRateServiceServer
// for forward compatibility.
type HeartRateServiceServer interface {
	// check whether HeartRate is Readable
	CanRead(context.Context, *Empty) (*AvailabilityResponse, error)
	// check whether HeartRate is Writable, like for Virtual Console or from outside apps like Apple Watch
	CanWrite(context.Context, *Empty) (*AvailabilityResponse, error)
	// get the current Heart Rate Metric relative to the current workout
	GetHeartRate(context.Context, *Empty) (*HeartRateMetric, error)
	SetHeartRate(context.Context, *HeartRateRequest) (*WorkoutResult, error)
	// subscribe to HeartRate updates relative to the current workout
	HeartRateSubscription(*Empty, grpc.ServerStreamingServer[HeartRateMetric]) error
	// gets a list of all of the HeartRate changes for the given workout ID
	GetHeartRateHistory(context.Context, *WorkoutID) (*HeartRateMetricList, error)
	mustEmbedUnimplementedHeartRateServiceServer()
}

// UnimplementedHeartRateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeartRateServiceServer struct{}

func (UnimplementedHeartRateServiceServer) CanRead(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedHeartRateServiceServer) CanWrite(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanWrite not implemented")
}
func (UnimplementedHeartRateServiceServer) GetHeartRate(context.Context, *Empty) (*HeartRateMetric, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeartRate not implemented")
}
func (UnimplementedHeartRateServiceServer) SetHeartRate(context.Context, *HeartRateRequest) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHeartRate not implemented")
}
func (UnimplementedHeartRateServiceServer) HeartRateSubscription(*Empty, grpc.ServerStreamingServer[HeartRateMetric]) error {
	return status.Error(codes.Unimplemented, "method HeartRateSubscription not implemented")
}
func (UnimplementedHeartRateServiceServer) GetHeartRateHistory(context.Context, *WorkoutID) (*HeartRateMetricList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeartRateHistory not implemented")
}
func (UnimplementedHeartRateServiceServer) mustEmbedUnimplementedHeartRateServiceServer() {}
func (UnimplementedHeartRateServiceServer) testEmbeddedByValue()                          {}

// UnsafeHeartRateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartRateServiceServer will
// result in compilation errors.
type UnsafeHeartRateServiceServer interface {
	mustEmbedUnimplementedHeartRateServiceServer()
}

func RegisterHeartRateServiceServer(s grpc.ServiceRegistrar, srv HeartRateServiceServer) {
	// If the following call panics, it indicates UnimplementedHeartRateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeartRateService_ServiceDesc, srv)
}

func _HeartRateService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartRateServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeartRateService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartRateServiceServer).CanRead(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeartRateService_CanWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartRateServiceServer).CanWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeartRateService_CanWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartRateServiceServer).CanWrite(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeartRateService_GetHeartRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartRateServiceServer).GetHeartRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeartRateService_GetHeartRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartRateServiceServer).GetHeartRate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeartRateService_SetHeartRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartRateServiceServer).SetHeartRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeartRateService_SetHeartRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartRateServiceServer).SetHeartRate(ctx, req.(*HeartRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeartRateService_HeartRateSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HeartRateServiceServer).HeartRateSubscription(m, &grpc.GenericServerStream[Empty, HeartRateMetric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HeartRateService_HeartRateSubscriptionServer = grpc.ServerStreamingServer[HeartRateMetric]

func _HeartRateService_GetHeartRateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartRateServiceServer).GetHeartRateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeartRateService_GetHeartRateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartRateServiceServer).GetHeartRateHistory(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

// HeartRateService_ServiceDesc is the grpc.ServiceDesc for HeartRateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeartRateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.HeartRateService",
	HandlerType: (*HeartRateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanRead",
			Handler:    _HeartRateService_CanRead_Handler,
		},
		{
			MethodName: "CanWrite",
			Handler:    _HeartRateService_CanWrite_Handler,
		},
		{
			MethodName: "GetHeartRate",
			Handler:    _HeartRateService_GetHeartRate_Handler,
		},
		{
			MethodName: "SetHeartRate",
			Handler:    _HeartRateService_SetHeartRate_Handler,
		},
		{
			MethodName: "GetHeartRateHistory",
			Handler:    _HeartRateService_GetHeartRateHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartRateSubscription",
			Handler:       _HeartRateService_HeartRateSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/HeartRateService.proto",
}
