// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: util/IFitError.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IFitError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*IFitError_NetworkError
	//	*IFitError_UserError
	//	*IFitError_AuthError
	//	*IFitError_ConnectionError
	//	*IFitError_WorkoutError
	//	*IFitError_InputError
	//	*IFitError_ActivityLogError
	//	*IFitError_ConsoleError
	//	*IFitError_ProgrammedSessionError
	Error         isIFitError_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IFitError) Reset() {
	*x = IFitError{}
	mi := &file_util_IFitError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IFitError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IFitError) ProtoMessage() {}

func (x *IFitError) ProtoReflect() protoreflect.Message {
	mi := &file_util_IFitError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IFitError.ProtoReflect.Descriptor instead.
func (*IFitError) Descriptor() ([]byte, []int) {
	return file_util_IFitError_proto_rawDescGZIP(), []int{0}
}

func (x *IFitError) GetError() isIFitError_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *IFitError) GetNetworkError() *NetworkError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_NetworkError); ok {
			return x.NetworkError
		}
	}
	return nil
}

func (x *IFitError) GetUserError() *UserError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_UserError); ok {
			return x.UserError
		}
	}
	return nil
}

func (x *IFitError) GetAuthError() *AuthError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_AuthError); ok {
			return x.AuthError
		}
	}
	return nil
}

func (x *IFitError) GetConnectionError() *ConnectionError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_ConnectionError); ok {
			return x.ConnectionError
		}
	}
	return nil
}

func (x *IFitError) GetWorkoutError() *WorkoutError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_WorkoutError); ok {
			return x.WorkoutError
		}
	}
	return nil
}

func (x *IFitError) GetInputError() *InputError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_InputError); ok {
			return x.InputError
		}
	}
	return nil
}

func (x *IFitError) GetActivityLogError() *ActivityLogError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_ActivityLogError); ok {
			return x.ActivityLogError
		}
	}
	return nil
}

func (x *IFitError) GetConsoleError() *ConsoleError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_ConsoleError); ok {
			return x.ConsoleError
		}
	}
	return nil
}

func (x *IFitError) GetProgrammedSessionError() *ProgrammedWorkoutSessionError {
	if x != nil {
		if x, ok := x.Error.(*IFitError_ProgrammedSessionError); ok {
			return x.ProgrammedSessionError
		}
	}
	return nil
}

type isIFitError_Error interface {
	isIFitError_Error()
}

type IFitError_NetworkError struct {
	NetworkError *NetworkError `protobuf:"bytes,1,opt,name=networkError,proto3,oneof"`
}

type IFitError_UserError struct {
	UserError *UserError `protobuf:"bytes,2,opt,name=userError,proto3,oneof"`
}

type IFitError_AuthError struct {
	AuthError *AuthError `protobuf:"bytes,3,opt,name=authError,proto3,oneof"`
}

type IFitError_ConnectionError struct {
	ConnectionError *ConnectionError `protobuf:"bytes,4,opt,name=connectionError,proto3,oneof"`
}

type IFitError_WorkoutError struct {
	WorkoutError *WorkoutError `protobuf:"bytes,5,opt,name=workoutError,proto3,oneof"`
}

type IFitError_InputError struct {
	InputError *InputError `protobuf:"bytes,6,opt,name=inputError,proto3,oneof"`
}

type IFitError_ActivityLogError struct {
	ActivityLogError *ActivityLogError `protobuf:"bytes,7,opt,name=activityLogError,proto3,oneof"`
}

type IFitError_ConsoleError struct {
	ConsoleError *ConsoleError `protobuf:"bytes,8,opt,name=consoleError,proto3,oneof"`
}

type IFitError_ProgrammedSessionError struct {
	ProgrammedSessionError *ProgrammedWorkoutSessionError `protobuf:"bytes,9,opt,name=programmedSessionError,proto3,oneof"`
}

func (*IFitError_NetworkError) isIFitError_Error() {}

func (*IFitError_UserError) isIFitError_Error() {}

func (*IFitError_AuthError) isIFitError_Error() {}

func (*IFitError_ConnectionError) isIFitError_Error() {}

func (*IFitError_WorkoutError) isIFitError_Error() {}

func (*IFitError_InputError) isIFitError_Error() {}

func (*IFitError_ActivityLogError) isIFitError_Error() {}

func (*IFitError_ConsoleError) isIFitError_Error() {}

func (*IFitError_ProgrammedSessionError) isIFitError_Error() {}

var File_util_IFitError_proto protoreflect.FileDescriptor

const file_util_IFitError_proto_rawDesc = "" +
	"\n" +
	"\x14util/IFitError.proto\x12\x10com.ifit.glassos\x1a\"activitylog/ActivityLogError.proto\x1a\x14auth/AuthError.proto\x1a\x1aconsole/ConsoleError.proto\x1a\x14user/UserError.proto\x1a\x1autil/ConnectionError.proto\x1a\x15util/InputError.proto\x1a\x17util/NetworkError.proto\x1a+workout/ProgrammedWorkoutSessionError.proto\x1a\x1aworkout/WorkoutError.proto\"\xac\x05\n" +
	"\tIFitError\x12D\n" +
	"\fnetworkError\x18\x01 \x01(\v2\x1e.com.ifit.glassos.NetworkErrorH\x00R\fnetworkError\x12;\n" +
	"\tuserError\x18\x02 \x01(\v2\x1b.com.ifit.glassos.UserErrorH\x00R\tuserError\x12;\n" +
	"\tauthError\x18\x03 \x01(\v2\x1b.com.ifit.glassos.AuthErrorH\x00R\tauthError\x12M\n" +
	"\x0fconnectionError\x18\x04 \x01(\v2!.com.ifit.glassos.ConnectionErrorH\x00R\x0fconnectionError\x12D\n" +
	"\fworkoutError\x18\x05 \x01(\v2\x1e.com.ifit.glassos.WorkoutErrorH\x00R\fworkoutError\x12>\n" +
	"\n" +
	"inputError\x18\x06 \x01(\v2\x1c.com.ifit.glassos.InputErrorH\x00R\n" +
	"inputError\x12P\n" +
	"\x10activityLogError\x18\a \x01(\v2\".com.ifit.glassos.ActivityLogErrorH\x00R\x10activityLogError\x12D\n" +
	"\fconsoleError\x18\b \x01(\v2\x1e.com.ifit.glassos.ConsoleErrorH\x00R\fconsoleError\x12i\n" +
	"\x16programmedSessionError\x18\t \x01(\v2/.com.ifit.glassos.ProgrammedWorkoutSessionErrorH\x00R\x16programmedSessionErrorB\a\n" +
	"\x05errorB,\n" +
	"\x15com.ifit.glassos.utilB\x0eIFitErrorProtoP\x01\xba\x02\x00b\x06proto3"

var (
	file_util_IFitError_proto_rawDescOnce sync.Once
	file_util_IFitError_proto_rawDescData []byte
)

func file_util_IFitError_proto_rawDescGZIP() []byte {
	file_util_IFitError_proto_rawDescOnce.Do(func() {
		file_util_IFitError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_IFitError_proto_rawDesc), len(file_util_IFitError_proto_rawDesc)))
	})
	return file_util_IFitError_proto_rawDescData
}

var file_util_IFitError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_IFitError_proto_goTypes = []any{
	(*IFitError)(nil),                     // 0: com.ifit.glassos.IFitError
	(*NetworkError)(nil),                  // 1: com.ifit.glassos.NetworkError
	(*UserError)(nil),                     // 2: com.ifit.glassos.UserError
	(*AuthError)(nil),                     // 3: com.ifit.glassos.AuthError
	(*ConnectionError)(nil),               // 4: com.ifit.glassos.ConnectionError
	(*WorkoutError)(nil),                  // 5: com.ifit.glassos.WorkoutError
	(*InputError)(nil),                    // 6: com.ifit.glassos.InputError
	(*ActivityLogError)(nil),              // 7: com.ifit.glassos.ActivityLogError
	(*ConsoleError)(nil),                  // 8: com.ifit.glassos.ConsoleError
	(*ProgrammedWorkoutSessionError)(nil), // 9: com.ifit.glassos.ProgrammedWorkoutSessionError
}
var file_util_IFitError_proto_depIdxs = []int32{
	1, // 0: com.ifit.glassos.IFitError.networkError:type_name -> com.ifit.glassos.NetworkError
	2, // 1: com.ifit.glassos.IFitError.userError:type_name -> com.ifit.glassos.UserError
	3, // 2: com.ifit.glassos.IFitError.authError:type_name -> com.ifit.glassos.AuthError
	4, // 3: com.ifit.glassos.IFitError.connectionError:type_name -> com.ifit.glassos.ConnectionError
	5, // 4: com.ifit.glassos.IFitError.workoutError:type_name -> com.ifit.glassos.WorkoutError
	6, // 5: com.ifit.glassos.IFitError.inputError:type_name -> com.ifit.glassos.InputError
	7, // 6: com.ifit.glassos.IFitError.activityLogError:type_name -> com.ifit.glassos.ActivityLogError
	8, // 7: com.ifit.glassos.IFitError.consoleError:type_name -> com.ifit.glassos.ConsoleError
	9, // 8: com.ifit.glassos.IFitError.programmedSessionError:type_name -> com.ifit.glassos.ProgrammedWorkoutSessionError
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_util_IFitError_proto_init() }
func file_util_IFitError_proto_init() {
	if File_util_IFitError_proto != nil {
		return
	}
	file_activitylog_ActivityLogError_proto_init()
	file_auth_AuthError_proto_init()
	file_console_ConsoleError_proto_init()
	file_user_UserError_proto_init()
	file_util_ConnectionError_proto_init()
	file_util_InputError_proto_init()
	file_util_NetworkError_proto_init()
	file_workout_ProgrammedWorkoutSessionError_proto_init()
	file_workout_WorkoutError_proto_init()
	file_util_IFitError_proto_msgTypes[0].OneofWrappers = []any{
		(*IFitError_NetworkError)(nil),
		(*IFitError_UserError)(nil),
		(*IFitError_AuthError)(nil),
		(*IFitError_ConnectionError)(nil),
		(*IFitError_WorkoutError)(nil),
		(*IFitError_InputError)(nil),
		(*IFitError_ActivityLogError)(nil),
		(*IFitError_ConsoleError)(nil),
		(*IFitError_ProgrammedSessionError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_IFitError_proto_rawDesc), len(file_util_IFitError_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_IFitError_proto_goTypes,
		DependencyIndexes: file_util_IFitError_proto_depIdxs,
		MessageInfos:      file_util_IFitError_proto_msgTypes,
	}.Build()
	File_util_IFitError_proto = out.File
	file_util_IFitError_proto_goTypes = nil
	file_util_IFitError_proto_depIdxs = nil
}
