// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/InclineService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InclineService_CanRead_FullMethodName                 = "/com.ifit.glassos.InclineService/CanRead"
	InclineService_CanWrite_FullMethodName                = "/com.ifit.glassos.InclineService/CanWrite"
	InclineService_GetIncline_FullMethodName              = "/com.ifit.glassos.InclineService/GetIncline"
	InclineService_SetIncline_FullMethodName              = "/com.ifit.glassos.InclineService/SetIncline"
	InclineService_InclineSubscription_FullMethodName     = "/com.ifit.glassos.InclineService/InclineSubscription"
	InclineService_GetInclineHistory_FullMethodName       = "/com.ifit.glassos.InclineService/GetInclineHistory"
	InclineService_FollowWorkout_FullMethodName           = "/com.ifit.glassos.InclineService/FollowWorkout"
	InclineService_StopFollowing_FullMethodName           = "/com.ifit.glassos.InclineService/StopFollowing"
	InclineService_GetIsFollowing_FullMethodName          = "/com.ifit.glassos.InclineService/GetIsFollowing"
	InclineService_IsFollowingSubscription_FullMethodName = "/com.ifit.glassos.InclineService/IsFollowingSubscription"
	InclineService_GetControls_FullMethodName             = "/com.ifit.glassos.InclineService/GetControls"
	InclineService_ControlsSubscription_FullMethodName    = "/com.ifit.glassos.InclineService/ControlsSubscription"
)

// InclineServiceClient is the client API for InclineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InclineServiceClient interface {
	// check whether Incline is Readable and Writeable
	CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	CanWrite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// get the current Incline relative to the current workout
	GetIncline(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InclineMetric, error)
	// sets the Incline to the given value
	SetIncline(ctx context.Context, in *InclineRequest, opts ...grpc.CallOption) (*WorkoutResult, error)
	// subscribe to Incline updates relative to the current workout
	InclineSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InclineMetric], error)
	// gets a list of all of the Incline changes for the given workout ID
	GetInclineHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*InclineMetricList, error)
	// follow the current workout
	FollowWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error)
	// stop following the current workout
	StopFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// check whether the current workout is being followed
	GetIsFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BooleanResponse, error)
	// subscribe to following updates
	IsFollowingSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BooleanResponse], error)
	// get the current workout controls
	GetControls(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlList, error)
	// subscribe to workout control updates
	ControlsSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlList], error)
}

type inclineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInclineServiceClient(cc grpc.ClientConnInterface) InclineServiceClient {
	return &inclineServiceClient{cc}
}

func (c *inclineServiceClient) CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, InclineService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) CanWrite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, InclineService_CanWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) GetIncline(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InclineMetric, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InclineMetric)
	err := c.cc.Invoke(ctx, InclineService_GetIncline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) SetIncline(ctx context.Context, in *InclineRequest, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, InclineService_SetIncline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) InclineSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InclineMetric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InclineService_ServiceDesc.Streams[0], InclineService_InclineSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, InclineMetric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InclineService_InclineSubscriptionClient = grpc.ServerStreamingClient[InclineMetric]

func (c *inclineServiceClient) GetInclineHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*InclineMetricList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InclineMetricList)
	err := c.cc.Invoke(ctx, InclineService_GetInclineHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) FollowWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, InclineService_FollowWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) StopFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InclineService_StopFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) GetIsFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooleanResponse)
	err := c.cc.Invoke(ctx, InclineService_GetIsFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) IsFollowingSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BooleanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InclineService_ServiceDesc.Streams[1], InclineService_IsFollowingSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, BooleanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InclineService_IsFollowingSubscriptionClient = grpc.ServerStreamingClient[BooleanResponse]

func (c *inclineServiceClient) GetControls(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlList)
	err := c.cc.Invoke(ctx, InclineService_GetControls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inclineServiceClient) ControlsSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InclineService_ServiceDesc.Streams[2], InclineService_ControlsSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ControlList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InclineService_ControlsSubscriptionClient = grpc.ServerStreamingClient[ControlList]

// InclineServiceServer is the server API for InclineService service.
// All implementations must embed UnimplementedInclineServiceServer
// for forward compatibility.
type InclineServiceServer interface {
	// check whether Incline is Readable and Writeable
	CanRead(context.Context, *Empty) (*AvailabilityResponse, error)
	CanWrite(context.Context, *Empty) (*AvailabilityResponse, error)
	// get the current Incline relative to the current workout
	GetIncline(context.Context, *Empty) (*InclineMetric, error)
	// sets the Incline to the given value
	SetIncline(context.Context, *InclineRequest) (*WorkoutResult, error)
	// subscribe to Incline updates relative to the current workout
	InclineSubscription(*Empty, grpc.ServerStreamingServer[InclineMetric]) error
	// gets a list of all of the Incline changes for the given workout ID
	GetInclineHistory(context.Context, *WorkoutID) (*InclineMetricList, error)
	// follow the current workout
	FollowWorkout(context.Context, *Empty) (*WorkoutResult, error)
	// stop following the current workout
	StopFollowing(context.Context, *Empty) (*Empty, error)
	// check whether the current workout is being followed
	GetIsFollowing(context.Context, *Empty) (*BooleanResponse, error)
	// subscribe to following updates
	IsFollowingSubscription(*Empty, grpc.ServerStreamingServer[BooleanResponse]) error
	// get the current workout controls
	GetControls(context.Context, *Empty) (*ControlList, error)
	// subscribe to workout control updates
	ControlsSubscription(*Empty, grpc.ServerStreamingServer[ControlList]) error
	mustEmbedUnimplementedInclineServiceServer()
}

// UnimplementedInclineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInclineServiceServer struct{}

func (UnimplementedInclineServiceServer) CanRead(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedInclineServiceServer) CanWrite(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanWrite not implemented")
}
func (UnimplementedInclineServiceServer) GetIncline(context.Context, *Empty) (*InclineMetric, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncline not implemented")
}
func (UnimplementedInclineServiceServer) SetIncline(context.Context, *InclineRequest) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetIncline not implemented")
}
func (UnimplementedInclineServiceServer) InclineSubscription(*Empty, grpc.ServerStreamingServer[InclineMetric]) error {
	return status.Error(codes.Unimplemented, "method InclineSubscription not implemented")
}
func (UnimplementedInclineServiceServer) GetInclineHistory(context.Context, *WorkoutID) (*InclineMetricList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInclineHistory not implemented")
}
func (UnimplementedInclineServiceServer) FollowWorkout(context.Context, *Empty) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowWorkout not implemented")
}
func (UnimplementedInclineServiceServer) StopFollowing(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopFollowing not implemented")
}
func (UnimplementedInclineServiceServer) GetIsFollowing(context.Context, *Empty) (*BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIsFollowing not implemented")
}
func (UnimplementedInclineServiceServer) IsFollowingSubscription(*Empty, grpc.ServerStreamingServer[BooleanResponse]) error {
	return status.Error(codes.Unimplemented, "method IsFollowingSubscription not implemented")
}
func (UnimplementedInclineServiceServer) GetControls(context.Context, *Empty) (*ControlList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetControls not implemented")
}
func (UnimplementedInclineServiceServer) ControlsSubscription(*Empty, grpc.ServerStreamingServer[ControlList]) error {
	return status.Error(codes.Unimplemented, "method ControlsSubscription not implemented")
}
func (UnimplementedInclineServiceServer) mustEmbedUnimplementedInclineServiceServer() {}
func (UnimplementedInclineServiceServer) testEmbeddedByValue()                        {}

// UnsafeInclineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InclineServiceServer will
// result in compilation errors.
type UnsafeInclineServiceServer interface {
	mustEmbedUnimplementedInclineServiceServer()
}

func RegisterInclineServiceServer(s grpc.ServiceRegistrar, srv InclineServiceServer) {
	// If the following call panics, it indicates UnimplementedInclineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InclineService_ServiceDesc, srv)
}

func _InclineService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).CanRead(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_CanWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).CanWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_CanWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).CanWrite(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_GetIncline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).GetIncline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_GetIncline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).GetIncline(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_SetIncline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InclineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).SetIncline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_SetIncline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).SetIncline(ctx, req.(*InclineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_InclineSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InclineServiceServer).InclineSubscription(m, &grpc.GenericServerStream[Empty, InclineMetric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InclineService_InclineSubscriptionServer = grpc.ServerStreamingServer[InclineMetric]

func _InclineService_GetInclineHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).GetInclineHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_GetInclineHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).GetInclineHistory(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_FollowWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).FollowWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_FollowWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).FollowWorkout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_StopFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).StopFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_StopFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).StopFollowing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_GetIsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).GetIsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_GetIsFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).GetIsFollowing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_IsFollowingSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InclineServiceServer).IsFollowingSubscription(m, &grpc.GenericServerStream[Empty, BooleanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InclineService_IsFollowingSubscriptionServer = grpc.ServerStreamingServer[BooleanResponse]

func _InclineService_GetControls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InclineServiceServer).GetControls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InclineService_GetControls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InclineServiceServer).GetControls(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InclineService_ControlsSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InclineServiceServer).ControlsSubscription(m, &grpc.GenericServerStream[Empty, ControlList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InclineService_ControlsSubscriptionServer = grpc.ServerStreamingServer[ControlList]

// InclineService_ServiceDesc is the grpc.ServiceDesc for InclineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InclineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.InclineService",
	HandlerType: (*InclineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanRead",
			Handler:    _InclineService_CanRead_Handler,
		},
		{
			MethodName: "CanWrite",
			Handler:    _InclineService_CanWrite_Handler,
		},
		{
			MethodName: "GetIncline",
			Handler:    _InclineService_GetIncline_Handler,
		},
		{
			MethodName: "SetIncline",
			Handler:    _InclineService_SetIncline_Handler,
		},
		{
			MethodName: "GetInclineHistory",
			Handler:    _InclineService_GetInclineHistory_Handler,
		},
		{
			MethodName: "FollowWorkout",
			Handler:    _InclineService_FollowWorkout_Handler,
		},
		{
			MethodName: "StopFollowing",
			Handler:    _InclineService_StopFollowing_Handler,
		},
		{
			MethodName: "GetIsFollowing",
			Handler:    _InclineService_GetIsFollowing_Handler,
		},
		{
			MethodName: "GetControls",
			Handler:    _InclineService_GetControls_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InclineSubscription",
			Handler:       _InclineService_InclineSubscription_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IsFollowingSubscription",
			Handler:       _InclineService_IsFollowingSubscription_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ControlsSubscription",
			Handler:       _InclineService_ControlsSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/InclineService.proto",
}
