// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/ItemType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_ITEM_TYPE_WARM_UP   ItemType = 0
	ItemType_ITEM_TYPE_MAIN      ItemType = 1
	ItemType_ITEM_TYPE_COOL_DOWN ItemType = 2
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_WARM_UP",
		1: "ITEM_TYPE_MAIN",
		2: "ITEM_TYPE_COOL_DOWN",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_WARM_UP":   0,
		"ITEM_TYPE_MAIN":      1,
		"ITEM_TYPE_COOL_DOWN": 2,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_data_ItemType_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_workout_data_ItemType_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_workout_data_ItemType_proto_rawDescGZIP(), []int{0}
}

var File_workout_data_ItemType_proto protoreflect.FileDescriptor

const file_workout_data_ItemType_proto_rawDesc = "" +
	"\n" +
	"\x1bworkout/data/ItemType.proto\x12\x10com.ifit.glassos*N\n" +
	"\bItemType\x12\x15\n" +
	"\x11ITEM_TYPE_WARM_UP\x10\x00\x12\x12\n" +
	"\x0eITEM_TYPE_MAIN\x10\x01\x12\x17\n" +
	"\x13ITEM_TYPE_COOL_DOWN\x10\x02B7\n" +
	"\x1dcom.ifit.glassos.workout.dataB\rItemTypeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_ItemType_proto_rawDescOnce sync.Once
	file_workout_data_ItemType_proto_rawDescData []byte
)

func file_workout_data_ItemType_proto_rawDescGZIP() []byte {
	file_workout_data_ItemType_proto_rawDescOnce.Do(func() {
		file_workout_data_ItemType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_ItemType_proto_rawDesc), len(file_workout_data_ItemType_proto_rawDesc)))
	})
	return file_workout_data_ItemType_proto_rawDescData
}

var file_workout_data_ItemType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_data_ItemType_proto_goTypes = []any{
	(ItemType)(0), // 0: com.ifit.glassos.ItemType
}
var file_workout_data_ItemType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_ItemType_proto_init() }
func file_workout_data_ItemType_proto_init() {
	if File_workout_data_ItemType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_ItemType_proto_rawDesc), len(file_workout_data_ItemType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_ItemType_proto_goTypes,
		DependencyIndexes: file_workout_data_ItemType_proto_depIdxs,
		EnumInfos:         file_workout_data_ItemType_proto_enumTypes,
	}.Build()
	File_workout_data_ItemType_proto = out.File
	file_workout_data_ItemType_proto_goTypes = nil
	file_workout_data_ItemType_proto_depIdxs = nil
}
