// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/video/MusicRegion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MusicRegion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartMilliSeconds int64                  `protobuf:"varint,1,opt,name=startMilliSeconds,proto3" json:"startMilliSeconds,omitempty"`
	EndMilliSeconds   int64                  `protobuf:"varint,2,opt,name=endMilliSeconds,proto3" json:"endMilliSeconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MusicRegion) Reset() {
	*x = MusicRegion{}
	mi := &file_workout_data_video_MusicRegion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicRegion) ProtoMessage() {}

func (x *MusicRegion) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_video_MusicRegion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicRegion.ProtoReflect.Descriptor instead.
func (*MusicRegion) Descriptor() ([]byte, []int) {
	return file_workout_data_video_MusicRegion_proto_rawDescGZIP(), []int{0}
}

func (x *MusicRegion) GetStartMilliSeconds() int64 {
	if x != nil {
		return x.StartMilliSeconds
	}
	return 0
}

func (x *MusicRegion) GetEndMilliSeconds() int64 {
	if x != nil {
		return x.EndMilliSeconds
	}
	return 0
}

var File_workout_data_video_MusicRegion_proto protoreflect.FileDescriptor

const file_workout_data_video_MusicRegion_proto_rawDesc = "" +
	"\n" +
	"$workout/data/video/MusicRegion.proto\x12\x10com.ifit.glassos\"e\n" +
	"\vMusicRegion\x12,\n" +
	"\x11startMilliSeconds\x18\x01 \x01(\x03R\x11startMilliSeconds\x12(\n" +
	"\x0fendMilliSeconds\x18\x02 \x01(\x03R\x0fendMilliSecondsB@\n" +
	"#com.ifit.glassos.workout.data.videoB\x10MusicRegionProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_video_MusicRegion_proto_rawDescOnce sync.Once
	file_workout_data_video_MusicRegion_proto_rawDescData []byte
)

func file_workout_data_video_MusicRegion_proto_rawDescGZIP() []byte {
	file_workout_data_video_MusicRegion_proto_rawDescOnce.Do(func() {
		file_workout_data_video_MusicRegion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_video_MusicRegion_proto_rawDesc), len(file_workout_data_video_MusicRegion_proto_rawDesc)))
	})
	return file_workout_data_video_MusicRegion_proto_rawDescData
}

var file_workout_data_video_MusicRegion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workout_data_video_MusicRegion_proto_goTypes = []any{
	(*MusicRegion)(nil), // 0: com.ifit.glassos.MusicRegion
}
var file_workout_data_video_MusicRegion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_video_MusicRegion_proto_init() }
func file_workout_data_video_MusicRegion_proto_init() {
	if File_workout_data_video_MusicRegion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_video_MusicRegion_proto_rawDesc), len(file_workout_data_video_MusicRegion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_video_MusicRegion_proto_goTypes,
		DependencyIndexes: file_workout_data_video_MusicRegion_proto_depIdxs,
		MessageInfos:      file_workout_data_video_MusicRegion_proto_msgTypes,
	}.Build()
	File_workout_data_video_MusicRegion_proto = out.File
	file_workout_data_video_MusicRegion_proto_goTypes = nil
	file_workout_data_video_MusicRegion_proto_depIdxs = nil
}
