// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/ProgrammedWorkoutSessionService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAllWorkoutSegmentsRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	WorkoutSegments []*WorkoutSegmentDescriptor `protobuf:"bytes,1,rep,name=workoutSegments,proto3" json:"workoutSegments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddAllWorkoutSegmentsRequest) Reset() {
	*x = AddAllWorkoutSegmentsRequest{}
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAllWorkoutSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAllWorkoutSegmentsRequest) ProtoMessage() {}

func (x *AddAllWorkoutSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAllWorkoutSegmentsRequest.ProtoReflect.Descriptor instead.
func (*AddAllWorkoutSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP(), []int{0}
}

func (x *AddAllWorkoutSegmentsRequest) GetWorkoutSegments() []*WorkoutSegmentDescriptor {
	if x != nil {
		return x.WorkoutSegments
	}
	return nil
}

type ProgrammedWorkoutServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ErrorOrSuccess:
	//
	//	*ProgrammedWorkoutServiceResponse_Success
	//	*ProgrammedWorkoutServiceResponse_ProgrammedSessionError
	//	*ProgrammedWorkoutServiceResponse_WorkoutError
	//	*ProgrammedWorkoutServiceResponse_NetworkError
	ErrorOrSuccess isProgrammedWorkoutServiceResponse_ErrorOrSuccess `protobuf_oneof:"errorOrSuccess"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgrammedWorkoutServiceResponse) Reset() {
	*x = ProgrammedWorkoutServiceResponse{}
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgrammedWorkoutServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgrammedWorkoutServiceResponse) ProtoMessage() {}

func (x *ProgrammedWorkoutServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgrammedWorkoutServiceResponse.ProtoReflect.Descriptor instead.
func (*ProgrammedWorkoutServiceResponse) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP(), []int{1}
}

func (x *ProgrammedWorkoutServiceResponse) GetErrorOrSuccess() isProgrammedWorkoutServiceResponse_ErrorOrSuccess {
	if x != nil {
		return x.ErrorOrSuccess
	}
	return nil
}

func (x *ProgrammedWorkoutServiceResponse) GetSuccess() bool {
	if x != nil {
		if x, ok := x.ErrorOrSuccess.(*ProgrammedWorkoutServiceResponse_Success); ok {
			return x.Success
		}
	}
	return false
}

func (x *ProgrammedWorkoutServiceResponse) GetProgrammedSessionError() *ProgrammedWorkoutSessionError {
	if x != nil {
		if x, ok := x.ErrorOrSuccess.(*ProgrammedWorkoutServiceResponse_ProgrammedSessionError); ok {
			return x.ProgrammedSessionError
		}
	}
	return nil
}

func (x *ProgrammedWorkoutServiceResponse) GetWorkoutError() *WorkoutError {
	if x != nil {
		if x, ok := x.ErrorOrSuccess.(*ProgrammedWorkoutServiceResponse_WorkoutError); ok {
			return x.WorkoutError
		}
	}
	return nil
}

func (x *ProgrammedWorkoutServiceResponse) GetNetworkError() *NetworkError {
	if x != nil {
		if x, ok := x.ErrorOrSuccess.(*ProgrammedWorkoutServiceResponse_NetworkError); ok {
			return x.NetworkError
		}
	}
	return nil
}

type isProgrammedWorkoutServiceResponse_ErrorOrSuccess interface {
	isProgrammedWorkoutServiceResponse_ErrorOrSuccess()
}

type ProgrammedWorkoutServiceResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3,oneof"`
}

type ProgrammedWorkoutServiceResponse_ProgrammedSessionError struct {
	ProgrammedSessionError *ProgrammedWorkoutSessionError `protobuf:"bytes,2,opt,name=programmedSessionError,proto3,oneof"`
}

type ProgrammedWorkoutServiceResponse_WorkoutError struct {
	WorkoutError *WorkoutError `protobuf:"bytes,3,opt,name=workoutError,proto3,oneof"`
}

type ProgrammedWorkoutServiceResponse_NetworkError struct {
	NetworkError *NetworkError `protobuf:"bytes,4,opt,name=networkError,proto3,oneof"`
}

func (*ProgrammedWorkoutServiceResponse_Success) isProgrammedWorkoutServiceResponse_ErrorOrSuccess() {
}

func (*ProgrammedWorkoutServiceResponse_ProgrammedSessionError) isProgrammedWorkoutServiceResponse_ErrorOrSuccess() {
}

func (*ProgrammedWorkoutServiceResponse_WorkoutError) isProgrammedWorkoutServiceResponse_ErrorOrSuccess() {
}

func (*ProgrammedWorkoutServiceResponse_NetworkError) isProgrammedWorkoutServiceResponse_ErrorOrSuccess() {
}

type ProgramAtPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Position:
	//
	//	*ProgramAtPosition_Seconds
	//	*ProgramAtPosition_Meters
	//	*ProgramAtPosition_Calories
	Position      isProgramAtPosition_Position `protobuf_oneof:"position"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramAtPosition) Reset() {
	*x = ProgramAtPosition{}
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramAtPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramAtPosition) ProtoMessage() {}

func (x *ProgramAtPosition) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramAtPosition.ProtoReflect.Descriptor instead.
func (*ProgramAtPosition) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP(), []int{2}
}

func (x *ProgramAtPosition) GetPosition() isProgramAtPosition_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ProgramAtPosition) GetSeconds() float64 {
	if x != nil {
		if x, ok := x.Position.(*ProgramAtPosition_Seconds); ok {
			return x.Seconds
		}
	}
	return 0
}

func (x *ProgramAtPosition) GetMeters() float64 {
	if x != nil {
		if x, ok := x.Position.(*ProgramAtPosition_Meters); ok {
			return x.Meters
		}
	}
	return 0
}

func (x *ProgramAtPosition) GetCalories() float64 {
	if x != nil {
		if x, ok := x.Position.(*ProgramAtPosition_Calories); ok {
			return x.Calories
		}
	}
	return 0
}

type isProgramAtPosition_Position interface {
	isProgramAtPosition_Position()
}

type ProgramAtPosition_Seconds struct {
	Seconds float64 `protobuf:"fixed64,1,opt,name=seconds,proto3,oneof"`
}

type ProgramAtPosition_Meters struct {
	Meters float64 `protobuf:"fixed64,2,opt,name=meters,proto3,oneof"`
}

type ProgramAtPosition_Calories struct {
	Calories float64 `protobuf:"fixed64,3,opt,name=calories,proto3,oneof"`
}

func (*ProgramAtPosition_Seconds) isProgramAtPosition_Position() {}

func (*ProgramAtPosition_Meters) isProgramAtPosition_Position() {}

func (*ProgramAtPosition_Calories) isProgramAtPosition_Position() {}

type SetAtPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *ProgramAtPosition     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	WorkoutId     string                 `protobuf:"bytes,2,opt,name=workoutId,proto3" json:"workoutId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAtPositionRequest) Reset() {
	*x = SetAtPositionRequest{}
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAtPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAtPositionRequest) ProtoMessage() {}

func (x *SetAtPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAtPositionRequest.ProtoReflect.Descriptor instead.
func (*SetAtPositionRequest) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP(), []int{3}
}

func (x *SetAtPositionRequest) GetPosition() *ProgramAtPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SetAtPositionRequest) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

type ProgramPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    WorkoutTargetType      `protobuf:"varint,1,opt,name=targetType,proto3,enum=com.ifit.glassos.WorkoutTargetType" json:"targetType,omitempty"`
	At            float64                `protobuf:"fixed64,2,opt,name=at,proto3" json:"at,omitempty"`
	Elapsed       float64                `protobuf:"fixed64,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	WorkoutId     string                 `protobuf:"bytes,4,opt,name=workoutId,proto3" json:"workoutId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramPosition) Reset() {
	*x = ProgramPosition{}
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramPosition) ProtoMessage() {}

func (x *ProgramPosition) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramPosition.ProtoReflect.Descriptor instead.
func (*ProgramPosition) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP(), []int{4}
}

func (x *ProgramPosition) GetTargetType() WorkoutTargetType {
	if x != nil {
		return x.TargetType
	}
	return WorkoutTargetType_WORKOUT_TARGET_TYPE_UNKNOWN
}

func (x *ProgramPosition) GetAt() float64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *ProgramPosition) GetElapsed() float64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *ProgramPosition) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

type RecoveredSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecoveredSession *RecoveredSession      `protobuf:"bytes,1,opt,name=recoveredSession,proto3,oneof" json:"recoveredSession,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoveredSessionResponse) Reset() {
	*x = RecoveredSessionResponse{}
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveredSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveredSessionResponse) ProtoMessage() {}

func (x *RecoveredSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveredSessionResponse.ProtoReflect.Descriptor instead.
func (*RecoveredSessionResponse) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP(), []int{5}
}

func (x *RecoveredSessionResponse) GetRecoveredSession() *RecoveredSession {
	if x != nil {
		return x.RecoveredSession
	}
	return nil
}

var File_workout_ProgrammedWorkoutSessionService_proto protoreflect.FileDescriptor

const file_workout_ProgrammedWorkoutSessionService_proto_rawDesc = "" +
	"\n" +
	"-workout/ProgrammedWorkoutSessionService.proto\x12\x10com.ifit.glassos\x1a\x17util/NetworkError.proto\x1a\x0futil/Util.proto\x1a+workout/ProgrammedWorkoutSessionError.proto\x1a\x1aworkout/WorkoutError.proto\x1a\x1aworkout/WorkoutState.proto\x1a\x1aworkout/data/Workout.proto\x1a+workout/data/WorkoutSegmentDescriptor.proto\x1a%workout/data/WorkoutSessionItem.proto\x1a&workout/data/WorkoutSessionState.proto\x1a$workout/data/WorkoutTargetType.proto\x1a,workout/data/recovery/RecoveredSession.proto\"t\n" +
	"\x1cAddAllWorkoutSegmentsRequest\x12T\n" +
	"\x0fworkoutSegments\x18\x01 \x03(\v2*.com.ifit.glassos.WorkoutSegmentDescriptorR\x0fworkoutSegments\"\xc7\x02\n" +
	" ProgrammedWorkoutServiceResponse\x12\x1a\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x12i\n" +
	"\x16programmedSessionError\x18\x02 \x01(\v2/.com.ifit.glassos.ProgrammedWorkoutSessionErrorH\x00R\x16programmedSessionError\x12D\n" +
	"\fworkoutError\x18\x03 \x01(\v2\x1e.com.ifit.glassos.WorkoutErrorH\x00R\fworkoutError\x12D\n" +
	"\fnetworkError\x18\x04 \x01(\v2\x1e.com.ifit.glassos.NetworkErrorH\x00R\fnetworkErrorB\x10\n" +
	"\x0eerrorOrSuccess\"s\n" +
	"\x11ProgramAtPosition\x12\x1a\n" +
	"\aseconds\x18\x01 \x01(\x01H\x00R\aseconds\x12\x18\n" +
	"\x06meters\x18\x02 \x01(\x01H\x00R\x06meters\x12\x1c\n" +
	"\bcalories\x18\x03 \x01(\x01H\x00R\bcaloriesB\n" +
	"\n" +
	"\bposition\"u\n" +
	"\x14SetAtPositionRequest\x12?\n" +
	"\bposition\x18\x01 \x01(\v2#.com.ifit.glassos.ProgramAtPositionR\bposition\x12\x1c\n" +
	"\tworkoutId\x18\x02 \x01(\tR\tworkoutId\"\x9e\x01\n" +
	"\x0fProgramPosition\x12C\n" +
	"\n" +
	"targetType\x18\x01 \x01(\x0e2#.com.ifit.glassos.WorkoutTargetTypeR\n" +
	"targetType\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x01R\x02at\x12\x18\n" +
	"\aelapsed\x18\x03 \x01(\x01R\aelapsed\x12\x1c\n" +
	"\tworkoutId\x18\x04 \x01(\tR\tworkoutId\"\x84\x01\n" +
	"\x18RecoveredSessionResponse\x12S\n" +
	"\x10recoveredSession\x18\x01 \x01(\v2\".com.ifit.glassos.RecoveredSessionH\x00R\x10recoveredSession\x88\x01\x01B\x13\n" +
	"\x11_recoveredSession2\xe8\x14\n" +
	"\x1fProgrammedWorkoutSessionService\x12U\n" +
	"\x0ePreloadWorkout\x12*.com.ifit.glassos.WorkoutSegmentDescriptor\x1a\x17.com.ifit.glassos.Empty\x12`\n" +
	"$PreloadedWorkoutsChangedSubscription\x12\x17.com.ifit.glassos.Empty\x1a\x1d.com.ifit.glassos.WorkoutList0\x01\x12]\n" +
	"\x1dSessionIsStartingSubscription\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.BooleanResponse0\x01\x12`\n" +
	" ManualStartRequestedSubscription\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.BooleanResponse0\x01\x12q\n" +
	"\vAddAndStart\x12..com.ifit.glassos.AddAllWorkoutSegmentsRequest\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12{\n" +
	"\x15AddAllWorkoutSegments\x12..com.ifit.glassos.AddAllWorkoutSegmentsRequest\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12Q\n" +
	"\x1dClearRemainingWorkoutSegments\x12\x17.com.ifit.glassos.Empty\x1a\x17.com.ifit.glassos.Empty\x12T\n" +
	"\x05Start\x12\x17.com.ifit.glassos.Empty\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12S\n" +
	"\x04Stop\x12\x17.com.ifit.glassos.Empty\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12S\n" +
	"\x04Next\x12\x17.com.ifit.glassos.Empty\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12T\n" +
	"\x05Pause\x12\x17.com.ifit.glassos.Empty\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12U\n" +
	"\x06Resume\x12\x17.com.ifit.glassos.Empty\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12`\n" +
	"\x19GetCurrentSessionWorkouts\x12\x17.com.ifit.glassos.Empty\x1a(.com.ifit.glassos.WorkoutSessionItemList\"\x00\x12_\n" +
	"\x16SessionWorkoutsChanged\x12\x17.com.ifit.glassos.Empty\x1a(.com.ifit.glassos.WorkoutSessionItemList\"\x000\x01\x12a\n" +
	"\x1dGetCurrentWorkoutSessionState\x12\x17.com.ifit.glassos.Empty\x1a%.com.ifit.glassos.WorkoutSessionState\"\x00\x12`\n" +
	"\x1aWorkoutSessionStateChanged\x12\x17.com.ifit.glassos.Empty\x1a%.com.ifit.glassos.WorkoutSessionState\"\x000\x01\x12d\n" +
	"\x15AssertPositionControl\x12\x17.com.ifit.glassos.Empty\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12J\n" +
	"\x16ReleasePositionControl\x12\x17.com.ifit.glassos.Empty\x1a\x17.com.ifit.glassos.Empty\x12R\n" +
	"\x15GetPositionController\x12\x17.com.ifit.glassos.Empty\x1a .com.ifit.glassos.StringResponse\x12k\n" +
	"\rSetAtPosition\x12&.com.ifit.glassos.SetAtPositionRequest\x1a2.com.ifit.glassos.ProgrammedWorkoutServiceResponse\x12Y\n" +
	"\x19GetCurrentProgramPosition\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.ProgramPosition\"\x00\x12X\n" +
	"\x16ProgramPositionChanged\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.ProgramPosition\"\x000\x01\x12h\n" +
	"!GetLatestUnfinishedWorkoutSession\x12\x17.com.ifit.glassos.Empty\x1a*.com.ifit.glassos.RecoveredSessionResponse\x12[\n" +
	"\x1dHasUnfinishedSessionAvailable\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.BooleanResponse\x12S\n" +
	"\x14RunUnfinishedSession\x12\".com.ifit.glassos.RecoveredSession\x1a\x17.com.ifit.glassos.Empty\x12^\n" +
	"\x1fMarkUnfinishedSessionAsComplete\x12\".com.ifit.glassos.RecoveredSession\x1a\x17.com.ifit.glassos.Empty\x12K\n" +
	"\x17ClearUnfinishedSessions\x12\x17.com.ifit.glassos.Empty\x1a\x17.com.ifit.glassos.Empty\x12b\n" +
	"\x1bGetRunningUnfinishedSession\x12\x17.com.ifit.glassos.Empty\x1a*.com.ifit.glassos.RecoveredSessionResponseBI\n" +
	"\x18com.ifit.glassos.workoutB$ProgrammedWorkoutSessionServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_ProgrammedWorkoutSessionService_proto_rawDescOnce sync.Once
	file_workout_ProgrammedWorkoutSessionService_proto_rawDescData []byte
)

func file_workout_ProgrammedWorkoutSessionService_proto_rawDescGZIP() []byte {
	file_workout_ProgrammedWorkoutSessionService_proto_rawDescOnce.Do(func() {
		file_workout_ProgrammedWorkoutSessionService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_ProgrammedWorkoutSessionService_proto_rawDesc), len(file_workout_ProgrammedWorkoutSessionService_proto_rawDesc)))
	})
	return file_workout_ProgrammedWorkoutSessionService_proto_rawDescData
}

var file_workout_ProgrammedWorkoutSessionService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_workout_ProgrammedWorkoutSessionService_proto_goTypes = []any{
	(*AddAllWorkoutSegmentsRequest)(nil),     // 0: com.ifit.glassos.AddAllWorkoutSegmentsRequest
	(*ProgrammedWorkoutServiceResponse)(nil), // 1: com.ifit.glassos.ProgrammedWorkoutServiceResponse
	(*ProgramAtPosition)(nil),                // 2: com.ifit.glassos.ProgramAtPosition
	(*SetAtPositionRequest)(nil),             // 3: com.ifit.glassos.SetAtPositionRequest
	(*ProgramPosition)(nil),                  // 4: com.ifit.glassos.ProgramPosition
	(*RecoveredSessionResponse)(nil),         // 5: com.ifit.glassos.RecoveredSessionResponse
	(*WorkoutSegmentDescriptor)(nil),         // 6: com.ifit.glassos.WorkoutSegmentDescriptor
	(*ProgrammedWorkoutSessionError)(nil),    // 7: com.ifit.glassos.ProgrammedWorkoutSessionError
	(*WorkoutError)(nil),                     // 8: com.ifit.glassos.WorkoutError
	(*NetworkError)(nil),                     // 9: com.ifit.glassos.NetworkError
	(WorkoutTargetType)(0),                   // 10: com.ifit.glassos.WorkoutTargetType
	(*RecoveredSession)(nil),                 // 11: com.ifit.glassos.RecoveredSession
	(*Empty)(nil),                            // 12: com.ifit.glassos.Empty
	(*WorkoutList)(nil),                      // 13: com.ifit.glassos.WorkoutList
	(*BooleanResponse)(nil),                  // 14: com.ifit.glassos.BooleanResponse
	(*WorkoutSessionItemList)(nil),           // 15: com.ifit.glassos.WorkoutSessionItemList
	(*WorkoutSessionState)(nil),              // 16: com.ifit.glassos.WorkoutSessionState
	(*StringResponse)(nil),                   // 17: com.ifit.glassos.StringResponse
}
var file_workout_ProgrammedWorkoutSessionService_proto_depIdxs = []int32{
	6,  // 0: com.ifit.glassos.AddAllWorkoutSegmentsRequest.workoutSegments:type_name -> com.ifit.glassos.WorkoutSegmentDescriptor
	7,  // 1: com.ifit.glassos.ProgrammedWorkoutServiceResponse.programmedSessionError:type_name -> com.ifit.glassos.ProgrammedWorkoutSessionError
	8,  // 2: com.ifit.glassos.ProgrammedWorkoutServiceResponse.workoutError:type_name -> com.ifit.glassos.WorkoutError
	9,  // 3: com.ifit.glassos.ProgrammedWorkoutServiceResponse.networkError:type_name -> com.ifit.glassos.NetworkError
	2,  // 4: com.ifit.glassos.SetAtPositionRequest.position:type_name -> com.ifit.glassos.ProgramAtPosition
	10, // 5: com.ifit.glassos.ProgramPosition.targetType:type_name -> com.ifit.glassos.WorkoutTargetType
	11, // 6: com.ifit.glassos.RecoveredSessionResponse.recoveredSession:type_name -> com.ifit.glassos.RecoveredSession
	6,  // 7: com.ifit.glassos.ProgrammedWorkoutSessionService.PreloadWorkout:input_type -> com.ifit.glassos.WorkoutSegmentDescriptor
	12, // 8: com.ifit.glassos.ProgrammedWorkoutSessionService.PreloadedWorkoutsChangedSubscription:input_type -> com.ifit.glassos.Empty
	12, // 9: com.ifit.glassos.ProgrammedWorkoutSessionService.SessionIsStartingSubscription:input_type -> com.ifit.glassos.Empty
	12, // 10: com.ifit.glassos.ProgrammedWorkoutSessionService.ManualStartRequestedSubscription:input_type -> com.ifit.glassos.Empty
	0,  // 11: com.ifit.glassos.ProgrammedWorkoutSessionService.AddAndStart:input_type -> com.ifit.glassos.AddAllWorkoutSegmentsRequest
	0,  // 12: com.ifit.glassos.ProgrammedWorkoutSessionService.AddAllWorkoutSegments:input_type -> com.ifit.glassos.AddAllWorkoutSegmentsRequest
	12, // 13: com.ifit.glassos.ProgrammedWorkoutSessionService.ClearRemainingWorkoutSegments:input_type -> com.ifit.glassos.Empty
	12, // 14: com.ifit.glassos.ProgrammedWorkoutSessionService.Start:input_type -> com.ifit.glassos.Empty
	12, // 15: com.ifit.glassos.ProgrammedWorkoutSessionService.Stop:input_type -> com.ifit.glassos.Empty
	12, // 16: com.ifit.glassos.ProgrammedWorkoutSessionService.Next:input_type -> com.ifit.glassos.Empty
	12, // 17: com.ifit.glassos.ProgrammedWorkoutSessionService.Pause:input_type -> com.ifit.glassos.Empty
	12, // 18: com.ifit.glassos.ProgrammedWorkoutSessionService.Resume:input_type -> com.ifit.glassos.Empty
	12, // 19: com.ifit.glassos.ProgrammedWorkoutSessionService.GetCurrentSessionWorkouts:input_type -> com.ifit.glassos.Empty
	12, // 20: com.ifit.glassos.ProgrammedWorkoutSessionService.SessionWorkoutsChanged:input_type -> com.ifit.glassos.Empty
	12, // 21: com.ifit.glassos.ProgrammedWorkoutSessionService.GetCurrentWorkoutSessionState:input_type -> com.ifit.glassos.Empty
	12, // 22: com.ifit.glassos.ProgrammedWorkoutSessionService.WorkoutSessionStateChanged:input_type -> com.ifit.glassos.Empty
	12, // 23: com.ifit.glassos.ProgrammedWorkoutSessionService.AssertPositionControl:input_type -> com.ifit.glassos.Empty
	12, // 24: com.ifit.glassos.ProgrammedWorkoutSessionService.ReleasePositionControl:input_type -> com.ifit.glassos.Empty
	12, // 25: com.ifit.glassos.ProgrammedWorkoutSessionService.GetPositionController:input_type -> com.ifit.glassos.Empty
	3,  // 26: com.ifit.glassos.ProgrammedWorkoutSessionService.SetAtPosition:input_type -> com.ifit.glassos.SetAtPositionRequest
	12, // 27: com.ifit.glassos.ProgrammedWorkoutSessionService.GetCurrentProgramPosition:input_type -> com.ifit.glassos.Empty
	12, // 28: com.ifit.glassos.ProgrammedWorkoutSessionService.ProgramPositionChanged:input_type -> com.ifit.glassos.Empty
	12, // 29: com.ifit.glassos.ProgrammedWorkoutSessionService.GetLatestUnfinishedWorkoutSession:input_type -> com.ifit.glassos.Empty
	12, // 30: com.ifit.glassos.ProgrammedWorkoutSessionService.HasUnfinishedSessionAvailable:input_type -> com.ifit.glassos.Empty
	11, // 31: com.ifit.glassos.ProgrammedWorkoutSessionService.RunUnfinishedSession:input_type -> com.ifit.glassos.RecoveredSession
	11, // 32: com.ifit.glassos.ProgrammedWorkoutSessionService.MarkUnfinishedSessionAsComplete:input_type -> com.ifit.glassos.RecoveredSession
	12, // 33: com.ifit.glassos.ProgrammedWorkoutSessionService.ClearUnfinishedSessions:input_type -> com.ifit.glassos.Empty
	12, // 34: com.ifit.glassos.ProgrammedWorkoutSessionService.GetRunningUnfinishedSession:input_type -> com.ifit.glassos.Empty
	12, // 35: com.ifit.glassos.ProgrammedWorkoutSessionService.PreloadWorkout:output_type -> com.ifit.glassos.Empty
	13, // 36: com.ifit.glassos.ProgrammedWorkoutSessionService.PreloadedWorkoutsChangedSubscription:output_type -> com.ifit.glassos.WorkoutList
	14, // 37: com.ifit.glassos.ProgrammedWorkoutSessionService.SessionIsStartingSubscription:output_type -> com.ifit.glassos.BooleanResponse
	14, // 38: com.ifit.glassos.ProgrammedWorkoutSessionService.ManualStartRequestedSubscription:output_type -> com.ifit.glassos.BooleanResponse
	1,  // 39: com.ifit.glassos.ProgrammedWorkoutSessionService.AddAndStart:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	1,  // 40: com.ifit.glassos.ProgrammedWorkoutSessionService.AddAllWorkoutSegments:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	12, // 41: com.ifit.glassos.ProgrammedWorkoutSessionService.ClearRemainingWorkoutSegments:output_type -> com.ifit.glassos.Empty
	1,  // 42: com.ifit.glassos.ProgrammedWorkoutSessionService.Start:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	1,  // 43: com.ifit.glassos.ProgrammedWorkoutSessionService.Stop:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	1,  // 44: com.ifit.glassos.ProgrammedWorkoutSessionService.Next:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	1,  // 45: com.ifit.glassos.ProgrammedWorkoutSessionService.Pause:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	1,  // 46: com.ifit.glassos.ProgrammedWorkoutSessionService.Resume:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	15, // 47: com.ifit.glassos.ProgrammedWorkoutSessionService.GetCurrentSessionWorkouts:output_type -> com.ifit.glassos.WorkoutSessionItemList
	15, // 48: com.ifit.glassos.ProgrammedWorkoutSessionService.SessionWorkoutsChanged:output_type -> com.ifit.glassos.WorkoutSessionItemList
	16, // 49: com.ifit.glassos.ProgrammedWorkoutSessionService.GetCurrentWorkoutSessionState:output_type -> com.ifit.glassos.WorkoutSessionState
	16, // 50: com.ifit.glassos.ProgrammedWorkoutSessionService.WorkoutSessionStateChanged:output_type -> com.ifit.glassos.WorkoutSessionState
	1,  // 51: com.ifit.glassos.ProgrammedWorkoutSessionService.AssertPositionControl:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	12, // 52: com.ifit.glassos.ProgrammedWorkoutSessionService.ReleasePositionControl:output_type -> com.ifit.glassos.Empty
	17, // 53: com.ifit.glassos.ProgrammedWorkoutSessionService.GetPositionController:output_type -> com.ifit.glassos.StringResponse
	1,  // 54: com.ifit.glassos.ProgrammedWorkoutSessionService.SetAtPosition:output_type -> com.ifit.glassos.ProgrammedWorkoutServiceResponse
	4,  // 55: com.ifit.glassos.ProgrammedWorkoutSessionService.GetCurrentProgramPosition:output_type -> com.ifit.glassos.ProgramPosition
	4,  // 56: com.ifit.glassos.ProgrammedWorkoutSessionService.ProgramPositionChanged:output_type -> com.ifit.glassos.ProgramPosition
	5,  // 57: com.ifit.glassos.ProgrammedWorkoutSessionService.GetLatestUnfinishedWorkoutSession:output_type -> com.ifit.glassos.RecoveredSessionResponse
	14, // 58: com.ifit.glassos.ProgrammedWorkoutSessionService.HasUnfinishedSessionAvailable:output_type -> com.ifit.glassos.BooleanResponse
	12, // 59: com.ifit.glassos.ProgrammedWorkoutSessionService.RunUnfinishedSession:output_type -> com.ifit.glassos.Empty
	12, // 60: com.ifit.glassos.ProgrammedWorkoutSessionService.MarkUnfinishedSessionAsComplete:output_type -> com.ifit.glassos.Empty
	12, // 61: com.ifit.glassos.ProgrammedWorkoutSessionService.ClearUnfinishedSessions:output_type -> com.ifit.glassos.Empty
	5,  // 62: com.ifit.glassos.ProgrammedWorkoutSessionService.GetRunningUnfinishedSession:output_type -> com.ifit.glassos.RecoveredSessionResponse
	35, // [35:63] is the sub-list for method output_type
	7,  // [7:35] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_workout_ProgrammedWorkoutSessionService_proto_init() }
func file_workout_ProgrammedWorkoutSessionService_proto_init() {
	if File_workout_ProgrammedWorkoutSessionService_proto != nil {
		return
	}
	file_util_NetworkError_proto_init()
	file_util_Util_proto_init()
	file_workout_ProgrammedWorkoutSessionError_proto_init()
	file_workout_WorkoutError_proto_init()
	file_workout_WorkoutState_proto_init()
	file_workout_data_Workout_proto_init()
	file_workout_data_WorkoutSegmentDescriptor_proto_init()
	file_workout_data_WorkoutSessionItem_proto_init()
	file_workout_data_WorkoutSessionState_proto_init()
	file_workout_data_WorkoutTargetType_proto_init()
	file_workout_data_recovery_RecoveredSession_proto_init()
	file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[1].OneofWrappers = []any{
		(*ProgrammedWorkoutServiceResponse_Success)(nil),
		(*ProgrammedWorkoutServiceResponse_ProgrammedSessionError)(nil),
		(*ProgrammedWorkoutServiceResponse_WorkoutError)(nil),
		(*ProgrammedWorkoutServiceResponse_NetworkError)(nil),
	}
	file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[2].OneofWrappers = []any{
		(*ProgramAtPosition_Seconds)(nil),
		(*ProgramAtPosition_Meters)(nil),
		(*ProgramAtPosition_Calories)(nil),
	}
	file_workout_ProgrammedWorkoutSessionService_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_ProgrammedWorkoutSessionService_proto_rawDesc), len(file_workout_ProgrammedWorkoutSessionService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_ProgrammedWorkoutSessionService_proto_goTypes,
		DependencyIndexes: file_workout_ProgrammedWorkoutSessionService_proto_depIdxs,
		MessageInfos:      file_workout_ProgrammedWorkoutSessionService_proto_msgTypes,
	}.Build()
	File_workout_ProgrammedWorkoutSessionService_proto = out.File
	file_workout_ProgrammedWorkoutSessionService_proto_goTypes = nil
	file_workout_ProgrammedWorkoutSessionService_proto_depIdxs = nil
}
