// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/ProgrammedWorkoutSessionError.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProgrammedWorkoutSessionErrorCode int32

const (
	ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_UNKNOWN_ERROR          ProgrammedWorkoutSessionErrorCode = 0
	ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_MISSING_ERROR          ProgrammedWorkoutSessionErrorCode = 1
	ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_NOT_RUNNING_ERROR      ProgrammedWorkoutSessionErrorCode = 2
	ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_RUNNING_ERROR          ProgrammedWorkoutSessionErrorCode = 3
	ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_UNEXPECTED_WORKOUT_ID  ProgrammedWorkoutSessionErrorCode = 4
	ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_UNEXPECTED_TARGET_TYPE ProgrammedWorkoutSessionErrorCode = 5
)

// Enum value maps for ProgrammedWorkoutSessionErrorCode.
var (
	ProgrammedWorkoutSessionErrorCode_name = map[int32]string{
		0: "PROGRAMMED_SESSION_UNKNOWN_ERROR",
		1: "PROGRAMMED_SESSION_MISSING_ERROR",
		2: "PROGRAMMED_SESSION_NOT_RUNNING_ERROR",
		3: "PROGRAMMED_SESSION_RUNNING_ERROR",
		4: "PROGRAMMED_SESSION_UNEXPECTED_WORKOUT_ID",
		5: "PROGRAMMED_SESSION_UNEXPECTED_TARGET_TYPE",
	}
	ProgrammedWorkoutSessionErrorCode_value = map[string]int32{
		"PROGRAMMED_SESSION_UNKNOWN_ERROR":          0,
		"PROGRAMMED_SESSION_MISSING_ERROR":          1,
		"PROGRAMMED_SESSION_NOT_RUNNING_ERROR":      2,
		"PROGRAMMED_SESSION_RUNNING_ERROR":          3,
		"PROGRAMMED_SESSION_UNEXPECTED_WORKOUT_ID":  4,
		"PROGRAMMED_SESSION_UNEXPECTED_TARGET_TYPE": 5,
	}
)

func (x ProgrammedWorkoutSessionErrorCode) Enum() *ProgrammedWorkoutSessionErrorCode {
	p := new(ProgrammedWorkoutSessionErrorCode)
	*p = x
	return p
}

func (x ProgrammedWorkoutSessionErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgrammedWorkoutSessionErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_ProgrammedWorkoutSessionError_proto_enumTypes[0].Descriptor()
}

func (ProgrammedWorkoutSessionErrorCode) Type() protoreflect.EnumType {
	return &file_workout_ProgrammedWorkoutSessionError_proto_enumTypes[0]
}

func (x ProgrammedWorkoutSessionErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgrammedWorkoutSessionErrorCode.Descriptor instead.
func (ProgrammedWorkoutSessionErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionError_proto_rawDescGZIP(), []int{0}
}

type ProgrammedWorkoutSessionError struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ErrorCode     ProgrammedWorkoutSessionErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=com.ifit.glassos.ProgrammedWorkoutSessionErrorCode" json:"errorCode,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgrammedWorkoutSessionError) Reset() {
	*x = ProgrammedWorkoutSessionError{}
	mi := &file_workout_ProgrammedWorkoutSessionError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgrammedWorkoutSessionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgrammedWorkoutSessionError) ProtoMessage() {}

func (x *ProgrammedWorkoutSessionError) ProtoReflect() protoreflect.Message {
	mi := &file_workout_ProgrammedWorkoutSessionError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgrammedWorkoutSessionError.ProtoReflect.Descriptor instead.
func (*ProgrammedWorkoutSessionError) Descriptor() ([]byte, []int) {
	return file_workout_ProgrammedWorkoutSessionError_proto_rawDescGZIP(), []int{0}
}

func (x *ProgrammedWorkoutSessionError) GetErrorCode() ProgrammedWorkoutSessionErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ProgrammedWorkoutSessionErrorCode_PROGRAMMED_SESSION_UNKNOWN_ERROR
}

func (x *ProgrammedWorkoutSessionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workout_ProgrammedWorkoutSessionError_proto protoreflect.FileDescriptor

const file_workout_ProgrammedWorkoutSessionError_proto_rawDesc = "" +
	"\n" +
	"+workout/ProgrammedWorkoutSessionError.proto\x12\x10com.ifit.glassos\"\x8c\x01\n" +
	"\x1dProgrammedWorkoutSessionError\x12Q\n" +
	"\terrorCode\x18\x01 \x01(\x0e23.com.ifit.glassos.ProgrammedWorkoutSessionErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x9c\x02\n" +
	"!ProgrammedWorkoutSessionErrorCode\x12$\n" +
	" PROGRAMMED_SESSION_UNKNOWN_ERROR\x10\x00\x12$\n" +
	" PROGRAMMED_SESSION_MISSING_ERROR\x10\x01\x12(\n" +
	"$PROGRAMMED_SESSION_NOT_RUNNING_ERROR\x10\x02\x12$\n" +
	" PROGRAMMED_SESSION_RUNNING_ERROR\x10\x03\x12,\n" +
	"(PROGRAMMED_SESSION_UNEXPECTED_WORKOUT_ID\x10\x04\x12-\n" +
	")PROGRAMMED_SESSION_UNEXPECTED_TARGET_TYPE\x10\x05BH\n" +
	"\x18com.ifit.glassos.workoutB#ProgrammedWorkoutSessiontErrorProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_ProgrammedWorkoutSessionError_proto_rawDescOnce sync.Once
	file_workout_ProgrammedWorkoutSessionError_proto_rawDescData []byte
)

func file_workout_ProgrammedWorkoutSessionError_proto_rawDescGZIP() []byte {
	file_workout_ProgrammedWorkoutSessionError_proto_rawDescOnce.Do(func() {
		file_workout_ProgrammedWorkoutSessionError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_ProgrammedWorkoutSessionError_proto_rawDesc), len(file_workout_ProgrammedWorkoutSessionError_proto_rawDesc)))
	})
	return file_workout_ProgrammedWorkoutSessionError_proto_rawDescData
}

var file_workout_ProgrammedWorkoutSessionError_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_ProgrammedWorkoutSessionError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workout_ProgrammedWorkoutSessionError_proto_goTypes = []any{
	(ProgrammedWorkoutSessionErrorCode)(0), // 0: com.ifit.glassos.ProgrammedWorkoutSessionErrorCode
	(*ProgrammedWorkoutSessionError)(nil),  // 1: com.ifit.glassos.ProgrammedWorkoutSessionError
}
var file_workout_ProgrammedWorkoutSessionError_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.ProgrammedWorkoutSessionError.errorCode:type_name -> com.ifit.glassos.ProgrammedWorkoutSessionErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workout_ProgrammedWorkoutSessionError_proto_init() }
func file_workout_ProgrammedWorkoutSessionError_proto_init() {
	if File_workout_ProgrammedWorkoutSessionError_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_ProgrammedWorkoutSessionError_proto_rawDesc), len(file_workout_ProgrammedWorkoutSessionError_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_ProgrammedWorkoutSessionError_proto_goTypes,
		DependencyIndexes: file_workout_ProgrammedWorkoutSessionError_proto_depIdxs,
		EnumInfos:         file_workout_ProgrammedWorkoutSessionError_proto_enumTypes,
		MessageInfos:      file_workout_ProgrammedWorkoutSessionError_proto_msgTypes,
	}.Build()
	File_workout_ProgrammedWorkoutSessionError_proto = out.File
	file_workout_ProgrammedWorkoutSessionError_proto_goTypes = nil
	file_workout_ProgrammedWorkoutSessionError_proto_depIdxs = nil
}
