// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/video/Sources.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hls           *VideoSourceHls        `protobuf:"bytes,1,opt,name=hls,proto3" json:"hls,omitempty"`
	Fixed         []*VideoSourceStream   `protobuf:"bytes,2,rep,name=fixed,proto3" json:"fixed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sources) Reset() {
	*x = Sources{}
	mi := &file_workout_data_video_Sources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sources) ProtoMessage() {}

func (x *Sources) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_video_Sources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sources.ProtoReflect.Descriptor instead.
func (*Sources) Descriptor() ([]byte, []int) {
	return file_workout_data_video_Sources_proto_rawDescGZIP(), []int{0}
}

func (x *Sources) GetHls() *VideoSourceHls {
	if x != nil {
		return x.Hls
	}
	return nil
}

func (x *Sources) GetFixed() []*VideoSourceStream {
	if x != nil {
		return x.Fixed
	}
	return nil
}

var File_workout_data_video_Sources_proto protoreflect.FileDescriptor

const file_workout_data_video_Sources_proto_rawDesc = "" +
	"\n" +
	" workout/data/video/Sources.proto\x12\x10com.ifit.glassos\x1a'workout/data/video/VideoSourceHls.proto\x1a*workout/data/video/VideoSourceStream.proto\"x\n" +
	"\aSources\x122\n" +
	"\x03hls\x18\x01 \x01(\v2 .com.ifit.glassos.VideoSourceHlsR\x03hls\x129\n" +
	"\x05fixed\x18\x02 \x03(\v2#.com.ifit.glassos.VideoSourceStreamR\x05fixedB<\n" +
	"#com.ifit.glassos.workout.data.videoB\fSourcesProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_video_Sources_proto_rawDescOnce sync.Once
	file_workout_data_video_Sources_proto_rawDescData []byte
)

func file_workout_data_video_Sources_proto_rawDescGZIP() []byte {
	file_workout_data_video_Sources_proto_rawDescOnce.Do(func() {
		file_workout_data_video_Sources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_video_Sources_proto_rawDesc), len(file_workout_data_video_Sources_proto_rawDesc)))
	})
	return file_workout_data_video_Sources_proto_rawDescData
}

var file_workout_data_video_Sources_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workout_data_video_Sources_proto_goTypes = []any{
	(*Sources)(nil),           // 0: com.ifit.glassos.Sources
	(*VideoSourceHls)(nil),    // 1: com.ifit.glassos.VideoSourceHls
	(*VideoSourceStream)(nil), // 2: com.ifit.glassos.VideoSourceStream
}
var file_workout_data_video_Sources_proto_depIdxs = []int32{
	1, // 0: com.ifit.glassos.Sources.hls:type_name -> com.ifit.glassos.VideoSourceHls
	2, // 1: com.ifit.glassos.Sources.fixed:type_name -> com.ifit.glassos.VideoSourceStream
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workout_data_video_Sources_proto_init() }
func file_workout_data_video_Sources_proto_init() {
	if File_workout_data_video_Sources_proto != nil {
		return
	}
	file_workout_data_video_VideoSourceHls_proto_init()
	file_workout_data_video_VideoSourceStream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_video_Sources_proto_rawDesc), len(file_workout_data_video_Sources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_video_Sources_proto_goTypes,
		DependencyIndexes: file_workout_data_video_Sources_proto_depIdxs,
		MessageInfos:      file_workout_data_video_Sources_proto_msgTypes,
	}.Build()
	File_workout_data_video_Sources_proto = out.File
	file_workout_data_video_Sources_proto_goTypes = nil
	file_workout_data_video_Sources_proto_depIdxs = nil
}
