// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/SpeedService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeedService_CanRead_FullMethodName                 = "/com.ifit.glassos.SpeedService/CanRead"
	SpeedService_CanWrite_FullMethodName                = "/com.ifit.glassos.SpeedService/CanWrite"
	SpeedService_GetSpeed_FullMethodName                = "/com.ifit.glassos.SpeedService/GetSpeed"
	SpeedService_SetSpeed_FullMethodName                = "/com.ifit.glassos.SpeedService/SetSpeed"
	SpeedService_SpeedSubscription_FullMethodName       = "/com.ifit.glassos.SpeedService/SpeedSubscription"
	SpeedService_GetSpeedHistory_FullMethodName         = "/com.ifit.glassos.SpeedService/GetSpeedHistory"
	SpeedService_FollowWorkout_FullMethodName           = "/com.ifit.glassos.SpeedService/FollowWorkout"
	SpeedService_StopFollowing_FullMethodName           = "/com.ifit.glassos.SpeedService/StopFollowing"
	SpeedService_GetIsFollowing_FullMethodName          = "/com.ifit.glassos.SpeedService/GetIsFollowing"
	SpeedService_IsFollowingSubscription_FullMethodName = "/com.ifit.glassos.SpeedService/IsFollowingSubscription"
	SpeedService_GetControls_FullMethodName             = "/com.ifit.glassos.SpeedService/GetControls"
	SpeedService_ControlsSubscription_FullMethodName    = "/com.ifit.glassos.SpeedService/ControlsSubscription"
)

// SpeedServiceClient is the client API for SpeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeedServiceClient interface {
	// check whether Speed is Readable and Writeable
	CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	CanWrite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// get the current Speed relative to the current workout
	GetSpeed(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SpeedMetric, error)
	// sets the Speed to the given value
	SetSpeed(ctx context.Context, in *SpeedRequest, opts ...grpc.CallOption) (*WorkoutResult, error)
	// subscribe to Speed updates relative to the current workout
	SpeedSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpeedMetric], error)
	// gets a list of all of the Speed changes for the given workout ID
	GetSpeedHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*SpeedMetricList, error)
	// follow the current workout
	FollowWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error)
	// stop following the current workout
	StopFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// check whether the current workout is being followed
	GetIsFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BooleanResponse, error)
	// subscribe to following updates
	IsFollowingSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BooleanResponse], error)
	// get the current workout controls
	GetControls(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlList, error)
	// subscribe to workout control updates
	ControlsSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlList], error)
}

type speedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeedServiceClient(cc grpc.ClientConnInterface) SpeedServiceClient {
	return &speedServiceClient{cc}
}

func (c *speedServiceClient) CanRead(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, SpeedService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) CanWrite(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, SpeedService_CanWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) GetSpeed(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SpeedMetric, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeedMetric)
	err := c.cc.Invoke(ctx, SpeedService_GetSpeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) SetSpeed(ctx context.Context, in *SpeedRequest, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, SpeedService_SetSpeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) SpeedSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpeedMetric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpeedService_ServiceDesc.Streams[0], SpeedService_SpeedSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, SpeedMetric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeedService_SpeedSubscriptionClient = grpc.ServerStreamingClient[SpeedMetric]

func (c *speedServiceClient) GetSpeedHistory(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*SpeedMetricList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeedMetricList)
	err := c.cc.Invoke(ctx, SpeedService_GetSpeedHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) FollowWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, SpeedService_FollowWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) StopFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SpeedService_StopFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) GetIsFollowing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BooleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooleanResponse)
	err := c.cc.Invoke(ctx, SpeedService_GetIsFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) IsFollowingSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BooleanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpeedService_ServiceDesc.Streams[1], SpeedService_IsFollowingSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, BooleanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeedService_IsFollowingSubscriptionClient = grpc.ServerStreamingClient[BooleanResponse]

func (c *speedServiceClient) GetControls(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ControlList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlList)
	err := c.cc.Invoke(ctx, SpeedService_GetControls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *speedServiceClient) ControlsSubscription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpeedService_ServiceDesc.Streams[2], SpeedService_ControlsSubscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ControlList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeedService_ControlsSubscriptionClient = grpc.ServerStreamingClient[ControlList]

// SpeedServiceServer is the server API for SpeedService service.
// All implementations must embed UnimplementedSpeedServiceServer
// for forward compatibility.
type SpeedServiceServer interface {
	// check whether Speed is Readable and Writeable
	CanRead(context.Context, *Empty) (*AvailabilityResponse, error)
	CanWrite(context.Context, *Empty) (*AvailabilityResponse, error)
	// get the current Speed relative to the current workout
	GetSpeed(context.Context, *Empty) (*SpeedMetric, error)
	// sets the Speed to the given value
	SetSpeed(context.Context, *SpeedRequest) (*WorkoutResult, error)
	// subscribe to Speed updates relative to the current workout
	SpeedSubscription(*Empty, grpc.ServerStreamingServer[SpeedMetric]) error
	// gets a list of all of the Speed changes for the given workout ID
	GetSpeedHistory(context.Context, *WorkoutID) (*SpeedMetricList, error)
	// follow the current workout
	FollowWorkout(context.Context, *Empty) (*WorkoutResult, error)
	// stop following the current workout
	StopFollowing(context.Context, *Empty) (*Empty, error)
	// check whether the current workout is being followed
	GetIsFollowing(context.Context, *Empty) (*BooleanResponse, error)
	// subscribe to following updates
	IsFollowingSubscription(*Empty, grpc.ServerStreamingServer[BooleanResponse]) error
	// get the current workout controls
	GetControls(context.Context, *Empty) (*ControlList, error)
	// subscribe to workout control updates
	ControlsSubscription(*Empty, grpc.ServerStreamingServer[ControlList]) error
	mustEmbedUnimplementedSpeedServiceServer()
}

// UnimplementedSpeedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeedServiceServer struct{}

func (UnimplementedSpeedServiceServer) CanRead(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedSpeedServiceServer) CanWrite(context.Context, *Empty) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanWrite not implemented")
}
func (UnimplementedSpeedServiceServer) GetSpeed(context.Context, *Empty) (*SpeedMetric, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpeed not implemented")
}
func (UnimplementedSpeedServiceServer) SetSpeed(context.Context, *SpeedRequest) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSpeed not implemented")
}
func (UnimplementedSpeedServiceServer) SpeedSubscription(*Empty, grpc.ServerStreamingServer[SpeedMetric]) error {
	return status.Error(codes.Unimplemented, "method SpeedSubscription not implemented")
}
func (UnimplementedSpeedServiceServer) GetSpeedHistory(context.Context, *WorkoutID) (*SpeedMetricList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpeedHistory not implemented")
}
func (UnimplementedSpeedServiceServer) FollowWorkout(context.Context, *Empty) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowWorkout not implemented")
}
func (UnimplementedSpeedServiceServer) StopFollowing(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopFollowing not implemented")
}
func (UnimplementedSpeedServiceServer) GetIsFollowing(context.Context, *Empty) (*BooleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIsFollowing not implemented")
}
func (UnimplementedSpeedServiceServer) IsFollowingSubscription(*Empty, grpc.ServerStreamingServer[BooleanResponse]) error {
	return status.Error(codes.Unimplemented, "method IsFollowingSubscription not implemented")
}
func (UnimplementedSpeedServiceServer) GetControls(context.Context, *Empty) (*ControlList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetControls not implemented")
}
func (UnimplementedSpeedServiceServer) ControlsSubscription(*Empty, grpc.ServerStreamingServer[ControlList]) error {
	return status.Error(codes.Unimplemented, "method ControlsSubscription not implemented")
}
func (UnimplementedSpeedServiceServer) mustEmbedUnimplementedSpeedServiceServer() {}
func (UnimplementedSpeedServiceServer) testEmbeddedByValue()                      {}

// UnsafeSpeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeedServiceServer will
// result in compilation errors.
type UnsafeSpeedServiceServer interface {
	mustEmbedUnimplementedSpeedServiceServer()
}

func RegisterSpeedServiceServer(s grpc.ServiceRegistrar, srv SpeedServiceServer) {
	// If the following call panics, it indicates UnimplementedSpeedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeedService_ServiceDesc, srv)
}

func _SpeedService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).CanRead(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_CanWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).CanWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_CanWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).CanWrite(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_GetSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).GetSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_GetSpeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).GetSpeed(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_SetSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).SetSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_SetSpeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).SetSpeed(ctx, req.(*SpeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_SpeedSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpeedServiceServer).SpeedSubscription(m, &grpc.GenericServerStream[Empty, SpeedMetric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeedService_SpeedSubscriptionServer = grpc.ServerStreamingServer[SpeedMetric]

func _SpeedService_GetSpeedHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).GetSpeedHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_GetSpeedHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).GetSpeedHistory(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_FollowWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).FollowWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_FollowWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).FollowWorkout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_StopFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).StopFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_StopFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).StopFollowing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_GetIsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).GetIsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_GetIsFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).GetIsFollowing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_IsFollowingSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpeedServiceServer).IsFollowingSubscription(m, &grpc.GenericServerStream[Empty, BooleanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeedService_IsFollowingSubscriptionServer = grpc.ServerStreamingServer[BooleanResponse]

func _SpeedService_GetControls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeedServiceServer).GetControls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeedService_GetControls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeedServiceServer).GetControls(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpeedService_ControlsSubscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpeedServiceServer).ControlsSubscription(m, &grpc.GenericServerStream[Empty, ControlList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeedService_ControlsSubscriptionServer = grpc.ServerStreamingServer[ControlList]

// SpeedService_ServiceDesc is the grpc.ServiceDesc for SpeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.SpeedService",
	HandlerType: (*SpeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanRead",
			Handler:    _SpeedService_CanRead_Handler,
		},
		{
			MethodName: "CanWrite",
			Handler:    _SpeedService_CanWrite_Handler,
		},
		{
			MethodName: "GetSpeed",
			Handler:    _SpeedService_GetSpeed_Handler,
		},
		{
			MethodName: "SetSpeed",
			Handler:    _SpeedService_SetSpeed_Handler,
		},
		{
			MethodName: "GetSpeedHistory",
			Handler:    _SpeedService_GetSpeedHistory_Handler,
		},
		{
			MethodName: "FollowWorkout",
			Handler:    _SpeedService_FollowWorkout_Handler,
		},
		{
			MethodName: "StopFollowing",
			Handler:    _SpeedService_StopFollowing_Handler,
		},
		{
			MethodName: "GetIsFollowing",
			Handler:    _SpeedService_GetIsFollowing_Handler,
		},
		{
			MethodName: "GetControls",
			Handler:    _SpeedService_GetControls_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SpeedSubscription",
			Handler:       _SpeedService_SpeedSubscription_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IsFollowingSubscription",
			Handler:       _SpeedService_IsFollowingSubscription_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ControlsSubscription",
			Handler:       _SpeedService_ControlsSubscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/SpeedService.proto",
}
