// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/SpeedService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpeedMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutID     string                 `protobuf:"bytes,1,opt,name=workoutID,proto3" json:"workoutID,omitempty"`
	TimeSeconds   int32                  `protobuf:"varint,2,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	LastKph       float64                `protobuf:"fixed64,3,opt,name=lastKph,proto3" json:"lastKph,omitempty"`
	MaxKph        float64                `protobuf:"fixed64,4,opt,name=maxKph,proto3" json:"maxKph,omitempty"`
	AvgKph        float64                `protobuf:"fixed64,5,opt,name=avgKph,proto3" json:"avgKph,omitempty"`
	MinKph        float64                `protobuf:"fixed64,6,opt,name=minKph,proto3" json:"minKph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedMetric) Reset() {
	*x = SpeedMetric{}
	mi := &file_workout_SpeedService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedMetric) ProtoMessage() {}

func (x *SpeedMetric) ProtoReflect() protoreflect.Message {
	mi := &file_workout_SpeedService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedMetric.ProtoReflect.Descriptor instead.
func (*SpeedMetric) Descriptor() ([]byte, []int) {
	return file_workout_SpeedService_proto_rawDescGZIP(), []int{0}
}

func (x *SpeedMetric) GetWorkoutID() string {
	if x != nil {
		return x.WorkoutID
	}
	return ""
}

func (x *SpeedMetric) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *SpeedMetric) GetLastKph() float64 {
	if x != nil {
		return x.LastKph
	}
	return 0
}

func (x *SpeedMetric) GetMaxKph() float64 {
	if x != nil {
		return x.MaxKph
	}
	return 0
}

func (x *SpeedMetric) GetAvgKph() float64 {
	if x != nil {
		return x.AvgKph
	}
	return 0
}

func (x *SpeedMetric) GetMinKph() float64 {
	if x != nil {
		return x.MinKph
	}
	return 0
}

type SpeedMetricList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*SpeedMetric         `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedMetricList) Reset() {
	*x = SpeedMetricList{}
	mi := &file_workout_SpeedService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedMetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedMetricList) ProtoMessage() {}

func (x *SpeedMetricList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_SpeedService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedMetricList.ProtoReflect.Descriptor instead.
func (*SpeedMetricList) Descriptor() ([]byte, []int) {
	return file_workout_SpeedService_proto_rawDescGZIP(), []int{1}
}

func (x *SpeedMetricList) GetMetrics() []*SpeedMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type SpeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kph           float64                `protobuf:"fixed64,1,opt,name=kph,proto3" json:"kph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedRequest) Reset() {
	*x = SpeedRequest{}
	mi := &file_workout_SpeedService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedRequest) ProtoMessage() {}

func (x *SpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_SpeedService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedRequest.ProtoReflect.Descriptor instead.
func (*SpeedRequest) Descriptor() ([]byte, []int) {
	return file_workout_SpeedService_proto_rawDescGZIP(), []int{2}
}

func (x *SpeedRequest) GetKph() float64 {
	if x != nil {
		return x.Kph
	}
	return 0
}

var File_workout_SpeedService_proto protoreflect.FileDescriptor

const file_workout_SpeedService_proto_rawDesc = "" +
	"\n" +
	"\x1aworkout/SpeedService.proto\x12\x10com.ifit.glassos\x1a\x0futil/Util.proto\x1a\x1aworkout/data/Control.proto\x1a\x1bworkout/WorkoutResult.proto\"\xaf\x01\n" +
	"\vSpeedMetric\x12\x1c\n" +
	"\tworkoutID\x18\x01 \x01(\tR\tworkoutID\x12 \n" +
	"\vtimeSeconds\x18\x02 \x01(\x05R\vtimeSeconds\x12\x18\n" +
	"\alastKph\x18\x03 \x01(\x01R\alastKph\x12\x16\n" +
	"\x06maxKph\x18\x04 \x01(\x01R\x06maxKph\x12\x16\n" +
	"\x06avgKph\x18\x05 \x01(\x01R\x06avgKph\x12\x16\n" +
	"\x06minKph\x18\x06 \x01(\x01R\x06minKph\"J\n" +
	"\x0fSpeedMetricList\x127\n" +
	"\ametrics\x18\x01 \x03(\v2\x1d.com.ifit.glassos.SpeedMetricR\ametrics\" \n" +
	"\fSpeedRequest\x12\x10\n" +
	"\x03kph\x18\x01 \x01(\x01R\x03kph2\xc0\a\n" +
	"\fSpeedService\x12L\n" +
	"\aCanRead\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12M\n" +
	"\bCanWrite\x12\x17.com.ifit.glassos.Empty\x1a&.com.ifit.glassos.AvailabilityResponse\"\x00\x12D\n" +
	"\bGetSpeed\x12\x17.com.ifit.glassos.Empty\x1a\x1d.com.ifit.glassos.SpeedMetric\"\x00\x12M\n" +
	"\bSetSpeed\x12\x1e.com.ifit.glassos.SpeedRequest\x1a\x1f.com.ifit.glassos.WorkoutResult\"\x00\x12O\n" +
	"\x11SpeedSubscription\x12\x17.com.ifit.glassos.Empty\x1a\x1d.com.ifit.glassos.SpeedMetric\"\x000\x01\x12S\n" +
	"\x0fGetSpeedHistory\x12\x1b.com.ifit.glassos.WorkoutID\x1a!.com.ifit.glassos.SpeedMetricList\"\x00\x12K\n" +
	"\rFollowWorkout\x12\x17.com.ifit.glassos.Empty\x1a\x1f.com.ifit.glassos.WorkoutResult\"\x00\x12C\n" +
	"\rStopFollowing\x12\x17.com.ifit.glassos.Empty\x1a\x17.com.ifit.glassos.Empty\"\x00\x12N\n" +
	"\x0eGetIsFollowing\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.BooleanResponse\"\x00\x12Y\n" +
	"\x17IsFollowingSubscription\x12\x17.com.ifit.glassos.Empty\x1a!.com.ifit.glassos.BooleanResponse\"\x000\x01\x12G\n" +
	"\vGetControls\x12\x17.com.ifit.glassos.Empty\x1a\x1d.com.ifit.glassos.ControlList\"\x00\x12R\n" +
	"\x14ControlsSubscription\x12\x17.com.ifit.glassos.Empty\x1a\x1d.com.ifit.glassos.ControlList\"\x000\x01B6\n" +
	"\x18com.ifit.glassos.workoutB\x11SpeedServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_SpeedService_proto_rawDescOnce sync.Once
	file_workout_SpeedService_proto_rawDescData []byte
)

func file_workout_SpeedService_proto_rawDescGZIP() []byte {
	file_workout_SpeedService_proto_rawDescOnce.Do(func() {
		file_workout_SpeedService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_SpeedService_proto_rawDesc), len(file_workout_SpeedService_proto_rawDesc)))
	})
	return file_workout_SpeedService_proto_rawDescData
}

var file_workout_SpeedService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workout_SpeedService_proto_goTypes = []any{
	(*SpeedMetric)(nil),          // 0: com.ifit.glassos.SpeedMetric
	(*SpeedMetricList)(nil),      // 1: com.ifit.glassos.SpeedMetricList
	(*SpeedRequest)(nil),         // 2: com.ifit.glassos.SpeedRequest
	(*Empty)(nil),                // 3: com.ifit.glassos.Empty
	(*WorkoutID)(nil),            // 4: com.ifit.glassos.WorkoutID
	(*AvailabilityResponse)(nil), // 5: com.ifit.glassos.AvailabilityResponse
	(*WorkoutResult)(nil),        // 6: com.ifit.glassos.WorkoutResult
	(*BooleanResponse)(nil),      // 7: com.ifit.glassos.BooleanResponse
	(*ControlList)(nil),          // 8: com.ifit.glassos.ControlList
}
var file_workout_SpeedService_proto_depIdxs = []int32{
	0,  // 0: com.ifit.glassos.SpeedMetricList.metrics:type_name -> com.ifit.glassos.SpeedMetric
	3,  // 1: com.ifit.glassos.SpeedService.CanRead:input_type -> com.ifit.glassos.Empty
	3,  // 2: com.ifit.glassos.SpeedService.CanWrite:input_type -> com.ifit.glassos.Empty
	3,  // 3: com.ifit.glassos.SpeedService.GetSpeed:input_type -> com.ifit.glassos.Empty
	2,  // 4: com.ifit.glassos.SpeedService.SetSpeed:input_type -> com.ifit.glassos.SpeedRequest
	3,  // 5: com.ifit.glassos.SpeedService.SpeedSubscription:input_type -> com.ifit.glassos.Empty
	4,  // 6: com.ifit.glassos.SpeedService.GetSpeedHistory:input_type -> com.ifit.glassos.WorkoutID
	3,  // 7: com.ifit.glassos.SpeedService.FollowWorkout:input_type -> com.ifit.glassos.Empty
	3,  // 8: com.ifit.glassos.SpeedService.StopFollowing:input_type -> com.ifit.glassos.Empty
	3,  // 9: com.ifit.glassos.SpeedService.GetIsFollowing:input_type -> com.ifit.glassos.Empty
	3,  // 10: com.ifit.glassos.SpeedService.IsFollowingSubscription:input_type -> com.ifit.glassos.Empty
	3,  // 11: com.ifit.glassos.SpeedService.GetControls:input_type -> com.ifit.glassos.Empty
	3,  // 12: com.ifit.glassos.SpeedService.ControlsSubscription:input_type -> com.ifit.glassos.Empty
	5,  // 13: com.ifit.glassos.SpeedService.CanRead:output_type -> com.ifit.glassos.AvailabilityResponse
	5,  // 14: com.ifit.glassos.SpeedService.CanWrite:output_type -> com.ifit.glassos.AvailabilityResponse
	0,  // 15: com.ifit.glassos.SpeedService.GetSpeed:output_type -> com.ifit.glassos.SpeedMetric
	6,  // 16: com.ifit.glassos.SpeedService.SetSpeed:output_type -> com.ifit.glassos.WorkoutResult
	0,  // 17: com.ifit.glassos.SpeedService.SpeedSubscription:output_type -> com.ifit.glassos.SpeedMetric
	1,  // 18: com.ifit.glassos.SpeedService.GetSpeedHistory:output_type -> com.ifit.glassos.SpeedMetricList
	6,  // 19: com.ifit.glassos.SpeedService.FollowWorkout:output_type -> com.ifit.glassos.WorkoutResult
	3,  // 20: com.ifit.glassos.SpeedService.StopFollowing:output_type -> com.ifit.glassos.Empty
	7,  // 21: com.ifit.glassos.SpeedService.GetIsFollowing:output_type -> com.ifit.glassos.BooleanResponse
	7,  // 22: com.ifit.glassos.SpeedService.IsFollowingSubscription:output_type -> com.ifit.glassos.BooleanResponse
	8,  // 23: com.ifit.glassos.SpeedService.GetControls:output_type -> com.ifit.glassos.ControlList
	8,  // 24: com.ifit.glassos.SpeedService.ControlsSubscription:output_type -> com.ifit.glassos.ControlList
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_workout_SpeedService_proto_init() }
func file_workout_SpeedService_proto_init() {
	if File_workout_SpeedService_proto != nil {
		return
	}
	file_util_Util_proto_init()
	file_workout_data_Control_proto_init()
	file_workout_WorkoutResult_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_SpeedService_proto_rawDesc), len(file_workout_SpeedService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_SpeedService_proto_goTypes,
		DependencyIndexes: file_workout_SpeedService_proto_depIdxs,
		MessageInfos:      file_workout_SpeedService_proto_msgTypes,
	}.Build()
	File_workout_SpeedService_proto = out.File
	file_workout_SpeedService_proto_goTypes = nil
	file_workout_SpeedService_proto_depIdxs = nil
}
