// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: settings/SystemUnitsService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemUnits int32

const (
	SystemUnits_SYSTEM_UNITS_UNKNOWN  SystemUnits = 0
	SystemUnits_SYSTEM_UNITS_METRIC   SystemUnits = 1
	SystemUnits_SYSTEM_UNITS_IMPERIAL SystemUnits = 2
)

// Enum value maps for SystemUnits.
var (
	SystemUnits_name = map[int32]string{
		0: "SYSTEM_UNITS_UNKNOWN",
		1: "SYSTEM_UNITS_METRIC",
		2: "SYSTEM_UNITS_IMPERIAL",
	}
	SystemUnits_value = map[string]int32{
		"SYSTEM_UNITS_UNKNOWN":  0,
		"SYSTEM_UNITS_METRIC":   1,
		"SYSTEM_UNITS_IMPERIAL": 2,
	}
)

func (x SystemUnits) Enum() *SystemUnits {
	p := new(SystemUnits)
	*p = x
	return p
}

func (x SystemUnits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemUnits) Descriptor() protoreflect.EnumDescriptor {
	return file_settings_SystemUnitsService_proto_enumTypes[0].Descriptor()
}

func (SystemUnits) Type() protoreflect.EnumType {
	return &file_settings_SystemUnitsService_proto_enumTypes[0]
}

func (x SystemUnits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemUnits.Descriptor instead.
func (SystemUnits) EnumDescriptor() ([]byte, []int) {
	return file_settings_SystemUnitsService_proto_rawDescGZIP(), []int{0}
}

var File_settings_SystemUnitsService_proto protoreflect.FileDescriptor

const file_settings_SystemUnitsService_proto_rawDesc = "" +
	"\n" +
	"!settings/SystemUnitsService.proto\x12\x10com.ifit.glassos*[\n" +
	"\vSystemUnits\x12\x18\n" +
	"\x14SYSTEM_UNITS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SYSTEM_UNITS_METRIC\x10\x01\x12\x19\n" +
	"\x15SYSTEM_UNITS_IMPERIAL\x10\x02B=\n" +
	"\x19com.ifit.glassos.settingsB\x17SystemUnitsServiceProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_settings_SystemUnitsService_proto_rawDescOnce sync.Once
	file_settings_SystemUnitsService_proto_rawDescData []byte
)

func file_settings_SystemUnitsService_proto_rawDescGZIP() []byte {
	file_settings_SystemUnitsService_proto_rawDescOnce.Do(func() {
		file_settings_SystemUnitsService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_SystemUnitsService_proto_rawDesc), len(file_settings_SystemUnitsService_proto_rawDesc)))
	})
	return file_settings_SystemUnitsService_proto_rawDescData
}

var file_settings_SystemUnitsService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_settings_SystemUnitsService_proto_goTypes = []any{
	(SystemUnits)(0), // 0: com.ifit.glassos.SystemUnits
}
var file_settings_SystemUnitsService_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settings_SystemUnitsService_proto_init() }
func file_settings_SystemUnitsService_proto_init() {
	if File_settings_SystemUnitsService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_SystemUnitsService_proto_rawDesc), len(file_settings_SystemUnitsService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_SystemUnitsService_proto_goTypes,
		DependencyIndexes: file_settings_SystemUnitsService_proto_depIdxs,
		EnumInfos:         file_settings_SystemUnitsService_proto_enumTypes,
	}.Build()
	File_settings_SystemUnitsService_proto = out.File
	file_settings_SystemUnitsService_proto_goTypes = nil
	file_settings_SystemUnitsService_proto_depIdxs = nil
}
