// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/video/VideoSourceHls.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoSourceHls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,opt,name=src,proto3,oneof" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSourceHls) Reset() {
	*x = VideoSourceHls{}
	mi := &file_workout_data_video_VideoSourceHls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSourceHls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSourceHls) ProtoMessage() {}

func (x *VideoSourceHls) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_video_VideoSourceHls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSourceHls.ProtoReflect.Descriptor instead.
func (*VideoSourceHls) Descriptor() ([]byte, []int) {
	return file_workout_data_video_VideoSourceHls_proto_rawDescGZIP(), []int{0}
}

func (x *VideoSourceHls) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

var File_workout_data_video_VideoSourceHls_proto protoreflect.FileDescriptor

const file_workout_data_video_VideoSourceHls_proto_rawDesc = "" +
	"\n" +
	"'workout/data/video/VideoSourceHls.proto\x12\x10com.ifit.glassos\"/\n" +
	"\x0eVideoSourceHls\x12\x15\n" +
	"\x03src\x18\x01 \x01(\tH\x00R\x03src\x88\x01\x01B\x06\n" +
	"\x04_srcBC\n" +
	"#com.ifit.glassos.workout.data.videoB\x13VideoSourceHlsProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_video_VideoSourceHls_proto_rawDescOnce sync.Once
	file_workout_data_video_VideoSourceHls_proto_rawDescData []byte
)

func file_workout_data_video_VideoSourceHls_proto_rawDescGZIP() []byte {
	file_workout_data_video_VideoSourceHls_proto_rawDescOnce.Do(func() {
		file_workout_data_video_VideoSourceHls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_video_VideoSourceHls_proto_rawDesc), len(file_workout_data_video_VideoSourceHls_proto_rawDesc)))
	})
	return file_workout_data_video_VideoSourceHls_proto_rawDescData
}

var file_workout_data_video_VideoSourceHls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workout_data_video_VideoSourceHls_proto_goTypes = []any{
	(*VideoSourceHls)(nil), // 0: com.ifit.glassos.VideoSourceHls
}
var file_workout_data_video_VideoSourceHls_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_video_VideoSourceHls_proto_init() }
func file_workout_data_video_VideoSourceHls_proto_init() {
	if File_workout_data_video_VideoSourceHls_proto != nil {
		return
	}
	file_workout_data_video_VideoSourceHls_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_video_VideoSourceHls_proto_rawDesc), len(file_workout_data_video_VideoSourceHls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_video_VideoSourceHls_proto_goTypes,
		DependencyIndexes: file_workout_data_video_VideoSourceHls_proto_depIdxs,
		MessageInfos:      file_workout_data_video_VideoSourceHls_proto_msgTypes,
	}.Build()
	File_workout_data_video_VideoSourceHls_proto = out.File
	file_workout_data_video_VideoSourceHls_proto_goTypes = nil
	file_workout_data_video_VideoSourceHls_proto_depIdxs = nil
}
