// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: workout/WorkoutService.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkoutService_StartNewWorkout_FullMethodName       = "/com.ifit.glassos.WorkoutService/StartNewWorkout"
	WorkoutService_StartLoggedWorkout_FullMethodName    = "/com.ifit.glassos.WorkoutService/StartLoggedWorkout"
	WorkoutService_Pause_FullMethodName                 = "/com.ifit.glassos.WorkoutService/Pause"
	WorkoutService_Resume_FullMethodName                = "/com.ifit.glassos.WorkoutService/Resume"
	WorkoutService_Stop_FullMethodName                  = "/com.ifit.glassos.WorkoutService/Stop"
	WorkoutService_GetWorkoutState_FullMethodName       = "/com.ifit.glassos.WorkoutService/GetWorkoutState"
	WorkoutService_WorkoutStateChanged_FullMethodName   = "/com.ifit.glassos.WorkoutService/WorkoutStateChanged"
	WorkoutService_GetCurrentWorkout_FullMethodName     = "/com.ifit.glassos.WorkoutService/GetCurrentWorkout"
	WorkoutService_CurrentWorkoutChanged_FullMethodName = "/com.ifit.glassos.WorkoutService/CurrentWorkoutChanged"
	WorkoutService_GetWorkoutSource_FullMethodName      = "/com.ifit.glassos.WorkoutService/GetWorkoutSource"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	StartNewWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StartWorkoutResponse, error)
	StartLoggedWorkout(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*StartWorkoutResponse, error)
	Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error)
	Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error)
	GetWorkoutState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutStateMessage, error)
	WorkoutStateChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkoutStateMessage], error)
	GetCurrentWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutID, error)
	CurrentWorkoutChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkoutID], error)
	GetWorkoutSource(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutSourceMessage, error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) StartNewWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StartWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_StartNewWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) StartLoggedWorkout(ctx context.Context, in *WorkoutID, opts ...grpc.CallOption) (*StartWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_StartLoggedWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, WorkoutService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, WorkoutService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutResult)
	err := c.cc.Invoke(ctx, WorkoutService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkoutState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutStateMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutStateMessage)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkoutState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) WorkoutStateChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkoutStateMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkoutService_ServiceDesc.Streams[0], WorkoutService_WorkoutStateChanged_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, WorkoutStateMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkoutService_WorkoutStateChangedClient = grpc.ServerStreamingClient[WorkoutStateMessage]

func (c *workoutServiceClient) GetCurrentWorkout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutID)
	err := c.cc.Invoke(ctx, WorkoutService_GetCurrentWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) CurrentWorkoutChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkoutID], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkoutService_ServiceDesc.Streams[1], WorkoutService_CurrentWorkoutChanged_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, WorkoutID]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkoutService_CurrentWorkoutChangedClient = grpc.ServerStreamingClient[WorkoutID]

func (c *workoutServiceClient) GetWorkoutSource(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkoutSourceMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutSourceMessage)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkoutSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	StartNewWorkout(context.Context, *Empty) (*StartWorkoutResponse, error)
	StartLoggedWorkout(context.Context, *WorkoutID) (*StartWorkoutResponse, error)
	Pause(context.Context, *Empty) (*WorkoutResult, error)
	Resume(context.Context, *Empty) (*WorkoutResult, error)
	Stop(context.Context, *Empty) (*WorkoutResult, error)
	GetWorkoutState(context.Context, *Empty) (*WorkoutStateMessage, error)
	WorkoutStateChanged(*Empty, grpc.ServerStreamingServer[WorkoutStateMessage]) error
	GetCurrentWorkout(context.Context, *Empty) (*WorkoutID, error)
	CurrentWorkoutChanged(*Empty, grpc.ServerStreamingServer[WorkoutID]) error
	GetWorkoutSource(context.Context, *Empty) (*WorkoutSourceMessage, error)
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) StartNewWorkout(context.Context, *Empty) (*StartWorkoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartNewWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) StartLoggedWorkout(context.Context, *WorkoutID) (*StartWorkoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLoggedWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) Pause(context.Context, *Empty) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedWorkoutServiceServer) Resume(context.Context, *Empty) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedWorkoutServiceServer) Stop(context.Context, *Empty) (*WorkoutResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkoutState(context.Context, *Empty) (*WorkoutStateMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkoutState not implemented")
}
func (UnimplementedWorkoutServiceServer) WorkoutStateChanged(*Empty, grpc.ServerStreamingServer[WorkoutStateMessage]) error {
	return status.Error(codes.Unimplemented, "method WorkoutStateChanged not implemented")
}
func (UnimplementedWorkoutServiceServer) GetCurrentWorkout(context.Context, *Empty) (*WorkoutID, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) CurrentWorkoutChanged(*Empty, grpc.ServerStreamingServer[WorkoutID]) error {
	return status.Error(codes.Unimplemented, "method CurrentWorkoutChanged not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkoutSource(context.Context, *Empty) (*WorkoutSourceMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkoutSource not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_StartNewWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).StartNewWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_StartNewWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).StartNewWorkout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_StartLoggedWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).StartLoggedWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_StartLoggedWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).StartLoggedWorkout(ctx, req.(*WorkoutID))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).Pause(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).Resume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkoutState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkoutState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkoutState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkoutState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_WorkoutStateChanged_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkoutServiceServer).WorkoutStateChanged(m, &grpc.GenericServerStream[Empty, WorkoutStateMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkoutService_WorkoutStateChangedServer = grpc.ServerStreamingServer[WorkoutStateMessage]

func _WorkoutService_GetCurrentWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetCurrentWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetCurrentWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetCurrentWorkout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_CurrentWorkoutChanged_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkoutServiceServer).CurrentWorkoutChanged(m, &grpc.GenericServerStream[Empty, WorkoutID]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkoutService_CurrentWorkoutChangedServer = grpc.ServerStreamingServer[WorkoutID]

func _WorkoutService_GetWorkoutSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkoutSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkoutSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkoutSource(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ifit.glassos.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartNewWorkout",
			Handler:    _WorkoutService_StartNewWorkout_Handler,
		},
		{
			MethodName: "StartLoggedWorkout",
			Handler:    _WorkoutService_StartLoggedWorkout_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _WorkoutService_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _WorkoutService_Resume_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _WorkoutService_Stop_Handler,
		},
		{
			MethodName: "GetWorkoutState",
			Handler:    _WorkoutService_GetWorkoutState_Handler,
		},
		{
			MethodName: "GetCurrentWorkout",
			Handler:    _WorkoutService_GetCurrentWorkout_Handler,
		},
		{
			MethodName: "GetWorkoutSource",
			Handler:    _WorkoutService_GetWorkoutSource_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkoutStateChanged",
			Handler:       _WorkoutService_WorkoutStateChanged_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CurrentWorkoutChanged",
			Handler:       _WorkoutService_CurrentWorkoutChanged_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/WorkoutService.proto",
}
