// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/WorkoutState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutState int32

const (
	WorkoutState_WORKOUT_STATE_UNKNOWN WorkoutState = 0
	WorkoutState_WORKOUT_STATE_IDLE    WorkoutState = 1
	WorkoutState_WORKOUT_STATE_DMK     WorkoutState = 2
	WorkoutState_WORKOUT_STATE_RUNNING WorkoutState = 3
	WorkoutState_WORKOUT_STATE_PAUSED  WorkoutState = 4
	WorkoutState_WORKOUT_STATE_RESULTS WorkoutState = 5
)

// Enum value maps for WorkoutState.
var (
	WorkoutState_name = map[int32]string{
		0: "WORKOUT_STATE_UNKNOWN",
		1: "WORKOUT_STATE_IDLE",
		2: "WORKOUT_STATE_DMK",
		3: "WORKOUT_STATE_RUNNING",
		4: "WORKOUT_STATE_PAUSED",
		5: "WORKOUT_STATE_RESULTS",
	}
	WorkoutState_value = map[string]int32{
		"WORKOUT_STATE_UNKNOWN": 0,
		"WORKOUT_STATE_IDLE":    1,
		"WORKOUT_STATE_DMK":     2,
		"WORKOUT_STATE_RUNNING": 3,
		"WORKOUT_STATE_PAUSED":  4,
		"WORKOUT_STATE_RESULTS": 5,
	}
)

func (x WorkoutState) Enum() *WorkoutState {
	p := new(WorkoutState)
	*p = x
	return p
}

func (x WorkoutState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutState) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_WorkoutState_proto_enumTypes[0].Descriptor()
}

func (WorkoutState) Type() protoreflect.EnumType {
	return &file_workout_WorkoutState_proto_enumTypes[0]
}

func (x WorkoutState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutState.Descriptor instead.
func (WorkoutState) EnumDescriptor() ([]byte, []int) {
	return file_workout_WorkoutState_proto_rawDescGZIP(), []int{0}
}

var File_workout_WorkoutState_proto protoreflect.FileDescriptor

const file_workout_WorkoutState_proto_rawDesc = "" +
	"\n" +
	"\x1aworkout/WorkoutState.proto\x12\x10com.ifit.glassos*\xa8\x01\n" +
	"\fWorkoutState\x12\x19\n" +
	"\x15WORKOUT_STATE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12WORKOUT_STATE_IDLE\x10\x01\x12\x15\n" +
	"\x11WORKOUT_STATE_DMK\x10\x02\x12\x19\n" +
	"\x15WORKOUT_STATE_RUNNING\x10\x03\x12\x18\n" +
	"\x14WORKOUT_STATE_PAUSED\x10\x04\x12\x19\n" +
	"\x15WORKOUT_STATE_RESULTS\x10\x05B6\n" +
	"\x18com.ifit.glassos.workoutB\x11WorkoutStateProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_WorkoutState_proto_rawDescOnce sync.Once
	file_workout_WorkoutState_proto_rawDescData []byte
)

func file_workout_WorkoutState_proto_rawDescGZIP() []byte {
	file_workout_WorkoutState_proto_rawDescOnce.Do(func() {
		file_workout_WorkoutState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_WorkoutState_proto_rawDesc), len(file_workout_WorkoutState_proto_rawDesc)))
	})
	return file_workout_WorkoutState_proto_rawDescData
}

var file_workout_WorkoutState_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_WorkoutState_proto_goTypes = []any{
	(WorkoutState)(0), // 0: com.ifit.glassos.WorkoutState
}
var file_workout_WorkoutState_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_WorkoutState_proto_init() }
func file_workout_WorkoutState_proto_init() {
	if File_workout_WorkoutState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_WorkoutState_proto_rawDesc), len(file_workout_WorkoutState_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_WorkoutState_proto_goTypes,
		DependencyIndexes: file_workout_WorkoutState_proto_depIdxs,
		EnumInfos:         file_workout_WorkoutState_proto_enumTypes,
	}.Build()
	File_workout_WorkoutState_proto = out.File
	file_workout_WorkoutState_proto_goTypes = nil
	file_workout_WorkoutState_proto_depIdxs = nil
}
