// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/Workout.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_workout_data_Workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{0}
}

func (x *StringList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type WorkoutFilterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []WorkoutFilter        `protobuf:"varint,1,rep,packed,name=items,proto3,enum=com.ifit.glassos.WorkoutFilter" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutFilterList) Reset() {
	*x = WorkoutFilterList{}
	mi := &file_workout_data_Workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutFilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutFilterList) ProtoMessage() {}

func (x *WorkoutFilterList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutFilterList.ProtoReflect.Descriptor instead.
func (*WorkoutFilterList) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{1}
}

func (x *WorkoutFilterList) GetItems() []WorkoutFilter {
	if x != nil {
		return x.Items
	}
	return nil
}

type MusicRegionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MusicRegion         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicRegionList) Reset() {
	*x = MusicRegionList{}
	mi := &file_workout_data_Workout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicRegionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicRegionList) ProtoMessage() {}

func (x *MusicRegionList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicRegionList.ProtoReflect.Descriptor instead.
func (*MusicRegionList) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{2}
}

func (x *MusicRegionList) GetItems() []*MusicRegion {
	if x != nil {
		return x.Items
	}
	return nil
}

type LibraryCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subcategories []string               `protobuf:"bytes,2,rep,name=subcategories,proto3" json:"subcategories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryCategory) Reset() {
	*x = LibraryCategory{}
	mi := &file_workout_data_Workout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryCategory) ProtoMessage() {}

func (x *LibraryCategory) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryCategory.ProtoReflect.Descriptor instead.
func (*LibraryCategory) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{3}
}

func (x *LibraryCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LibraryCategory) GetSubcategories() []string {
	if x != nil {
		return x.Subcategories
	}
	return nil
}

type LibraryCategoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LibraryCategory     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryCategoryList) Reset() {
	*x = LibraryCategoryList{}
	mi := &file_workout_data_Workout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryCategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryCategoryList) ProtoMessage() {}

func (x *LibraryCategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryCategoryList.ProtoReflect.Descriptor instead.
func (*LibraryCategoryList) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{4}
}

func (x *LibraryCategoryList) GetItems() []*LibraryCategory {
	if x != nil {
		return x.Items
	}
	return nil
}

type LibraryCategoryMap struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Items         map[string]*LibraryCategoryList `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryCategoryMap) Reset() {
	*x = LibraryCategoryMap{}
	mi := &file_workout_data_Workout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryCategoryMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryCategoryMap) ProtoMessage() {}

func (x *LibraryCategoryMap) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryCategoryMap.ProtoReflect.Descriptor instead.
func (*LibraryCategoryMap) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{5}
}

func (x *LibraryCategoryMap) GetItems() map[string]*LibraryCategoryList {
	if x != nil {
		return x.Items
	}
	return nil
}

type Workout struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Id                *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	HeroImageUrl      *string                `protobuf:"bytes,3,opt,name=heroImageUrl,proto3,oneof" json:"heroImageUrl,omitempty"`
	Categories        *StringList            `protobuf:"bytes,4,opt,name=categories,proto3,oneof" json:"categories,omitempty"`
	WorkoutFilters    *WorkoutFilterList     `protobuf:"bytes,5,opt,name=workoutFilters,proto3" json:"workoutFilters,omitempty"`
	Controls          *ControlList           `protobuf:"bytes,6,opt,name=controls,proto3" json:"controls,omitempty"`
	TargetType        WorkoutTargetType      `protobuf:"varint,7,opt,name=targetType,proto3,enum=com.ifit.glassos.WorkoutTargetType" json:"targetType,omitempty"`
	TargetValue       *float64               `protobuf:"fixed64,8,opt,name=targetValue,proto3,oneof" json:"targetValue,omitempty"`
	WorkoutType       WorkoutType            `protobuf:"varint,9,opt,name=workoutType,proto3,enum=com.ifit.glassos.WorkoutType" json:"workoutType,omitempty"`
	VideoMusicRegions *MusicRegionList       `protobuf:"bytes,10,opt,name=videoMusicRegions,proto3,oneof" json:"videoMusicRegions,omitempty"`
	Sources           *Sources               `protobuf:"bytes,11,opt,name=sources,proto3,oneof" json:"sources,omitempty"`
	LibraryFilters    *LibraryCategoryMap    `protobuf:"bytes,12,opt,name=libraryFilters,proto3,oneof" json:"libraryFilters,omitempty"`
	ScaledControls    *ScaledControls        `protobuf:"bytes,13,opt,name=scaledControls,proto3,oneof" json:"scaledControls,omitempty"`
	StartingLevel     *int32                 `protobuf:"varint,14,opt,name=startingLevel,proto3,oneof" json:"startingLevel,omitempty"`
	SkipWarmup        *bool                  `protobuf:"varint,15,opt,name=skipWarmup,proto3,oneof" json:"skipWarmup,omitempty"`
	MapCoordinates    *MapCoordinateList     `protobuf:"bytes,16,opt,name=mapCoordinates,proto3,oneof" json:"mapCoordinates,omitempty"`
	WorkoutDriverFQN  *string                `protobuf:"bytes,17,opt,name=workoutDriverFQN,proto3,oneof" json:"workoutDriverFQN,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Workout) Reset() {
	*x = Workout{}
	mi := &file_workout_data_Workout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workout) ProtoMessage() {}

func (x *Workout) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workout.ProtoReflect.Descriptor instead.
func (*Workout) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{6}
}

func (x *Workout) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Workout) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Workout) GetHeroImageUrl() string {
	if x != nil && x.HeroImageUrl != nil {
		return *x.HeroImageUrl
	}
	return ""
}

func (x *Workout) GetCategories() *StringList {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Workout) GetWorkoutFilters() *WorkoutFilterList {
	if x != nil {
		return x.WorkoutFilters
	}
	return nil
}

func (x *Workout) GetControls() *ControlList {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *Workout) GetTargetType() WorkoutTargetType {
	if x != nil {
		return x.TargetType
	}
	return WorkoutTargetType_WORKOUT_TARGET_TYPE_UNKNOWN
}

func (x *Workout) GetTargetValue() float64 {
	if x != nil && x.TargetValue != nil {
		return *x.TargetValue
	}
	return 0
}

func (x *Workout) GetWorkoutType() WorkoutType {
	if x != nil {
		return x.WorkoutType
	}
	return WorkoutType_WORKOUT_TYPE_UNKNOWN
}

func (x *Workout) GetVideoMusicRegions() *MusicRegionList {
	if x != nil {
		return x.VideoMusicRegions
	}
	return nil
}

func (x *Workout) GetSources() *Sources {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Workout) GetLibraryFilters() *LibraryCategoryMap {
	if x != nil {
		return x.LibraryFilters
	}
	return nil
}

func (x *Workout) GetScaledControls() *ScaledControls {
	if x != nil {
		return x.ScaledControls
	}
	return nil
}

func (x *Workout) GetStartingLevel() int32 {
	if x != nil && x.StartingLevel != nil {
		return *x.StartingLevel
	}
	return 0
}

func (x *Workout) GetSkipWarmup() bool {
	if x != nil && x.SkipWarmup != nil {
		return *x.SkipWarmup
	}
	return false
}

func (x *Workout) GetMapCoordinates() *MapCoordinateList {
	if x != nil {
		return x.MapCoordinates
	}
	return nil
}

func (x *Workout) GetWorkoutDriverFQN() string {
	if x != nil && x.WorkoutDriverFQN != nil {
		return *x.WorkoutDriverFQN
	}
	return ""
}

type WorkoutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Workout             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutList) Reset() {
	*x = WorkoutList{}
	mi := &file_workout_data_Workout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutList) ProtoMessage() {}

func (x *WorkoutList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_Workout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutList.ProtoReflect.Descriptor instead.
func (*WorkoutList) Descriptor() ([]byte, []int) {
	return file_workout_data_Workout_proto_rawDescGZIP(), []int{7}
}

func (x *WorkoutList) GetItems() []*Workout {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_workout_data_Workout_proto protoreflect.FileDescriptor

const file_workout_data_Workout_proto_rawDesc = "" +
	"\n" +
	"\x1aworkout/data/Workout.proto\x12\x10com.ifit.glassos\x1a\x1aworkout/data/Control.proto\x1a!workout/data/ScaledControls.proto\x1a\"workout/data/WorkoutCategory.proto\x1a workout/data/WorkoutFilter.proto\x1a$workout/data/WorkoutTargetType.proto\x1a\x1eworkout/data/WorkoutType.proto\x1a$workout/data/video/MusicRegion.proto\x1a workout/data/video/Sources.proto\x1a$workout/data/map/MapCoordinate.proto\"\"\n" +
	"\n" +
	"StringList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"J\n" +
	"\x11WorkoutFilterList\x125\n" +
	"\x05items\x18\x01 \x03(\x0e2\x1f.com.ifit.glassos.WorkoutFilterR\x05items\"F\n" +
	"\x0fMusicRegionList\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.com.ifit.glassos.MusicRegionR\x05items\"K\n" +
	"\x0fLibraryCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\rsubcategories\x18\x02 \x03(\tR\rsubcategories\"N\n" +
	"\x13LibraryCategoryList\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.com.ifit.glassos.LibraryCategoryR\x05items\"\xbc\x01\n" +
	"\x12LibraryCategoryMap\x12E\n" +
	"\x05items\x18\x01 \x03(\v2/.com.ifit.glassos.LibraryCategoryMap.ItemsEntryR\x05items\x1a_\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.com.ifit.glassos.LibraryCategoryListR\x05value:\x028\x01\"\xb1\t\n" +
	"\aWorkout\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01\x12'\n" +
	"\fheroImageUrl\x18\x03 \x01(\tH\x02R\fheroImageUrl\x88\x01\x01\x12A\n" +
	"\n" +
	"categories\x18\x04 \x01(\v2\x1c.com.ifit.glassos.StringListH\x03R\n" +
	"categories\x88\x01\x01\x12K\n" +
	"\x0eworkoutFilters\x18\x05 \x01(\v2#.com.ifit.glassos.WorkoutFilterListR\x0eworkoutFilters\x129\n" +
	"\bcontrols\x18\x06 \x01(\v2\x1d.com.ifit.glassos.ControlListR\bcontrols\x12C\n" +
	"\n" +
	"targetType\x18\a \x01(\x0e2#.com.ifit.glassos.WorkoutTargetTypeR\n" +
	"targetType\x12%\n" +
	"\vtargetValue\x18\b \x01(\x01H\x04R\vtargetValue\x88\x01\x01\x12?\n" +
	"\vworkoutType\x18\t \x01(\x0e2\x1d.com.ifit.glassos.WorkoutTypeR\vworkoutType\x12T\n" +
	"\x11videoMusicRegions\x18\n" +
	" \x01(\v2!.com.ifit.glassos.MusicRegionListH\x05R\x11videoMusicRegions\x88\x01\x01\x128\n" +
	"\asources\x18\v \x01(\v2\x19.com.ifit.glassos.SourcesH\x06R\asources\x88\x01\x01\x12Q\n" +
	"\x0elibraryFilters\x18\f \x01(\v2$.com.ifit.glassos.LibraryCategoryMapH\aR\x0elibraryFilters\x88\x01\x01\x12M\n" +
	"\x0escaledControls\x18\r \x01(\v2 .com.ifit.glassos.ScaledControlsH\bR\x0escaledControls\x88\x01\x01\x12)\n" +
	"\rstartingLevel\x18\x0e \x01(\x05H\tR\rstartingLevel\x88\x01\x01\x12#\n" +
	"\n" +
	"skipWarmup\x18\x0f \x01(\bH\n" +
	"R\n" +
	"skipWarmup\x88\x01\x01\x12P\n" +
	"\x0emapCoordinates\x18\x10 \x01(\v2#.com.ifit.glassos.MapCoordinateListH\vR\x0emapCoordinates\x88\x01\x01\x12/\n" +
	"\x10workoutDriverFQN\x18\x11 \x01(\tH\fR\x10workoutDriverFQN\x88\x01\x01B\b\n" +
	"\x06_titleB\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_heroImageUrlB\r\n" +
	"\v_categoriesB\x0e\n" +
	"\f_targetValueB\x14\n" +
	"\x12_videoMusicRegionsB\n" +
	"\n" +
	"\b_sourcesB\x11\n" +
	"\x0f_libraryFiltersB\x11\n" +
	"\x0f_scaledControlsB\x10\n" +
	"\x0e_startingLevelB\r\n" +
	"\v_skipWarmupB\x11\n" +
	"\x0f_mapCoordinatesB\x13\n" +
	"\x11_workoutDriverFQN\">\n" +
	"\vWorkoutList\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.com.ifit.glassos.WorkoutR\x05itemsB6\n" +
	"\x1dcom.ifit.glassos.workout.dataB\fWorkoutProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_Workout_proto_rawDescOnce sync.Once
	file_workout_data_Workout_proto_rawDescData []byte
)

func file_workout_data_Workout_proto_rawDescGZIP() []byte {
	file_workout_data_Workout_proto_rawDescOnce.Do(func() {
		file_workout_data_Workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_Workout_proto_rawDesc), len(file_workout_data_Workout_proto_rawDesc)))
	})
	return file_workout_data_Workout_proto_rawDescData
}

var file_workout_data_Workout_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_workout_data_Workout_proto_goTypes = []any{
	(*StringList)(nil),          // 0: com.ifit.glassos.StringList
	(*WorkoutFilterList)(nil),   // 1: com.ifit.glassos.WorkoutFilterList
	(*MusicRegionList)(nil),     // 2: com.ifit.glassos.MusicRegionList
	(*LibraryCategory)(nil),     // 3: com.ifit.glassos.LibraryCategory
	(*LibraryCategoryList)(nil), // 4: com.ifit.glassos.LibraryCategoryList
	(*LibraryCategoryMap)(nil),  // 5: com.ifit.glassos.LibraryCategoryMap
	(*Workout)(nil),             // 6: com.ifit.glassos.Workout
	(*WorkoutList)(nil),         // 7: com.ifit.glassos.WorkoutList
	nil,                         // 8: com.ifit.glassos.LibraryCategoryMap.ItemsEntry
	(WorkoutFilter)(0),          // 9: com.ifit.glassos.WorkoutFilter
	(*MusicRegion)(nil),         // 10: com.ifit.glassos.MusicRegion
	(*ControlList)(nil),         // 11: com.ifit.glassos.ControlList
	(WorkoutTargetType)(0),      // 12: com.ifit.glassos.WorkoutTargetType
	(WorkoutType)(0),            // 13: com.ifit.glassos.WorkoutType
	(*Sources)(nil),             // 14: com.ifit.glassos.Sources
	(*ScaledControls)(nil),      // 15: com.ifit.glassos.ScaledControls
	(*MapCoordinateList)(nil),   // 16: com.ifit.glassos.MapCoordinateList
}
var file_workout_data_Workout_proto_depIdxs = []int32{
	9,  // 0: com.ifit.glassos.WorkoutFilterList.items:type_name -> com.ifit.glassos.WorkoutFilter
	10, // 1: com.ifit.glassos.MusicRegionList.items:type_name -> com.ifit.glassos.MusicRegion
	3,  // 2: com.ifit.glassos.LibraryCategoryList.items:type_name -> com.ifit.glassos.LibraryCategory
	8,  // 3: com.ifit.glassos.LibraryCategoryMap.items:type_name -> com.ifit.glassos.LibraryCategoryMap.ItemsEntry
	0,  // 4: com.ifit.glassos.Workout.categories:type_name -> com.ifit.glassos.StringList
	1,  // 5: com.ifit.glassos.Workout.workoutFilters:type_name -> com.ifit.glassos.WorkoutFilterList
	11, // 6: com.ifit.glassos.Workout.controls:type_name -> com.ifit.glassos.ControlList
	12, // 7: com.ifit.glassos.Workout.targetType:type_name -> com.ifit.glassos.WorkoutTargetType
	13, // 8: com.ifit.glassos.Workout.workoutType:type_name -> com.ifit.glassos.WorkoutType
	2,  // 9: com.ifit.glassos.Workout.videoMusicRegions:type_name -> com.ifit.glassos.MusicRegionList
	14, // 10: com.ifit.glassos.Workout.sources:type_name -> com.ifit.glassos.Sources
	5,  // 11: com.ifit.glassos.Workout.libraryFilters:type_name -> com.ifit.glassos.LibraryCategoryMap
	15, // 12: com.ifit.glassos.Workout.scaledControls:type_name -> com.ifit.glassos.ScaledControls
	16, // 13: com.ifit.glassos.Workout.mapCoordinates:type_name -> com.ifit.glassos.MapCoordinateList
	6,  // 14: com.ifit.glassos.WorkoutList.items:type_name -> com.ifit.glassos.Workout
	4,  // 15: com.ifit.glassos.LibraryCategoryMap.ItemsEntry.value:type_name -> com.ifit.glassos.LibraryCategoryList
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_workout_data_Workout_proto_init() }
func file_workout_data_Workout_proto_init() {
	if File_workout_data_Workout_proto != nil {
		return
	}
	file_workout_data_Control_proto_init()
	file_workout_data_ScaledControls_proto_init()
	file_workout_data_WorkoutCategory_proto_init()
	file_workout_data_WorkoutFilter_proto_init()
	file_workout_data_WorkoutTargetType_proto_init()
	file_workout_data_WorkoutType_proto_init()
	file_workout_data_video_MusicRegion_proto_init()
	file_workout_data_video_Sources_proto_init()
	file_workout_data_map_MapCoordinate_proto_init()
	file_workout_data_Workout_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_Workout_proto_rawDesc), len(file_workout_data_Workout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_Workout_proto_goTypes,
		DependencyIndexes: file_workout_data_Workout_proto_depIdxs,
		MessageInfos:      file_workout_data_Workout_proto_msgTypes,
	}.Build()
	File_workout_data_Workout_proto = out.File
	file_workout_data_Workout_proto_goTypes = nil
	file_workout_data_Workout_proto_depIdxs = nil
}
