// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/WorkoutError.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutErrorCode int32

const (
	WorkoutErrorCode_NO_CONSOLE_CONNECTED WorkoutErrorCode = 0
	WorkoutErrorCode_STATE_INVALID        WorkoutErrorCode = 1
)

// Enum value maps for WorkoutErrorCode.
var (
	WorkoutErrorCode_name = map[int32]string{
		0: "NO_CONSOLE_CONNECTED",
		1: "STATE_INVALID",
	}
	WorkoutErrorCode_value = map[string]int32{
		"NO_CONSOLE_CONNECTED": 0,
		"STATE_INVALID":        1,
	}
)

func (x WorkoutErrorCode) Enum() *WorkoutErrorCode {
	p := new(WorkoutErrorCode)
	*p = x
	return p
}

func (x WorkoutErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_WorkoutError_proto_enumTypes[0].Descriptor()
}

func (WorkoutErrorCode) Type() protoreflect.EnumType {
	return &file_workout_WorkoutError_proto_enumTypes[0]
}

func (x WorkoutErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutErrorCode.Descriptor instead.
func (WorkoutErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_workout_WorkoutError_proto_rawDescGZIP(), []int{0}
}

type WorkoutError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode      WorkoutErrorCode       `protobuf:"varint,1,opt,name=errorCode,proto3,enum=com.ifit.glassos.WorkoutErrorCode" json:"errorCode,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	State          WorkoutState           `protobuf:"varint,3,opt,name=state,proto3,enum=com.ifit.glassos.WorkoutState" json:"state,omitempty"`
	ExpectedStates []WorkoutState         `protobuf:"varint,4,rep,packed,name=expectedStates,proto3,enum=com.ifit.glassos.WorkoutState" json:"expectedStates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkoutError) Reset() {
	*x = WorkoutError{}
	mi := &file_workout_WorkoutError_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutError) ProtoMessage() {}

func (x *WorkoutError) ProtoReflect() protoreflect.Message {
	mi := &file_workout_WorkoutError_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutError.ProtoReflect.Descriptor instead.
func (*WorkoutError) Descriptor() ([]byte, []int) {
	return file_workout_WorkoutError_proto_rawDescGZIP(), []int{0}
}

func (x *WorkoutError) GetErrorCode() WorkoutErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return WorkoutErrorCode_NO_CONSOLE_CONNECTED
}

func (x *WorkoutError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkoutError) GetState() WorkoutState {
	if x != nil {
		return x.State
	}
	return WorkoutState_WORKOUT_STATE_UNKNOWN
}

func (x *WorkoutError) GetExpectedStates() []WorkoutState {
	if x != nil {
		return x.ExpectedStates
	}
	return nil
}

var File_workout_WorkoutError_proto protoreflect.FileDescriptor

const file_workout_WorkoutError_proto_rawDesc = "" +
	"\n" +
	"\x1aworkout/WorkoutError.proto\x12\x10com.ifit.glassos\x1a\x1aworkout/WorkoutState.proto\"\xe8\x01\n" +
	"\fWorkoutError\x12@\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\".com.ifit.glassos.WorkoutErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.com.ifit.glassos.WorkoutStateR\x05state\x12F\n" +
	"\x0eexpectedStates\x18\x04 \x03(\x0e2\x1e.com.ifit.glassos.WorkoutStateR\x0eexpectedStates*?\n" +
	"\x10WorkoutErrorCode\x12\x18\n" +
	"\x14NO_CONSOLE_CONNECTED\x10\x00\x12\x11\n" +
	"\rSTATE_INVALID\x10\x01B6\n" +
	"\x18com.ifit.glassos.workoutB\x11WorkoutErrorProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_WorkoutError_proto_rawDescOnce sync.Once
	file_workout_WorkoutError_proto_rawDescData []byte
)

func file_workout_WorkoutError_proto_rawDescGZIP() []byte {
	file_workout_WorkoutError_proto_rawDescOnce.Do(func() {
		file_workout_WorkoutError_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_WorkoutError_proto_rawDesc), len(file_workout_WorkoutError_proto_rawDesc)))
	})
	return file_workout_WorkoutError_proto_rawDescData
}

var file_workout_WorkoutError_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_WorkoutError_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workout_WorkoutError_proto_goTypes = []any{
	(WorkoutErrorCode)(0), // 0: com.ifit.glassos.WorkoutErrorCode
	(*WorkoutError)(nil),  // 1: com.ifit.glassos.WorkoutError
	(WorkoutState)(0),     // 2: com.ifit.glassos.WorkoutState
}
var file_workout_WorkoutError_proto_depIdxs = []int32{
	0, // 0: com.ifit.glassos.WorkoutError.errorCode:type_name -> com.ifit.glassos.WorkoutErrorCode
	2, // 1: com.ifit.glassos.WorkoutError.state:type_name -> com.ifit.glassos.WorkoutState
	2, // 2: com.ifit.glassos.WorkoutError.expectedStates:type_name -> com.ifit.glassos.WorkoutState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_workout_WorkoutError_proto_init() }
func file_workout_WorkoutError_proto_init() {
	if File_workout_WorkoutError_proto != nil {
		return
	}
	file_workout_WorkoutState_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_WorkoutError_proto_rawDesc), len(file_workout_WorkoutError_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_WorkoutError_proto_goTypes,
		DependencyIndexes: file_workout_WorkoutError_proto_depIdxs,
		EnumInfos:         file_workout_WorkoutError_proto_enumTypes,
		MessageInfos:      file_workout_WorkoutError_proto_msgTypes,
	}.Build()
	File_workout_WorkoutError_proto = out.File
	file_workout_WorkoutError_proto_goTypes = nil
	file_workout_WorkoutError_proto_depIdxs = nil
}
