// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/WorkoutFilter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutFilter int32

const (
	WorkoutFilter_WORKOUT_FILTER_UNKNOWN              WorkoutFilter = 0
	WorkoutFilter_WORKOUT_FILTER_IFIT_BUILT           WorkoutFilter = 1
	WorkoutFilter_WORKOUT_FILTER_IS_MANUAL            WorkoutFilter = 2
	WorkoutFilter_WORKOUT_FILTER_IS_MAP               WorkoutFilter = 3
	WorkoutFilter_WORKOUT_FILTER_IS_VAULT             WorkoutFilter = 4
	WorkoutFilter_WORKOUT_FILTER_IS_VIDEO             WorkoutFilter = 5
	WorkoutFilter_WORKOUT_FILTER_IS_VUE               WorkoutFilter = 6
	WorkoutFilter_WORKOUT_FILTER_PORTRAIT_ORIENTATION WorkoutFilter = 7
	WorkoutFilter_WORKOUT_FILTER_OFF_EQUIPMENT        WorkoutFilter = 8
)

// Enum value maps for WorkoutFilter.
var (
	WorkoutFilter_name = map[int32]string{
		0: "WORKOUT_FILTER_UNKNOWN",
		1: "WORKOUT_FILTER_IFIT_BUILT",
		2: "WORKOUT_FILTER_IS_MANUAL",
		3: "WORKOUT_FILTER_IS_MAP",
		4: "WORKOUT_FILTER_IS_VAULT",
		5: "WORKOUT_FILTER_IS_VIDEO",
		6: "WORKOUT_FILTER_IS_VUE",
		7: "WORKOUT_FILTER_PORTRAIT_ORIENTATION",
		8: "WORKOUT_FILTER_OFF_EQUIPMENT",
	}
	WorkoutFilter_value = map[string]int32{
		"WORKOUT_FILTER_UNKNOWN":              0,
		"WORKOUT_FILTER_IFIT_BUILT":           1,
		"WORKOUT_FILTER_IS_MANUAL":            2,
		"WORKOUT_FILTER_IS_MAP":               3,
		"WORKOUT_FILTER_IS_VAULT":             4,
		"WORKOUT_FILTER_IS_VIDEO":             5,
		"WORKOUT_FILTER_IS_VUE":               6,
		"WORKOUT_FILTER_PORTRAIT_ORIENTATION": 7,
		"WORKOUT_FILTER_OFF_EQUIPMENT":        8,
	}
)

func (x WorkoutFilter) Enum() *WorkoutFilter {
	p := new(WorkoutFilter)
	*p = x
	return p
}

func (x WorkoutFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_data_WorkoutFilter_proto_enumTypes[0].Descriptor()
}

func (WorkoutFilter) Type() protoreflect.EnumType {
	return &file_workout_data_WorkoutFilter_proto_enumTypes[0]
}

func (x WorkoutFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutFilter.Descriptor instead.
func (WorkoutFilter) EnumDescriptor() ([]byte, []int) {
	return file_workout_data_WorkoutFilter_proto_rawDescGZIP(), []int{0}
}

var File_workout_data_WorkoutFilter_proto protoreflect.FileDescriptor

const file_workout_data_WorkoutFilter_proto_rawDesc = "" +
	"\n" +
	" workout/data/WorkoutFilter.proto\x12\x10com.ifit.glassos*\xa3\x02\n" +
	"\rWorkoutFilter\x12\x1a\n" +
	"\x16WORKOUT_FILTER_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19WORKOUT_FILTER_IFIT_BUILT\x10\x01\x12\x1c\n" +
	"\x18WORKOUT_FILTER_IS_MANUAL\x10\x02\x12\x19\n" +
	"\x15WORKOUT_FILTER_IS_MAP\x10\x03\x12\x1b\n" +
	"\x17WORKOUT_FILTER_IS_VAULT\x10\x04\x12\x1b\n" +
	"\x17WORKOUT_FILTER_IS_VIDEO\x10\x05\x12\x19\n" +
	"\x15WORKOUT_FILTER_IS_VUE\x10\x06\x12'\n" +
	"#WORKOUT_FILTER_PORTRAIT_ORIENTATION\x10\a\x12 \n" +
	"\x1cWORKOUT_FILTER_OFF_EQUIPMENT\x10\bB<\n" +
	"\x1dcom.ifit.glassos.workout.dataB\x12WorkoutFilterProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_WorkoutFilter_proto_rawDescOnce sync.Once
	file_workout_data_WorkoutFilter_proto_rawDescData []byte
)

func file_workout_data_WorkoutFilter_proto_rawDescGZIP() []byte {
	file_workout_data_WorkoutFilter_proto_rawDescOnce.Do(func() {
		file_workout_data_WorkoutFilter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutFilter_proto_rawDesc), len(file_workout_data_WorkoutFilter_proto_rawDesc)))
	})
	return file_workout_data_WorkoutFilter_proto_rawDescData
}

var file_workout_data_WorkoutFilter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_data_WorkoutFilter_proto_goTypes = []any{
	(WorkoutFilter)(0), // 0: com.ifit.glassos.WorkoutFilter
}
var file_workout_data_WorkoutFilter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_WorkoutFilter_proto_init() }
func file_workout_data_WorkoutFilter_proto_init() {
	if File_workout_data_WorkoutFilter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutFilter_proto_rawDesc), len(file_workout_data_WorkoutFilter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_WorkoutFilter_proto_goTypes,
		DependencyIndexes: file_workout_data_WorkoutFilter_proto_depIdxs,
		EnumInfos:         file_workout_data_WorkoutFilter_proto_enumTypes,
	}.Build()
	File_workout_data_WorkoutFilter_proto = out.File
	file_workout_data_WorkoutFilter_proto_goTypes = nil
	file_workout_data_WorkoutFilter_proto_depIdxs = nil
}
