// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/WorkoutType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutType int32

const (
	WorkoutType_WORKOUT_TYPE_UNKNOWN        WorkoutType = 0
	WorkoutType_WORKOUT_TYPE_CARDIO         WorkoutType = 1
	WorkoutType_WORKOUT_TYPE_CYCLE          WorkoutType = 2
	WorkoutType_WORKOUT_TYPE_FUSION         WorkoutType = 3
	WorkoutType_WORKOUT_TYPE_ROW            WorkoutType = 4
	WorkoutType_WORKOUT_TYPE_RUN            WorkoutType = 5
	WorkoutType_WORKOUT_TYPE_STRENGTH       WorkoutType = 6
	WorkoutType_WORKOUT_TYPE_VIBRATION      WorkoutType = 7
	WorkoutType_WORKOUT_TYPE_CROSS_TRAINING WorkoutType = 8
)

// Enum value maps for WorkoutType.
var (
	WorkoutType_name = map[int32]string{
		0: "WORKOUT_TYPE_UNKNOWN",
		1: "WORKOUT_TYPE_CARDIO",
		2: "WORKOUT_TYPE_CYCLE",
		3: "WORKOUT_TYPE_FUSION",
		4: "WORKOUT_TYPE_ROW",
		5: "WORKOUT_TYPE_RUN",
		6: "WORKOUT_TYPE_STRENGTH",
		7: "WORKOUT_TYPE_VIBRATION",
		8: "WORKOUT_TYPE_CROSS_TRAINING",
	}
	WorkoutType_value = map[string]int32{
		"WORKOUT_TYPE_UNKNOWN":        0,
		"WORKOUT_TYPE_CARDIO":         1,
		"WORKOUT_TYPE_CYCLE":          2,
		"WORKOUT_TYPE_FUSION":         3,
		"WORKOUT_TYPE_ROW":            4,
		"WORKOUT_TYPE_RUN":            5,
		"WORKOUT_TYPE_STRENGTH":       6,
		"WORKOUT_TYPE_VIBRATION":      7,
		"WORKOUT_TYPE_CROSS_TRAINING": 8,
	}
)

func (x WorkoutType) Enum() *WorkoutType {
	p := new(WorkoutType)
	*p = x
	return p
}

func (x WorkoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_data_WorkoutType_proto_enumTypes[0].Descriptor()
}

func (WorkoutType) Type() protoreflect.EnumType {
	return &file_workout_data_WorkoutType_proto_enumTypes[0]
}

func (x WorkoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutType.Descriptor instead.
func (WorkoutType) EnumDescriptor() ([]byte, []int) {
	return file_workout_data_WorkoutType_proto_rawDescGZIP(), []int{0}
}

var File_workout_data_WorkoutType_proto protoreflect.FileDescriptor

const file_workout_data_WorkoutType_proto_rawDesc = "" +
	"\n" +
	"\x1eworkout/data/WorkoutType.proto\x12\x10com.ifit.glassos*\xf5\x01\n" +
	"\vWorkoutType\x12\x18\n" +
	"\x14WORKOUT_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13WORKOUT_TYPE_CARDIO\x10\x01\x12\x16\n" +
	"\x12WORKOUT_TYPE_CYCLE\x10\x02\x12\x17\n" +
	"\x13WORKOUT_TYPE_FUSION\x10\x03\x12\x14\n" +
	"\x10WORKOUT_TYPE_ROW\x10\x04\x12\x14\n" +
	"\x10WORKOUT_TYPE_RUN\x10\x05\x12\x19\n" +
	"\x15WORKOUT_TYPE_STRENGTH\x10\x06\x12\x1a\n" +
	"\x16WORKOUT_TYPE_VIBRATION\x10\a\x12\x1f\n" +
	"\x1bWORKOUT_TYPE_CROSS_TRAINING\x10\bB:\n" +
	"\x1dcom.ifit.glassos.workout.dataB\x10WorkoutTypeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_WorkoutType_proto_rawDescOnce sync.Once
	file_workout_data_WorkoutType_proto_rawDescData []byte
)

func file_workout_data_WorkoutType_proto_rawDescGZIP() []byte {
	file_workout_data_WorkoutType_proto_rawDescOnce.Do(func() {
		file_workout_data_WorkoutType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutType_proto_rawDesc), len(file_workout_data_WorkoutType_proto_rawDesc)))
	})
	return file_workout_data_WorkoutType_proto_rawDescData
}

var file_workout_data_WorkoutType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_data_WorkoutType_proto_goTypes = []any{
	(WorkoutType)(0), // 0: com.ifit.glassos.WorkoutType
}
var file_workout_data_WorkoutType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_WorkoutType_proto_init() }
func file_workout_data_WorkoutType_proto_init() {
	if File_workout_data_WorkoutType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutType_proto_rawDesc), len(file_workout_data_WorkoutType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_WorkoutType_proto_goTypes,
		DependencyIndexes: file_workout_data_WorkoutType_proto_depIdxs,
		EnumInfos:         file_workout_data_WorkoutType_proto_enumTypes,
	}.Build()
	File_workout_data_WorkoutType_proto = out.File
	file_workout_data_WorkoutType_proto_goTypes = nil
	file_workout_data_WorkoutType_proto_depIdxs = nil
}
