// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/WorkoutTargetType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutTargetType int32

const (
	WorkoutTargetType_WORKOUT_TARGET_TYPE_UNKNOWN  WorkoutTargetType = 0
	WorkoutTargetType_WORKOUT_TARGET_TYPE_CALORIES WorkoutTargetType = 1
	WorkoutTargetType_WORKOUT_TARGET_TYPE_METERS   WorkoutTargetType = 2
	WorkoutTargetType_WORKOUT_TARGET_TYPE_SECONDS  WorkoutTargetType = 3
)

// Enum value maps for WorkoutTargetType.
var (
	WorkoutTargetType_name = map[int32]string{
		0: "WORKOUT_TARGET_TYPE_UNKNOWN",
		1: "WORKOUT_TARGET_TYPE_CALORIES",
		2: "WORKOUT_TARGET_TYPE_METERS",
		3: "WORKOUT_TARGET_TYPE_SECONDS",
	}
	WorkoutTargetType_value = map[string]int32{
		"WORKOUT_TARGET_TYPE_UNKNOWN":  0,
		"WORKOUT_TARGET_TYPE_CALORIES": 1,
		"WORKOUT_TARGET_TYPE_METERS":   2,
		"WORKOUT_TARGET_TYPE_SECONDS":  3,
	}
)

func (x WorkoutTargetType) Enum() *WorkoutTargetType {
	p := new(WorkoutTargetType)
	*p = x
	return p
}

func (x WorkoutTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_workout_data_WorkoutTargetType_proto_enumTypes[0].Descriptor()
}

func (WorkoutTargetType) Type() protoreflect.EnumType {
	return &file_workout_data_WorkoutTargetType_proto_enumTypes[0]
}

func (x WorkoutTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutTargetType.Descriptor instead.
func (WorkoutTargetType) EnumDescriptor() ([]byte, []int) {
	return file_workout_data_WorkoutTargetType_proto_rawDescGZIP(), []int{0}
}

var File_workout_data_WorkoutTargetType_proto protoreflect.FileDescriptor

const file_workout_data_WorkoutTargetType_proto_rawDesc = "" +
	"\n" +
	"$workout/data/WorkoutTargetType.proto\x12\x10com.ifit.glassos*\x97\x01\n" +
	"\x11WorkoutTargetType\x12\x1f\n" +
	"\x1bWORKOUT_TARGET_TYPE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cWORKOUT_TARGET_TYPE_CALORIES\x10\x01\x12\x1e\n" +
	"\x1aWORKOUT_TARGET_TYPE_METERS\x10\x02\x12\x1f\n" +
	"\x1bWORKOUT_TARGET_TYPE_SECONDS\x10\x03B@\n" +
	"\x1dcom.ifit.glassos.workout.dataB\x16WorkoutTargetTypeProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_WorkoutTargetType_proto_rawDescOnce sync.Once
	file_workout_data_WorkoutTargetType_proto_rawDescData []byte
)

func file_workout_data_WorkoutTargetType_proto_rawDescGZIP() []byte {
	file_workout_data_WorkoutTargetType_proto_rawDescOnce.Do(func() {
		file_workout_data_WorkoutTargetType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutTargetType_proto_rawDesc), len(file_workout_data_WorkoutTargetType_proto_rawDesc)))
	})
	return file_workout_data_WorkoutTargetType_proto_rawDescData
}

var file_workout_data_WorkoutTargetType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workout_data_WorkoutTargetType_proto_goTypes = []any{
	(WorkoutTargetType)(0), // 0: com.ifit.glassos.WorkoutTargetType
}
var file_workout_data_WorkoutTargetType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workout_data_WorkoutTargetType_proto_init() }
func file_workout_data_WorkoutTargetType_proto_init() {
	if File_workout_data_WorkoutTargetType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutTargetType_proto_rawDesc), len(file_workout_data_WorkoutTargetType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_WorkoutTargetType_proto_goTypes,
		DependencyIndexes: file_workout_data_WorkoutTargetType_proto_depIdxs,
		EnumInfos:         file_workout_data_WorkoutTargetType_proto_enumTypes,
	}.Build()
	File_workout_data_WorkoutTargetType_proto = out.File
	file_workout_data_WorkoutTargetType_proto_goTypes = nil
	file_workout_data_WorkoutTargetType_proto_depIdxs = nil
}
