// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/WorkoutSessionState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutSessionState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CurrentWorkoutItem   *WorkoutSessionItem    `protobuf:"bytes,1,opt,name=currentWorkoutItem,proto3,oneof" json:"currentWorkoutItem,omitempty"`
	CurrentWorkoutState  WorkoutState           `protobuf:"varint,2,opt,name=currentWorkoutState,proto3,enum=com.ifit.glassos.WorkoutState" json:"currentWorkoutState,omitempty"`
	PreviousWorkoutItem  *WorkoutSessionItem    `protobuf:"bytes,3,opt,name=previousWorkoutItem,proto3,oneof" json:"previousWorkoutItem,omitempty"`
	PreviousWorkoutState WorkoutState           `protobuf:"varint,4,opt,name=previousWorkoutState,proto3,enum=com.ifit.glassos.WorkoutState" json:"previousWorkoutState,omitempty"`
	NextWorkoutItem      *WorkoutSessionItem    `protobuf:"bytes,5,opt,name=nextWorkoutItem,proto3,oneof" json:"nextWorkoutItem,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkoutSessionState) Reset() {
	*x = WorkoutSessionState{}
	mi := &file_workout_data_WorkoutSessionState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutSessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutSessionState) ProtoMessage() {}

func (x *WorkoutSessionState) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_WorkoutSessionState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutSessionState.ProtoReflect.Descriptor instead.
func (*WorkoutSessionState) Descriptor() ([]byte, []int) {
	return file_workout_data_WorkoutSessionState_proto_rawDescGZIP(), []int{0}
}

func (x *WorkoutSessionState) GetCurrentWorkoutItem() *WorkoutSessionItem {
	if x != nil {
		return x.CurrentWorkoutItem
	}
	return nil
}

func (x *WorkoutSessionState) GetCurrentWorkoutState() WorkoutState {
	if x != nil {
		return x.CurrentWorkoutState
	}
	return WorkoutState_WORKOUT_STATE_UNKNOWN
}

func (x *WorkoutSessionState) GetPreviousWorkoutItem() *WorkoutSessionItem {
	if x != nil {
		return x.PreviousWorkoutItem
	}
	return nil
}

func (x *WorkoutSessionState) GetPreviousWorkoutState() WorkoutState {
	if x != nil {
		return x.PreviousWorkoutState
	}
	return WorkoutState_WORKOUT_STATE_UNKNOWN
}

func (x *WorkoutSessionState) GetNextWorkoutItem() *WorkoutSessionItem {
	if x != nil {
		return x.NextWorkoutItem
	}
	return nil
}

var File_workout_data_WorkoutSessionState_proto protoreflect.FileDescriptor

const file_workout_data_WorkoutSessionState_proto_rawDesc = "" +
	"\n" +
	"&workout/data/WorkoutSessionState.proto\x12\x10com.ifit.glassos\x1a\x1aworkout/WorkoutState.proto\x1a%workout/data/WorkoutSessionItem.proto\"\x8b\x04\n" +
	"\x13WorkoutSessionState\x12Y\n" +
	"\x12currentWorkoutItem\x18\x01 \x01(\v2$.com.ifit.glassos.WorkoutSessionItemH\x00R\x12currentWorkoutItem\x88\x01\x01\x12P\n" +
	"\x13currentWorkoutState\x18\x02 \x01(\x0e2\x1e.com.ifit.glassos.WorkoutStateR\x13currentWorkoutState\x12[\n" +
	"\x13previousWorkoutItem\x18\x03 \x01(\v2$.com.ifit.glassos.WorkoutSessionItemH\x01R\x13previousWorkoutItem\x88\x01\x01\x12R\n" +
	"\x14previousWorkoutState\x18\x04 \x01(\x0e2\x1e.com.ifit.glassos.WorkoutStateR\x14previousWorkoutState\x12S\n" +
	"\x0fnextWorkoutItem\x18\x05 \x01(\v2$.com.ifit.glassos.WorkoutSessionItemH\x02R\x0fnextWorkoutItem\x88\x01\x01B\x15\n" +
	"\x13_currentWorkoutItemB\x16\n" +
	"\x14_previousWorkoutItemB\x12\n" +
	"\x10_nextWorkoutItemBB\n" +
	"\x1dcom.ifit.glassos.workout.dataB\x18WorkoutSessionStateProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_WorkoutSessionState_proto_rawDescOnce sync.Once
	file_workout_data_WorkoutSessionState_proto_rawDescData []byte
)

func file_workout_data_WorkoutSessionState_proto_rawDescGZIP() []byte {
	file_workout_data_WorkoutSessionState_proto_rawDescOnce.Do(func() {
		file_workout_data_WorkoutSessionState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutSessionState_proto_rawDesc), len(file_workout_data_WorkoutSessionState_proto_rawDesc)))
	})
	return file_workout_data_WorkoutSessionState_proto_rawDescData
}

var file_workout_data_WorkoutSessionState_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workout_data_WorkoutSessionState_proto_goTypes = []any{
	(*WorkoutSessionState)(nil), // 0: com.ifit.glassos.WorkoutSessionState
	(*WorkoutSessionItem)(nil),  // 1: com.ifit.glassos.WorkoutSessionItem
	(WorkoutState)(0),           // 2: com.ifit.glassos.WorkoutState
}
var file_workout_data_WorkoutSessionState_proto_depIdxs = []int32{
	1, // 0: com.ifit.glassos.WorkoutSessionState.currentWorkoutItem:type_name -> com.ifit.glassos.WorkoutSessionItem
	2, // 1: com.ifit.glassos.WorkoutSessionState.currentWorkoutState:type_name -> com.ifit.glassos.WorkoutState
	1, // 2: com.ifit.glassos.WorkoutSessionState.previousWorkoutItem:type_name -> com.ifit.glassos.WorkoutSessionItem
	2, // 3: com.ifit.glassos.WorkoutSessionState.previousWorkoutState:type_name -> com.ifit.glassos.WorkoutState
	1, // 4: com.ifit.glassos.WorkoutSessionState.nextWorkoutItem:type_name -> com.ifit.glassos.WorkoutSessionItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_workout_data_WorkoutSessionState_proto_init() }
func file_workout_data_WorkoutSessionState_proto_init() {
	if File_workout_data_WorkoutSessionState_proto != nil {
		return
	}
	file_workout_WorkoutState_proto_init()
	file_workout_data_WorkoutSessionItem_proto_init()
	file_workout_data_WorkoutSessionState_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutSessionState_proto_rawDesc), len(file_workout_data_WorkoutSessionState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_WorkoutSessionState_proto_goTypes,
		DependencyIndexes: file_workout_data_WorkoutSessionState_proto_depIdxs,
		MessageInfos:      file_workout_data_WorkoutSessionState_proto_msgTypes,
	}.Build()
	File_workout_data_WorkoutSessionState_proto = out.File
	file_workout_data_WorkoutSessionState_proto_goTypes = nil
	file_workout_data_WorkoutSessionState_proto_depIdxs = nil
}
