// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workout/data/WorkoutSessionItem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkoutSessionItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Workout           *Workout               `protobuf:"bytes,1,opt,name=workout,proto3" json:"workout,omitempty"`
	ItemType          ItemType               `protobuf:"varint,2,opt,name=itemType,proto3,enum=com.ifit.glassos.ItemType" json:"itemType,omitempty"`
	WorkoutInstanceId *string                `protobuf:"bytes,3,opt,name=workoutInstanceId,proto3,oneof" json:"workoutInstanceId,omitempty"`
	Metadata          *ActivityLogMetadata   `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkoutSessionItem) Reset() {
	*x = WorkoutSessionItem{}
	mi := &file_workout_data_WorkoutSessionItem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutSessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutSessionItem) ProtoMessage() {}

func (x *WorkoutSessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_WorkoutSessionItem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutSessionItem.ProtoReflect.Descriptor instead.
func (*WorkoutSessionItem) Descriptor() ([]byte, []int) {
	return file_workout_data_WorkoutSessionItem_proto_rawDescGZIP(), []int{0}
}

func (x *WorkoutSessionItem) GetWorkout() *Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

func (x *WorkoutSessionItem) GetItemType() ItemType {
	if x != nil {
		return x.ItemType
	}
	return ItemType_ITEM_TYPE_WARM_UP
}

func (x *WorkoutSessionItem) GetWorkoutInstanceId() string {
	if x != nil && x.WorkoutInstanceId != nil {
		return *x.WorkoutInstanceId
	}
	return ""
}

func (x *WorkoutSessionItem) GetMetadata() *ActivityLogMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WorkoutSessionItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WorkoutSessionItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutSessionItemList) Reset() {
	*x = WorkoutSessionItemList{}
	mi := &file_workout_data_WorkoutSessionItem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutSessionItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutSessionItemList) ProtoMessage() {}

func (x *WorkoutSessionItemList) ProtoReflect() protoreflect.Message {
	mi := &file_workout_data_WorkoutSessionItem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutSessionItemList.ProtoReflect.Descriptor instead.
func (*WorkoutSessionItemList) Descriptor() ([]byte, []int) {
	return file_workout_data_WorkoutSessionItem_proto_rawDescGZIP(), []int{1}
}

func (x *WorkoutSessionItemList) GetItems() []*WorkoutSessionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_workout_data_WorkoutSessionItem_proto protoreflect.FileDescriptor

const file_workout_data_WorkoutSessionItem_proto_rawDesc = "" +
	"\n" +
	"%workout/data/WorkoutSessionItem.proto\x12\x10com.ifit.glassos\x1a%activitylog/ActivityLogMetadata.proto\x1a\x1bworkout/data/ItemType.proto\x1a\x1aworkout/data/Workout.proto\"\x8d\x02\n" +
	"\x12WorkoutSessionItem\x123\n" +
	"\aworkout\x18\x01 \x01(\v2\x19.com.ifit.glassos.WorkoutR\aworkout\x126\n" +
	"\bitemType\x18\x02 \x01(\x0e2\x1a.com.ifit.glassos.ItemTypeR\bitemType\x121\n" +
	"\x11workoutInstanceId\x18\x03 \x01(\tH\x00R\x11workoutInstanceId\x88\x01\x01\x12A\n" +
	"\bmetadata\x18\x04 \x01(\v2%.com.ifit.glassos.ActivityLogMetadataR\bmetadataB\x14\n" +
	"\x12_workoutInstanceId\"T\n" +
	"\x16WorkoutSessionItemList\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.com.ifit.glassos.WorkoutSessionItemR\x05itemsBA\n" +
	"\x1dcom.ifit.glassos.workout.dataB\x17WorkoutSessionItemProtoP\x01\xba\x02\x04IFitb\x06proto3"

var (
	file_workout_data_WorkoutSessionItem_proto_rawDescOnce sync.Once
	file_workout_data_WorkoutSessionItem_proto_rawDescData []byte
)

func file_workout_data_WorkoutSessionItem_proto_rawDescGZIP() []byte {
	file_workout_data_WorkoutSessionItem_proto_rawDescOnce.Do(func() {
		file_workout_data_WorkoutSessionItem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutSessionItem_proto_rawDesc), len(file_workout_data_WorkoutSessionItem_proto_rawDesc)))
	})
	return file_workout_data_WorkoutSessionItem_proto_rawDescData
}

var file_workout_data_WorkoutSessionItem_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workout_data_WorkoutSessionItem_proto_goTypes = []any{
	(*WorkoutSessionItem)(nil),     // 0: com.ifit.glassos.WorkoutSessionItem
	(*WorkoutSessionItemList)(nil), // 1: com.ifit.glassos.WorkoutSessionItemList
	(*Workout)(nil),                // 2: com.ifit.glassos.Workout
	(ItemType)(0),                  // 3: com.ifit.glassos.ItemType
	(*ActivityLogMetadata)(nil),    // 4: com.ifit.glassos.ActivityLogMetadata
}
var file_workout_data_WorkoutSessionItem_proto_depIdxs = []int32{
	2, // 0: com.ifit.glassos.WorkoutSessionItem.workout:type_name -> com.ifit.glassos.Workout
	3, // 1: com.ifit.glassos.WorkoutSessionItem.itemType:type_name -> com.ifit.glassos.ItemType
	4, // 2: com.ifit.glassos.WorkoutSessionItem.metadata:type_name -> com.ifit.glassos.ActivityLogMetadata
	0, // 3: com.ifit.glassos.WorkoutSessionItemList.items:type_name -> com.ifit.glassos.WorkoutSessionItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workout_data_WorkoutSessionItem_proto_init() }
func file_workout_data_WorkoutSessionItem_proto_init() {
	if File_workout_data_WorkoutSessionItem_proto != nil {
		return
	}
	file_activitylog_ActivityLogMetadata_proto_init()
	file_workout_data_ItemType_proto_init()
	file_workout_data_Workout_proto_init()
	file_workout_data_WorkoutSessionItem_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_data_WorkoutSessionItem_proto_rawDesc), len(file_workout_data_WorkoutSessionItem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workout_data_WorkoutSessionItem_proto_goTypes,
		DependencyIndexes: file_workout_data_WorkoutSessionItem_proto_depIdxs,
		MessageInfos:      file_workout_data_WorkoutSessionItem_proto_msgTypes,
	}.Build()
	File_workout_data_WorkoutSessionItem_proto = out.File
	file_workout_data_WorkoutSessionItem_proto_goTypes = nil
	file_workout_data_WorkoutSessionItem_proto_depIdxs = nil
}
